/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.portal_egov.portlet.tthc.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.portal_egov.portlet.tthc.model.TTHC_Category;
import com.portal_egov.portlet.tthc.model.TTHC_CategoryModel;
import com.portal_egov.portlet.tthc.model.TTHC_CategorySoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the TTHC_Category service. Represents a row in the &quot;tthc_category&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.portal_egov.portlet.tthc.model.TTHC_CategoryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TTHC_CategoryImpl}.
 * </p>
 *
 * @author HungDX
 * @see TTHC_CategoryImpl
 * @see com.portal_egov.portlet.tthc.model.TTHC_Category
 * @see com.portal_egov.portlet.tthc.model.TTHC_CategoryModel
 * @generated
 */
@JSON(strict = true)
public class TTHC_CategoryModelImpl extends BaseModelImpl<TTHC_Category>
	implements TTHC_CategoryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a t t h c_ category model instance should use the {@link com.portal_egov.portlet.tthc.model.TTHC_Category} interface instead.
	 */
	public static final String TABLE_NAME = "tthc_category";
	public static final Object[][] TABLE_COLUMNS = {
			{ "categoryId", Types.BIGINT },
			{ "parentId", Types.BIGINT },
			{ "categoryTypeId", Types.INTEGER },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "categoryName", Types.VARCHAR },
			{ "categoryDesc", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "displayPriority", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table tthc_category (categoryId LONG not null primary key,parentId LONG,categoryTypeId INTEGER,companyId LONG,groupId LONG,userId LONG,categoryName VARCHAR(300) null,categoryDesc VARCHAR(1000) null,createDate DATE null,modifiedDate DATE null,displayPriority INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table tthc_category";
	public static final String ORDER_BY_JPQL = " ORDER BY tthc_Category.displayPriority ASC";
	public static final String ORDER_BY_SQL = " ORDER BY tthc_category.displayPriority ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.portal_egov.portlet.tthc.model.TTHC_Category"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.portal_egov.portlet.tthc.model.TTHC_Category"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.portal_egov.portlet.tthc.model.TTHC_Category"),
			true);
	public static long CATEGORYTYPEID_COLUMN_BITMASK = 1L;
	public static long COMPANYID_COLUMN_BITMASK = 2L;
	public static long GROUPID_COLUMN_BITMASK = 4L;
	public static long PARENTID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TTHC_Category toModel(TTHC_CategorySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TTHC_Category model = new TTHC_CategoryImpl();

		model.setCategoryId(soapModel.getCategoryId());
		model.setParentId(soapModel.getParentId());
		model.setCategoryTypeId(soapModel.getCategoryTypeId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setCategoryName(soapModel.getCategoryName());
		model.setCategoryDesc(soapModel.getCategoryDesc());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setDisplayPriority(soapModel.getDisplayPriority());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TTHC_Category> toModels(TTHC_CategorySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TTHC_Category> models = new ArrayList<TTHC_Category>(soapModels.length);

		for (TTHC_CategorySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.portal_egov.portlet.tthc.model.TTHC_Category"));

	public TTHC_CategoryModelImpl() {
	}

	public long getPrimaryKey() {
		return _categoryId;
	}

	public void setPrimaryKey(long primaryKey) {
		setCategoryId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_categoryId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return TTHC_Category.class;
	}

	public String getModelClassName() {
		return TTHC_Category.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("categoryId", getCategoryId());
		attributes.put("parentId", getParentId());
		attributes.put("categoryTypeId", getCategoryTypeId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("categoryName", getCategoryName());
		attributes.put("categoryDesc", getCategoryDesc());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("displayPriority", getDisplayPriority());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long categoryId = (Long)attributes.get("categoryId");

		if (categoryId != null) {
			setCategoryId(categoryId);
		}

		Long parentId = (Long)attributes.get("parentId");

		if (parentId != null) {
			setParentId(parentId);
		}

		Integer categoryTypeId = (Integer)attributes.get("categoryTypeId");

		if (categoryTypeId != null) {
			setCategoryTypeId(categoryTypeId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String categoryName = (String)attributes.get("categoryName");

		if (categoryName != null) {
			setCategoryName(categoryName);
		}

		String categoryDesc = (String)attributes.get("categoryDesc");

		if (categoryDesc != null) {
			setCategoryDesc(categoryDesc);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Integer displayPriority = (Integer)attributes.get("displayPriority");

		if (displayPriority != null) {
			setDisplayPriority(displayPriority);
		}
	}

	@JSON
	public long getCategoryId() {
		return _categoryId;
	}

	public void setCategoryId(long categoryId) {
		_categoryId = categoryId;
	}

	@JSON
	public long getParentId() {
		return _parentId;
	}

	public void setParentId(long parentId) {
		_columnBitmask |= PARENTID_COLUMN_BITMASK;

		if (!_setOriginalParentId) {
			_setOriginalParentId = true;

			_originalParentId = _parentId;
		}

		_parentId = parentId;
	}

	public long getOriginalParentId() {
		return _originalParentId;
	}

	@JSON
	public int getCategoryTypeId() {
		return _categoryTypeId;
	}

	public void setCategoryTypeId(int categoryTypeId) {
		_columnBitmask |= CATEGORYTYPEID_COLUMN_BITMASK;

		if (!_setOriginalCategoryTypeId) {
			_setOriginalCategoryTypeId = true;

			_originalCategoryTypeId = _categoryTypeId;
		}

		_categoryTypeId = categoryTypeId;
	}

	public int getOriginalCategoryTypeId() {
		return _originalCategoryTypeId;
	}

	@JSON
	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	public String getCategoryName() {
		if (_categoryName == null) {
			return StringPool.BLANK;
		}
		else {
			return _categoryName;
		}
	}

	public void setCategoryName(String categoryName) {
		_categoryName = categoryName;
	}

	@JSON
	public String getCategoryDesc() {
		if (_categoryDesc == null) {
			return StringPool.BLANK;
		}
		else {
			return _categoryDesc;
		}
	}

	public void setCategoryDesc(String categoryDesc) {
		_categoryDesc = categoryDesc;
	}

	@JSON
	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	public int getDisplayPriority() {
		return _displayPriority;
	}

	public void setDisplayPriority(int displayPriority) {
		_columnBitmask = -1L;

		_displayPriority = displayPriority;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			TTHC_Category.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TTHC_Category toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (TTHC_Category)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		TTHC_CategoryImpl tthc_CategoryImpl = new TTHC_CategoryImpl();

		tthc_CategoryImpl.setCategoryId(getCategoryId());
		tthc_CategoryImpl.setParentId(getParentId());
		tthc_CategoryImpl.setCategoryTypeId(getCategoryTypeId());
		tthc_CategoryImpl.setCompanyId(getCompanyId());
		tthc_CategoryImpl.setGroupId(getGroupId());
		tthc_CategoryImpl.setUserId(getUserId());
		tthc_CategoryImpl.setCategoryName(getCategoryName());
		tthc_CategoryImpl.setCategoryDesc(getCategoryDesc());
		tthc_CategoryImpl.setCreateDate(getCreateDate());
		tthc_CategoryImpl.setModifiedDate(getModifiedDate());
		tthc_CategoryImpl.setDisplayPriority(getDisplayPriority());

		tthc_CategoryImpl.resetOriginalValues();

		return tthc_CategoryImpl;
	}

	public int compareTo(TTHC_Category tthc_Category) {
		int value = 0;

		if (getDisplayPriority() < tthc_Category.getDisplayPriority()) {
			value = -1;
		}
		else if (getDisplayPriority() > tthc_Category.getDisplayPriority()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		TTHC_Category tthc_Category = null;

		try {
			tthc_Category = (TTHC_Category)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = tthc_Category.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TTHC_CategoryModelImpl tthc_CategoryModelImpl = this;

		tthc_CategoryModelImpl._originalParentId = tthc_CategoryModelImpl._parentId;

		tthc_CategoryModelImpl._setOriginalParentId = false;

		tthc_CategoryModelImpl._originalCategoryTypeId = tthc_CategoryModelImpl._categoryTypeId;

		tthc_CategoryModelImpl._setOriginalCategoryTypeId = false;

		tthc_CategoryModelImpl._originalCompanyId = tthc_CategoryModelImpl._companyId;

		tthc_CategoryModelImpl._setOriginalCompanyId = false;

		tthc_CategoryModelImpl._originalGroupId = tthc_CategoryModelImpl._groupId;

		tthc_CategoryModelImpl._setOriginalGroupId = false;

		tthc_CategoryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TTHC_Category> toCacheModel() {
		TTHC_CategoryCacheModel tthc_CategoryCacheModel = new TTHC_CategoryCacheModel();

		tthc_CategoryCacheModel.categoryId = getCategoryId();

		tthc_CategoryCacheModel.parentId = getParentId();

		tthc_CategoryCacheModel.categoryTypeId = getCategoryTypeId();

		tthc_CategoryCacheModel.companyId = getCompanyId();

		tthc_CategoryCacheModel.groupId = getGroupId();

		tthc_CategoryCacheModel.userId = getUserId();

		tthc_CategoryCacheModel.categoryName = getCategoryName();

		String categoryName = tthc_CategoryCacheModel.categoryName;

		if ((categoryName != null) && (categoryName.length() == 0)) {
			tthc_CategoryCacheModel.categoryName = null;
		}

		tthc_CategoryCacheModel.categoryDesc = getCategoryDesc();

		String categoryDesc = tthc_CategoryCacheModel.categoryDesc;

		if ((categoryDesc != null) && (categoryDesc.length() == 0)) {
			tthc_CategoryCacheModel.categoryDesc = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			tthc_CategoryCacheModel.createDate = createDate.getTime();
		}
		else {
			tthc_CategoryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			tthc_CategoryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			tthc_CategoryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		tthc_CategoryCacheModel.displayPriority = getDisplayPriority();

		return tthc_CategoryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{categoryId=");
		sb.append(getCategoryId());
		sb.append(", parentId=");
		sb.append(getParentId());
		sb.append(", categoryTypeId=");
		sb.append(getCategoryTypeId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", categoryName=");
		sb.append(getCategoryName());
		sb.append(", categoryDesc=");
		sb.append(getCategoryDesc());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", displayPriority=");
		sb.append(getDisplayPriority());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.portal_egov.portlet.tthc.model.TTHC_Category");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>categoryId</column-name><column-value><![CDATA[");
		sb.append(getCategoryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>parentId</column-name><column-value><![CDATA[");
		sb.append(getParentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>categoryTypeId</column-name><column-value><![CDATA[");
		sb.append(getCategoryTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>categoryName</column-name><column-value><![CDATA[");
		sb.append(getCategoryName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>categoryDesc</column-name><column-value><![CDATA[");
		sb.append(getCategoryDesc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>displayPriority</column-name><column-value><![CDATA[");
		sb.append(getDisplayPriority());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TTHC_Category.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			TTHC_Category.class
		};
	private long _categoryId;
	private long _parentId;
	private long _originalParentId;
	private boolean _setOriginalParentId;
	private int _categoryTypeId;
	private int _originalCategoryTypeId;
	private boolean _setOriginalCategoryTypeId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private String _userUuid;
	private String _categoryName;
	private String _categoryDesc;
	private Date _createDate;
	private Date _modifiedDate;
	private int _displayPriority;
	private long _columnBitmask;
	private TTHC_Category _escapedModelProxy;
}