/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.portal_egov.portlet.proposition_feedback.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Proposition service. Represents a row in the &quot;Proposition&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.portal_egov.portlet.proposition_feedback.model.impl.PropositionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.portal_egov.portlet.proposition_feedback.model.impl.PropositionImpl}.
 * </p>
 *
 * @author HungDX
 * @see Proposition
 * @see com.portal_egov.portlet.proposition_feedback.model.impl.PropositionImpl
 * @see com.portal_egov.portlet.proposition_feedback.model.impl.PropositionModelImpl
 * @generated
 */
public interface PropositionModel extends BaseModel<Proposition>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a proposition model instance should use the {@link Proposition} interface instead.
	 */

	/**
	 * Returns the primary key of this proposition.
	 *
	 * @return the primary key of this proposition
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this proposition.
	 *
	 * @param primaryKey the primary key of this proposition
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the proposition ID of this proposition.
	 *
	 * @return the proposition ID of this proposition
	 */
	public long getPropositionId();

	/**
	 * Sets the proposition ID of this proposition.
	 *
	 * @param propositionId the proposition ID of this proposition
	 */
	public void setPropositionId(long propositionId);

	/**
	 * Returns the company ID of this proposition.
	 *
	 * @return the company ID of this proposition
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this proposition.
	 *
	 * @param companyId the company ID of this proposition
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this proposition.
	 *
	 * @return the group ID of this proposition
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this proposition.
	 *
	 * @param groupId the group ID of this proposition
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this proposition.
	 *
	 * @return the user ID of this proposition
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this proposition.
	 *
	 * @param userId the user ID of this proposition
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this proposition.
	 *
	 * @return the user uuid of this proposition
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this proposition.
	 *
	 * @param userUuid the user uuid of this proposition
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this proposition.
	 *
	 * @return the user name of this proposition
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this proposition.
	 *
	 * @param userName the user name of this proposition
	 */
	public void setUserName(String userName);

	/**
	 * Returns the category ID of this proposition.
	 *
	 * @return the category ID of this proposition
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this proposition.
	 *
	 * @param categoryId the category ID of this proposition
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the compilation department ID of this proposition.
	 *
	 * @return the compilation department ID of this proposition
	 */
	public long getCompilationDepartmentId();

	/**
	 * Sets the compilation department ID of this proposition.
	 *
	 * @param compilationDepartmentId the compilation department ID of this proposition
	 */
	public void setCompilationDepartmentId(long compilationDepartmentId);

	/**
	 * Returns the verification department ID of this proposition.
	 *
	 * @return the verification department ID of this proposition
	 */
	public long getVerificationDepartmentId();

	/**
	 * Sets the verification department ID of this proposition.
	 *
	 * @param verificationDepartmentId the verification department ID of this proposition
	 */
	public void setVerificationDepartmentId(long verificationDepartmentId);

	/**
	 * Returns the proposition name of this proposition.
	 *
	 * @return the proposition name of this proposition
	 */
	@AutoEscape
	public String getPropositionName();

	/**
	 * Sets the proposition name of this proposition.
	 *
	 * @param propositionName the proposition name of this proposition
	 */
	public void setPropositionName(String propositionName);

	/**
	 * Returns the proposition desc of this proposition.
	 *
	 * @return the proposition desc of this proposition
	 */
	@AutoEscape
	public String getPropositionDesc();

	/**
	 * Sets the proposition desc of this proposition.
	 *
	 * @param propositionDesc the proposition desc of this proposition
	 */
	public void setPropositionDesc(String propositionDesc);

	/**
	 * Returns the proposition content of this proposition.
	 *
	 * @return the proposition content of this proposition
	 */
	@AutoEscape
	public String getPropositionContent();

	/**
	 * Sets the proposition content of this proposition.
	 *
	 * @param propositionContent the proposition content of this proposition
	 */
	public void setPropositionContent(String propositionContent);

	/**
	 * Returns the document file ID of this proposition.
	 *
	 * @return the document file ID of this proposition
	 */
	public long getDocumentFileId();

	/**
	 * Sets the document file ID of this proposition.
	 *
	 * @param documentFileId the document file ID of this proposition
	 */
	public void setDocumentFileId(long documentFileId);

	/**
	 * Returns the create date of this proposition.
	 *
	 * @return the create date of this proposition
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this proposition.
	 *
	 * @param createDate the create date of this proposition
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this proposition.
	 *
	 * @return the modified date of this proposition
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this proposition.
	 *
	 * @param modifiedDate the modified date of this proposition
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the view count of this proposition.
	 *
	 * @return the view count of this proposition
	 */
	public int getViewCount();

	/**
	 * Sets the view count of this proposition.
	 *
	 * @param viewCount the view count of this proposition
	 */
	public void setViewCount(int viewCount);

	/**
	 * Returns the feedback count of this proposition.
	 *
	 * @return the feedback count of this proposition
	 */
	public int getFeedbackCount();

	/**
	 * Sets the feedback count of this proposition.
	 *
	 * @param feedbackCount the feedback count of this proposition
	 */
	public void setFeedbackCount(int feedbackCount);

	/**
	 * Returns the status of this proposition.
	 *
	 * @return the status of this proposition
	 */
	public int getStatus();

	/**
	 * Sets the status of this proposition.
	 *
	 * @param status the status of this proposition
	 */
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this proposition.
	 *
	 * @return the status by user ID of this proposition
	 */
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this proposition.
	 *
	 * @param statusByUserId the status by user ID of this proposition
	 */
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this proposition.
	 *
	 * @return the status by user uuid of this proposition
	 * @throws SystemException if a system exception occurred
	 */
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this proposition.
	 *
	 * @param statusByUserUuid the status by user uuid of this proposition
	 */
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status date of this proposition.
	 *
	 * @return the status date of this proposition
	 */
	public Date getStatusDate();

	/**
	 * Sets the status date of this proposition.
	 *
	 * @param statusDate the status date of this proposition
	 */
	public void setStatusDate(Date statusDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Proposition proposition);

	public int hashCode();

	public CacheModel<Proposition> toCacheModel();

	public Proposition toEscapedModel();

	public String toString();

	public String toXmlString();
}