/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.portal_egov.portlet.contacts.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ContactsDepartment service. Represents a row in the &quot;ContactsDepartment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.portal_egov.portlet.contacts.model.impl.ContactsDepartmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.portal_egov.portlet.contacts.model.impl.ContactsDepartmentImpl}.
 * </p>
 *
 * @author HungDX
 * @see ContactsDepartment
 * @see com.portal_egov.portlet.contacts.model.impl.ContactsDepartmentImpl
 * @see com.portal_egov.portlet.contacts.model.impl.ContactsDepartmentModelImpl
 * @generated
 */
public interface ContactsDepartmentModel extends BaseModel<ContactsDepartment>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a contacts department model instance should use the {@link ContactsDepartment} interface instead.
	 */

	/**
	 * Returns the primary key of this contacts department.
	 *
	 * @return the primary key of this contacts department
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this contacts department.
	 *
	 * @param primaryKey the primary key of this contacts department
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the department ID of this contacts department.
	 *
	 * @return the department ID of this contacts department
	 */
	public long getDepartmentId();

	/**
	 * Sets the department ID of this contacts department.
	 *
	 * @param departmentId the department ID of this contacts department
	 */
	public void setDepartmentId(long departmentId);

	/**
	 * Returns the group ID of this contacts department.
	 *
	 * @return the group ID of this contacts department
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this contacts department.
	 *
	 * @param groupId the group ID of this contacts department
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this contacts department.
	 *
	 * @return the company ID of this contacts department
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this contacts department.
	 *
	 * @param companyId the company ID of this contacts department
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this contacts department.
	 *
	 * @return the user ID of this contacts department
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this contacts department.
	 *
	 * @param userId the user ID of this contacts department
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this contacts department.
	 *
	 * @return the user uuid of this contacts department
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this contacts department.
	 *
	 * @param userUuid the user uuid of this contacts department
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this contacts department.
	 *
	 * @return the user name of this contacts department
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this contacts department.
	 *
	 * @param userName the user name of this contacts department
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this contacts department.
	 *
	 * @return the create date of this contacts department
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this contacts department.
	 *
	 * @param createDate the create date of this contacts department
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this contacts department.
	 *
	 * @return the modified date of this contacts department
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this contacts department.
	 *
	 * @param modifiedDate the modified date of this contacts department
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the parent ID of this contacts department.
	 *
	 * @return the parent ID of this contacts department
	 */
	public long getParentId();

	/**
	 * Sets the parent ID of this contacts department.
	 *
	 * @param parentId the parent ID of this contacts department
	 */
	public void setParentId(long parentId);

	/**
	 * Returns the department name of this contacts department.
	 *
	 * @return the department name of this contacts department
	 */
	@AutoEscape
	public String getDepartmentName();

	/**
	 * Sets the department name of this contacts department.
	 *
	 * @param departmentName the department name of this contacts department
	 */
	public void setDepartmentName(String departmentName);

	/**
	 * Returns the department address of this contacts department.
	 *
	 * @return the department address of this contacts department
	 */
	@AutoEscape
	public String getDepartmentAddress();

	/**
	 * Sets the department address of this contacts department.
	 *
	 * @param departmentAddress the department address of this contacts department
	 */
	public void setDepartmentAddress(String departmentAddress);

	/**
	 * Returns the department phone of this contacts department.
	 *
	 * @return the department phone of this contacts department
	 */
	@AutoEscape
	public String getDepartmentPhone();

	/**
	 * Sets the department phone of this contacts department.
	 *
	 * @param departmentPhone the department phone of this contacts department
	 */
	public void setDepartmentPhone(String departmentPhone);

	/**
	 * Returns the department website of this contacts department.
	 *
	 * @return the department website of this contacts department
	 */
	@AutoEscape
	public String getDepartmentWebsite();

	/**
	 * Sets the department website of this contacts department.
	 *
	 * @param departmentWebsite the department website of this contacts department
	 */
	public void setDepartmentWebsite(String departmentWebsite);

	/**
	 * Returns the department email of this contacts department.
	 *
	 * @return the department email of this contacts department
	 */
	@AutoEscape
	public String getDepartmentEmail();

	/**
	 * Sets the department email of this contacts department.
	 *
	 * @param departmentEmail the department email of this contacts department
	 */
	public void setDepartmentEmail(String departmentEmail);

	/**
	 * Returns the display priority of this contacts department.
	 *
	 * @return the display priority of this contacts department
	 */
	public int getDisplayPriority();

	/**
	 * Sets the display priority of this contacts department.
	 *
	 * @param displayPriority the display priority of this contacts department
	 */
	public void setDisplayPriority(int displayPriority);

	/**
	 * Returns the department status of this contacts department.
	 *
	 * @return the department status of this contacts department
	 */
	public int getDepartmentStatus();

	/**
	 * Sets the department status of this contacts department.
	 *
	 * @param departmentStatus the department status of this contacts department
	 */
	public void setDepartmentStatus(int departmentStatus);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ContactsDepartment contactsDepartment);

	public int hashCode();

	public CacheModel<ContactsDepartment> toCacheModel();

	public ContactsDepartment toEscapedModel();

	public String toString();

	public String toXmlString();
}