/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bkav.portal.portlet.complaints.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Complaints service. Represents a row in the &quot;Complaints&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bkav.portal.portlet.complaints.model.impl.ComplaintsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bkav.portal.portlet.complaints.model.impl.ComplaintsImpl}.
 * </p>
 *
 * @author AnhBDb
 * @see Complaints
 * @see com.bkav.portal.portlet.complaints.model.impl.ComplaintsImpl
 * @see com.bkav.portal.portlet.complaints.model.impl.ComplaintsModelImpl
 * @generated
 */
public interface ComplaintsModel extends BaseModel<Complaints> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a complaints model instance should use the {@link Complaints} interface instead.
	 */

	/**
	 * Returns the primary key of this complaints.
	 *
	 * @return the primary key of this complaints
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this complaints.
	 *
	 * @param primaryKey the primary key of this complaints
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the complaint ID of this complaints.
	 *
	 * @return the complaint ID of this complaints
	 */
	public long getComplaintId();

	/**
	 * Sets the complaint ID of this complaints.
	 *
	 * @param complaintId the complaint ID of this complaints
	 */
	public void setComplaintId(long complaintId);

	/**
	 * Returns the complaint number of this complaints.
	 *
	 * @return the complaint number of this complaints
	 */
	@AutoEscape
	public String getComplaintNumber();

	/**
	 * Sets the complaint number of this complaints.
	 *
	 * @param complaintNumber the complaint number of this complaints
	 */
	public void setComplaintNumber(String complaintNumber);

	/**
	 * Returns the signing date of this complaints.
	 *
	 * @return the signing date of this complaints
	 */
	public Date getSigningDate();

	/**
	 * Sets the signing date of this complaints.
	 *
	 * @param signingDate the signing date of this complaints
	 */
	public void setSigningDate(Date signingDate);

	/**
	 * Returns the complaint name of this complaints.
	 *
	 * @return the complaint name of this complaints
	 */
	@AutoEscape
	public String getComplaintName();

	/**
	 * Sets the complaint name of this complaints.
	 *
	 * @param complaintName the complaint name of this complaints
	 */
	public void setComplaintName(String complaintName);

	/**
	 * Returns the complaint desc of this complaints.
	 *
	 * @return the complaint desc of this complaints
	 */
	@AutoEscape
	public String getComplaintDesc();

	/**
	 * Sets the complaint desc of this complaints.
	 *
	 * @param complaintDesc the complaint desc of this complaints
	 */
	public void setComplaintDesc(String complaintDesc);

	/**
	 * Returns the complaint content of this complaints.
	 *
	 * @return the complaint content of this complaints
	 */
	@AutoEscape
	public String getComplaintContent();

	/**
	 * Sets the complaint content of this complaints.
	 *
	 * @param complaintContent the complaint content of this complaints
	 */
	public void setComplaintContent(String complaintContent);

	/**
	 * Returns the reply document of this complaints.
	 *
	 * @return the reply document of this complaints
	 */
	@AutoEscape
	public String getReplyDocument();

	/**
	 * Sets the reply document of this complaints.
	 *
	 * @param replyDocument the reply document of this complaints
	 */
	public void setReplyDocument(String replyDocument);

	/**
	 * Returns the group ID of this complaints.
	 *
	 * @return the group ID of this complaints
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this complaints.
	 *
	 * @param groupId the group ID of this complaints
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this complaints.
	 *
	 * @return the company ID of this complaints
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this complaints.
	 *
	 * @param companyId the company ID of this complaints
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this complaints.
	 *
	 * @return the user ID of this complaints
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this complaints.
	 *
	 * @param userId the user ID of this complaints
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this complaints.
	 *
	 * @return the user uuid of this complaints
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this complaints.
	 *
	 * @param userUuid the user uuid of this complaints
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this complaints.
	 *
	 * @return the create date of this complaints
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this complaints.
	 *
	 * @param createDate the create date of this complaints
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this complaints.
	 *
	 * @return the modified date of this complaints
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this complaints.
	 *
	 * @param modifiedDate the modified date of this complaints
	 */
	public void setModifiedDate(Date modifiedDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Complaints complaints);

	public int hashCode();

	public CacheModel<Complaints> toCacheModel();

	public Complaints toEscapedModel();

	public String toString();

	public String toXmlString();
}