/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bkav.portal.portlet.complaints.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Complaints_DLFileEntries service. Represents a row in the &quot;Complaints_DLFileEntries&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bkav.portal.portlet.complaints.model.impl.Complaints_DLFileEntriesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bkav.portal.portlet.complaints.model.impl.Complaints_DLFileEntriesImpl}.
 * </p>
 *
 * @author AnhBDb
 * @see Complaints_DLFileEntries
 * @see com.bkav.portal.portlet.complaints.model.impl.Complaints_DLFileEntriesImpl
 * @see com.bkav.portal.portlet.complaints.model.impl.Complaints_DLFileEntriesModelImpl
 * @generated
 */
public interface Complaints_DLFileEntriesModel extends BaseModel<Complaints_DLFileEntries> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a complaints_ d l file entries model instance should use the {@link Complaints_DLFileEntries} interface instead.
	 */

	/**
	 * Returns the primary key of this complaints_ d l file entries.
	 *
	 * @return the primary key of this complaints_ d l file entries
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this complaints_ d l file entries.
	 *
	 * @param primaryKey the primary key of this complaints_ d l file entries
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this complaints_ d l file entries.
	 *
	 * @return the ID of this complaints_ d l file entries
	 */
	public long getId();

	/**
	 * Sets the ID of this complaints_ d l file entries.
	 *
	 * @param id the ID of this complaints_ d l file entries
	 */
	public void setId(long id);

	/**
	 * Returns the complaint ID of this complaints_ d l file entries.
	 *
	 * @return the complaint ID of this complaints_ d l file entries
	 */
	public long getComplaintId();

	/**
	 * Sets the complaint ID of this complaints_ d l file entries.
	 *
	 * @param complaintId the complaint ID of this complaints_ d l file entries
	 */
	public void setComplaintId(long complaintId);

	/**
	 * Returns the file entry ID of this complaints_ d l file entries.
	 *
	 * @return the file entry ID of this complaints_ d l file entries
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this complaints_ d l file entries.
	 *
	 * @param fileEntryId the file entry ID of this complaints_ d l file entries
	 */
	public void setFileEntryId(long fileEntryId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Complaints_DLFileEntries complaints_DLFileEntries);

	public int hashCode();

	public CacheModel<Complaints_DLFileEntries> toCacheModel();

	public Complaints_DLFileEntries toEscapedModel();

	public String toString();

	public String toXmlString();
}