/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bkav.portal.portlet.dynamic_menu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DynamicMenu service. Represents a row in the &quot;DynamicMenu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bkav.portal.portlet.dynamic_menu.model.impl.DynamicMenuModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bkav.portal.portlet.dynamic_menu.model.impl.DynamicMenuImpl}.
 * </p>
 *
 * @author hungdx
 * @see DynamicMenu
 * @see com.bkav.portal.portlet.dynamic_menu.model.impl.DynamicMenuImpl
 * @see com.bkav.portal.portlet.dynamic_menu.model.impl.DynamicMenuModelImpl
 * @generated
 */
public interface DynamicMenuModel extends BaseModel<DynamicMenu>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dynamic menu model instance should use the {@link DynamicMenu} interface instead.
	 */

	/**
	 * Returns the primary key of this dynamic menu.
	 *
	 * @return the primary key of this dynamic menu
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dynamic menu.
	 *
	 * @param primaryKey the primary key of this dynamic menu
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the menu ID of this dynamic menu.
	 *
	 * @return the menu ID of this dynamic menu
	 */
	public long getMenuId();

	/**
	 * Sets the menu ID of this dynamic menu.
	 *
	 * @param menuId the menu ID of this dynamic menu
	 */
	public void setMenuId(long menuId);

	/**
	 * Returns the group ID of this dynamic menu.
	 *
	 * @return the group ID of this dynamic menu
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this dynamic menu.
	 *
	 * @param groupId the group ID of this dynamic menu
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this dynamic menu.
	 *
	 * @return the company ID of this dynamic menu
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this dynamic menu.
	 *
	 * @param companyId the company ID of this dynamic menu
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this dynamic menu.
	 *
	 * @return the user ID of this dynamic menu
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this dynamic menu.
	 *
	 * @param userId the user ID of this dynamic menu
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dynamic menu.
	 *
	 * @return the user uuid of this dynamic menu
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this dynamic menu.
	 *
	 * @param userUuid the user uuid of this dynamic menu
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this dynamic menu.
	 *
	 * @return the user name of this dynamic menu
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this dynamic menu.
	 *
	 * @param userName the user name of this dynamic menu
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this dynamic menu.
	 *
	 * @return the create date of this dynamic menu
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this dynamic menu.
	 *
	 * @param createDate the create date of this dynamic menu
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this dynamic menu.
	 *
	 * @return the modified date of this dynamic menu
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dynamic menu.
	 *
	 * @param modifiedDate the modified date of this dynamic menu
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this dynamic menu.
	 *
	 * @return the name of this dynamic menu
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this dynamic menu.
	 *
	 * @param name the name of this dynamic menu
	 */
	public void setName(String name);

	/**
	 * Returns the description of this dynamic menu.
	 *
	 * @return the description of this dynamic menu
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this dynamic menu.
	 *
	 * @param description the description of this dynamic menu
	 */
	public void setDescription(String description);

	/**
	 * Returns the item count of this dynamic menu.
	 *
	 * @return the item count of this dynamic menu
	 */
	public int getItemCount();

	/**
	 * Sets the item count of this dynamic menu.
	 *
	 * @param itemCount the item count of this dynamic menu
	 */
	public void setItemCount(int itemCount);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(DynamicMenu dynamicMenu);

	public int hashCode();

	public CacheModel<DynamicMenu> toCacheModel();

	public DynamicMenu toEscapedModel();

	public String toString();

	public String toXmlString();
}