/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.portal_egov.portlet.citizen_inquiry.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CitizenInquiry service. Represents a row in the &quot;CitizenInquiry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.portal_egov.portlet.citizen_inquiry.model.impl.CitizenInquiryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.portal_egov.portlet.citizen_inquiry.model.impl.CitizenInquiryImpl}.
 * </p>
 *
 * @author HungDX
 * @see CitizenInquiry
 * @see com.portal_egov.portlet.citizen_inquiry.model.impl.CitizenInquiryImpl
 * @see com.portal_egov.portlet.citizen_inquiry.model.impl.CitizenInquiryModelImpl
 * @generated
 */
public interface CitizenInquiryModel extends BaseModel<CitizenInquiry>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a citizen inquiry model instance should use the {@link CitizenInquiry} interface instead.
	 */

	/**
	 * Returns the primary key of this citizen inquiry.
	 *
	 * @return the primary key of this citizen inquiry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this citizen inquiry.
	 *
	 * @param primaryKey the primary key of this citizen inquiry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the inquiry ID of this citizen inquiry.
	 *
	 * @return the inquiry ID of this citizen inquiry
	 */
	public long getInquiryId();

	/**
	 * Sets the inquiry ID of this citizen inquiry.
	 *
	 * @param inquiryId the inquiry ID of this citizen inquiry
	 */
	public void setInquiryId(long inquiryId);

	/**
	 * Returns the group ID of this citizen inquiry.
	 *
	 * @return the group ID of this citizen inquiry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this citizen inquiry.
	 *
	 * @param groupId the group ID of this citizen inquiry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this citizen inquiry.
	 *
	 * @return the company ID of this citizen inquiry
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this citizen inquiry.
	 *
	 * @param companyId the company ID of this citizen inquiry
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this citizen inquiry.
	 *
	 * @return the user ID of this citizen inquiry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this citizen inquiry.
	 *
	 * @param userId the user ID of this citizen inquiry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this citizen inquiry.
	 *
	 * @return the user uuid of this citizen inquiry
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this citizen inquiry.
	 *
	 * @param userUuid the user uuid of this citizen inquiry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this citizen inquiry.
	 *
	 * @return the user name of this citizen inquiry
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this citizen inquiry.
	 *
	 * @param userName the user name of this citizen inquiry
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this citizen inquiry.
	 *
	 * @return the create date of this citizen inquiry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this citizen inquiry.
	 *
	 * @param createDate the create date of this citizen inquiry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this citizen inquiry.
	 *
	 * @return the modified date of this citizen inquiry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this citizen inquiry.
	 *
	 * @param modifiedDate the modified date of this citizen inquiry
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the category ID of this citizen inquiry.
	 *
	 * @return the category ID of this citizen inquiry
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this citizen inquiry.
	 *
	 * @param categoryId the category ID of this citizen inquiry
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the citizen name of this citizen inquiry.
	 *
	 * @return the citizen name of this citizen inquiry
	 */
	@AutoEscape
	public String getCitizenName();

	/**
	 * Sets the citizen name of this citizen inquiry.
	 *
	 * @param citizenName the citizen name of this citizen inquiry
	 */
	public void setCitizenName(String citizenName);

	/**
	 * Returns the citizen phone of this citizen inquiry.
	 *
	 * @return the citizen phone of this citizen inquiry
	 */
	@AutoEscape
	public String getCitizenPhone();

	/**
	 * Sets the citizen phone of this citizen inquiry.
	 *
	 * @param citizenPhone the citizen phone of this citizen inquiry
	 */
	public void setCitizenPhone(String citizenPhone);

	/**
	 * Returns the citizen email of this citizen inquiry.
	 *
	 * @return the citizen email of this citizen inquiry
	 */
	@AutoEscape
	public String getCitizenEmail();

	/**
	 * Sets the citizen email of this citizen inquiry.
	 *
	 * @param citizenEmail the citizen email of this citizen inquiry
	 */
	public void setCitizenEmail(String citizenEmail);

	/**
	 * Returns the citizen address of this citizen inquiry.
	 *
	 * @return the citizen address of this citizen inquiry
	 */
	@AutoEscape
	public String getCitizenAddress();

	/**
	 * Sets the citizen address of this citizen inquiry.
	 *
	 * @param citizenAddress the citizen address of this citizen inquiry
	 */
	public void setCitizenAddress(String citizenAddress);

	/**
	 * Returns the inquiry title of this citizen inquiry.
	 *
	 * @return the inquiry title of this citizen inquiry
	 */
	@AutoEscape
	public String getInquiryTitle();

	/**
	 * Sets the inquiry title of this citizen inquiry.
	 *
	 * @param inquiryTitle the inquiry title of this citizen inquiry
	 */
	public void setInquiryTitle(String inquiryTitle);

	/**
	 * Returns the inquiry content of this citizen inquiry.
	 *
	 * @return the inquiry content of this citizen inquiry
	 */
	@AutoEscape
	public String getInquiryContent();

	/**
	 * Sets the inquiry content of this citizen inquiry.
	 *
	 * @param inquiryContent the inquiry content of this citizen inquiry
	 */
	public void setInquiryContent(String inquiryContent);

	/**
	 * Returns the inquiry feedback of this citizen inquiry.
	 *
	 * @return the inquiry feedback of this citizen inquiry
	 */
	@AutoEscape
	public String getInquiryFeedback();

	/**
	 * Sets the inquiry feedback of this citizen inquiry.
	 *
	 * @param inquiryFeedback the inquiry feedback of this citizen inquiry
	 */
	public void setInquiryFeedback(String inquiryFeedback);

	/**
	 * Returns the inquiry feedback user of this citizen inquiry.
	 *
	 * @return the inquiry feedback user of this citizen inquiry
	 */
	@AutoEscape
	public String getInquiryFeedbackUser();

	/**
	 * Sets the inquiry feedback user of this citizen inquiry.
	 *
	 * @param inquiryFeedbackUser the inquiry feedback user of this citizen inquiry
	 */
	public void setInquiryFeedbackUser(String inquiryFeedbackUser);

	/**
	 * Returns the inquiry feedback date of this citizen inquiry.
	 *
	 * @return the inquiry feedback date of this citizen inquiry
	 */
	public Date getInquiryFeedbackDate();

	/**
	 * Sets the inquiry feedback date of this citizen inquiry.
	 *
	 * @param inquiryFeedbackDate the inquiry feedback date of this citizen inquiry
	 */
	public void setInquiryFeedbackDate(Date inquiryFeedbackDate);

	/**
	 * Returns the inquiry status of this citizen inquiry.
	 *
	 * @return the inquiry status of this citizen inquiry
	 */
	public int getInquiryStatus();

	/**
	 * Sets the inquiry status of this citizen inquiry.
	 *
	 * @param inquiryStatus the inquiry status of this citizen inquiry
	 */
	public void setInquiryStatus(int inquiryStatus);

	/**
	 * Returns the approved of this citizen inquiry.
	 *
	 * @return the approved of this citizen inquiry
	 */
	public boolean getApproved();

	/**
	 * Returns <code>true</code> if this citizen inquiry is approved.
	 *
	 * @return <code>true</code> if this citizen inquiry is approved; <code>false</code> otherwise
	 */
	public boolean isApproved();

	/**
	 * Sets whether this citizen inquiry is approved.
	 *
	 * @param approved the approved of this citizen inquiry
	 */
	public void setApproved(boolean approved);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(CitizenInquiry citizenInquiry);

	public int hashCode();

	public CacheModel<CitizenInquiry> toCacheModel();

	public CitizenInquiry toEscapedModel();

	public String toString();

	public String toXmlString();
}