/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.portal_egov.portlet.ykct.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the YKCT_Entry service. Represents a row in the &quot;YKCT_Entry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.portal_egov.portlet.ykct.model.impl.YKCT_EntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.portal_egov.portlet.ykct.model.impl.YKCT_EntryImpl}.
 * </p>
 *
 * @author DucDVd
 * @see YKCT_Entry
 * @see com.portal_egov.portlet.ykct.model.impl.YKCT_EntryImpl
 * @see com.portal_egov.portlet.ykct.model.impl.YKCT_EntryModelImpl
 * @generated
 */
public interface YKCT_EntryModel extends BaseModel<YKCT_Entry>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a y k c t_ entry model instance should use the {@link YKCT_Entry} interface instead.
	 */

	/**
	 * Returns the primary key of this y k c t_ entry.
	 *
	 * @return the primary key of this y k c t_ entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this y k c t_ entry.
	 *
	 * @param primaryKey the primary key of this y k c t_ entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the entry ID of this y k c t_ entry.
	 *
	 * @return the entry ID of this y k c t_ entry
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this y k c t_ entry.
	 *
	 * @param entryId the entry ID of this y k c t_ entry
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the group ID of this y k c t_ entry.
	 *
	 * @return the group ID of this y k c t_ entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this y k c t_ entry.
	 *
	 * @param groupId the group ID of this y k c t_ entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this y k c t_ entry.
	 *
	 * @return the company ID of this y k c t_ entry
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this y k c t_ entry.
	 *
	 * @param companyId the company ID of this y k c t_ entry
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this y k c t_ entry.
	 *
	 * @return the user ID of this y k c t_ entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this y k c t_ entry.
	 *
	 * @param userId the user ID of this y k c t_ entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this y k c t_ entry.
	 *
	 * @return the user uuid of this y k c t_ entry
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this y k c t_ entry.
	 *
	 * @param userUuid the user uuid of this y k c t_ entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this y k c t_ entry.
	 *
	 * @return the user name of this y k c t_ entry
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this y k c t_ entry.
	 *
	 * @param userName the user name of this y k c t_ entry
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this y k c t_ entry.
	 *
	 * @return the create date of this y k c t_ entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this y k c t_ entry.
	 *
	 * @param createDate the create date of this y k c t_ entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this y k c t_ entry.
	 *
	 * @return the modified date of this y k c t_ entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this y k c t_ entry.
	 *
	 * @param modifiedDate the modified date of this y k c t_ entry
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the entry name of this y k c t_ entry.
	 *
	 * @return the entry name of this y k c t_ entry
	 */
	@AutoEscape
	public String getEntryName();

	/**
	 * Sets the entry name of this y k c t_ entry.
	 *
	 * @param entryName the entry name of this y k c t_ entry
	 */
	public void setEntryName(String entryName);

	/**
	 * Returns the category ID of this y k c t_ entry.
	 *
	 * @return the category ID of this y k c t_ entry
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this y k c t_ entry.
	 *
	 * @param categoryId the category ID of this y k c t_ entry
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the file attachment u r l of this y k c t_ entry.
	 *
	 * @return the file attachment u r l of this y k c t_ entry
	 */
	@AutoEscape
	public String getFileAttachmentURL();

	/**
	 * Sets the file attachment u r l of this y k c t_ entry.
	 *
	 * @param fileAttachmentURL the file attachment u r l of this y k c t_ entry
	 */
	public void setFileAttachmentURL(String fileAttachmentURL);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(YKCT_Entry ykct_Entry);

	public int hashCode();

	public CacheModel<YKCT_Entry> toCacheModel();

	public YKCT_Entry toEscapedModel();

	public String toString();

	public String toXmlString();
}