/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bkav.portal.portlet.portalplugins.service.base;

import com.bkav.portal.portlet.portalplugins.model.PortalPlugins;
import com.bkav.portal.portlet.portalplugins.service.PortalPluginsLocalService;
import com.bkav.portal.portlet.portalplugins.service.PortalPluginsService;
import com.bkav.portal.portlet.portalplugins.service.ePortalsLocalService;
import com.bkav.portal.portlet.portalplugins.service.ePortalsService;
import com.bkav.portal.portlet.portalplugins.service.persistence.PortalPluginsFinder;
import com.bkav.portal.portlet.portalplugins.service.persistence.PortalPluginsPersistence;
import com.bkav.portal.portlet.portalplugins.service.persistence.ePortalsFinder;
import com.bkav.portal.portlet.portalplugins.service.persistence.ePortalsPersistence;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the portal plugins local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.bkav.portal.portlet.portalplugins.service.impl.PortalPluginsLocalServiceImpl}.
 * </p>
 *
 * @author AnhBDb
 * @see com.bkav.portal.portlet.portalplugins.service.impl.PortalPluginsLocalServiceImpl
 * @see com.bkav.portal.portlet.portalplugins.service.PortalPluginsLocalServiceUtil
 * @generated
 */
public abstract class PortalPluginsLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements PortalPluginsLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.bkav.portal.portlet.portalplugins.service.PortalPluginsLocalServiceUtil} to access the portal plugins local service.
	 */

	/**
	 * Adds the portal plugins to the database. Also notifies the appropriate model listeners.
	 *
	 * @param portalPlugins the portal plugins
	 * @return the portal plugins that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public PortalPlugins addPortalPlugins(PortalPlugins portalPlugins)
		throws SystemException {
		portalPlugins.setNew(true);

		return portalPluginsPersistence.update(portalPlugins, false);
	}

	/**
	 * Creates a new portal plugins with the primary key. Does not add the portal plugins to the database.
	 *
	 * @param pluginId the primary key for the new portal plugins
	 * @return the new portal plugins
	 */
	public PortalPlugins createPortalPlugins(long pluginId) {
		return portalPluginsPersistence.create(pluginId);
	}

	/**
	 * Deletes the portal plugins with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param pluginId the primary key of the portal plugins
	 * @return the portal plugins that was removed
	 * @throws PortalException if a portal plugins with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public PortalPlugins deletePortalPlugins(long pluginId)
		throws PortalException, SystemException {
		return portalPluginsPersistence.remove(pluginId);
	}

	/**
	 * Deletes the portal plugins from the database. Also notifies the appropriate model listeners.
	 *
	 * @param portalPlugins the portal plugins
	 * @return the portal plugins that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public PortalPlugins deletePortalPlugins(PortalPlugins portalPlugins)
		throws SystemException {
		return portalPluginsPersistence.remove(portalPlugins);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(PortalPlugins.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return portalPluginsPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return portalPluginsPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return portalPluginsPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return portalPluginsPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public PortalPlugins fetchPortalPlugins(long pluginId)
		throws SystemException {
		return portalPluginsPersistence.fetchByPrimaryKey(pluginId);
	}

	/**
	 * Returns the portal plugins with the primary key.
	 *
	 * @param pluginId the primary key of the portal plugins
	 * @return the portal plugins
	 * @throws PortalException if a portal plugins with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public PortalPlugins getPortalPlugins(long pluginId)
		throws PortalException, SystemException {
		return portalPluginsPersistence.findByPrimaryKey(pluginId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return portalPluginsPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the portal pluginses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of portal pluginses
	 * @param end the upper bound of the range of portal pluginses (not inclusive)
	 * @return the range of portal pluginses
	 * @throws SystemException if a system exception occurred
	 */
	public List<PortalPlugins> getPortalPluginses(int start, int end)
		throws SystemException {
		return portalPluginsPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of portal pluginses.
	 *
	 * @return the number of portal pluginses
	 * @throws SystemException if a system exception occurred
	 */
	public int getPortalPluginsesCount() throws SystemException {
		return portalPluginsPersistence.countAll();
	}

	/**
	 * Updates the portal plugins in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param portalPlugins the portal plugins
	 * @return the portal plugins that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public PortalPlugins updatePortalPlugins(PortalPlugins portalPlugins)
		throws SystemException {
		return updatePortalPlugins(portalPlugins, true);
	}

	/**
	 * Updates the portal plugins in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param portalPlugins the portal plugins
	 * @param merge whether to merge the portal plugins with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the portal plugins that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public PortalPlugins updatePortalPlugins(PortalPlugins portalPlugins,
		boolean merge) throws SystemException {
		portalPlugins.setNew(false);

		return portalPluginsPersistence.update(portalPlugins, merge);
	}

	/**
	 * Returns the e portals local service.
	 *
	 * @return the e portals local service
	 */
	public ePortalsLocalService getePortalsLocalService() {
		return ePortalsLocalService;
	}

	/**
	 * Sets the e portals local service.
	 *
	 * @param ePortalsLocalService the e portals local service
	 */
	public void setePortalsLocalService(
		ePortalsLocalService ePortalsLocalService) {
		this.ePortalsLocalService = ePortalsLocalService;
	}

	/**
	 * Returns the e portals remote service.
	 *
	 * @return the e portals remote service
	 */
	public ePortalsService getePortalsService() {
		return ePortalsService;
	}

	/**
	 * Sets the e portals remote service.
	 *
	 * @param ePortalsService the e portals remote service
	 */
	public void setePortalsService(ePortalsService ePortalsService) {
		this.ePortalsService = ePortalsService;
	}

	/**
	 * Returns the e portals persistence.
	 *
	 * @return the e portals persistence
	 */
	public ePortalsPersistence getePortalsPersistence() {
		return ePortalsPersistence;
	}

	/**
	 * Sets the e portals persistence.
	 *
	 * @param ePortalsPersistence the e portals persistence
	 */
	public void setePortalsPersistence(ePortalsPersistence ePortalsPersistence) {
		this.ePortalsPersistence = ePortalsPersistence;
	}

	/**
	 * Returns the e portals finder.
	 *
	 * @return the e portals finder
	 */
	public ePortalsFinder getePortalsFinder() {
		return ePortalsFinder;
	}

	/**
	 * Sets the e portals finder.
	 *
	 * @param ePortalsFinder the e portals finder
	 */
	public void setePortalsFinder(ePortalsFinder ePortalsFinder) {
		this.ePortalsFinder = ePortalsFinder;
	}

	/**
	 * Returns the portal plugins local service.
	 *
	 * @return the portal plugins local service
	 */
	public PortalPluginsLocalService getPortalPluginsLocalService() {
		return portalPluginsLocalService;
	}

	/**
	 * Sets the portal plugins local service.
	 *
	 * @param portalPluginsLocalService the portal plugins local service
	 */
	public void setPortalPluginsLocalService(
		PortalPluginsLocalService portalPluginsLocalService) {
		this.portalPluginsLocalService = portalPluginsLocalService;
	}

	/**
	 * Returns the portal plugins remote service.
	 *
	 * @return the portal plugins remote service
	 */
	public PortalPluginsService getPortalPluginsService() {
		return portalPluginsService;
	}

	/**
	 * Sets the portal plugins remote service.
	 *
	 * @param portalPluginsService the portal plugins remote service
	 */
	public void setPortalPluginsService(
		PortalPluginsService portalPluginsService) {
		this.portalPluginsService = portalPluginsService;
	}

	/**
	 * Returns the portal plugins persistence.
	 *
	 * @return the portal plugins persistence
	 */
	public PortalPluginsPersistence getPortalPluginsPersistence() {
		return portalPluginsPersistence;
	}

	/**
	 * Sets the portal plugins persistence.
	 *
	 * @param portalPluginsPersistence the portal plugins persistence
	 */
	public void setPortalPluginsPersistence(
		PortalPluginsPersistence portalPluginsPersistence) {
		this.portalPluginsPersistence = portalPluginsPersistence;
	}

	/**
	 * Returns the portal plugins finder.
	 *
	 * @return the portal plugins finder
	 */
	public PortalPluginsFinder getPortalPluginsFinder() {
		return portalPluginsFinder;
	}

	/**
	 * Sets the portal plugins finder.
	 *
	 * @param portalPluginsFinder the portal plugins finder
	 */
	public void setPortalPluginsFinder(PortalPluginsFinder portalPluginsFinder) {
		this.portalPluginsFinder = portalPluginsFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.bkav.portal.portlet.portalplugins.model.PortalPlugins",
			portalPluginsLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.bkav.portal.portlet.portalplugins.model.PortalPlugins");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return PortalPlugins.class;
	}

	protected String getModelClassName() {
		return PortalPlugins.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = portalPluginsPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = ePortalsLocalService.class)
	protected ePortalsLocalService ePortalsLocalService;
	@BeanReference(type = ePortalsService.class)
	protected ePortalsService ePortalsService;
	@BeanReference(type = ePortalsPersistence.class)
	protected ePortalsPersistence ePortalsPersistence;
	@BeanReference(type = ePortalsFinder.class)
	protected ePortalsFinder ePortalsFinder;
	@BeanReference(type = PortalPluginsLocalService.class)
	protected PortalPluginsLocalService portalPluginsLocalService;
	@BeanReference(type = PortalPluginsService.class)
	protected PortalPluginsService portalPluginsService;
	@BeanReference(type = PortalPluginsPersistence.class)
	protected PortalPluginsPersistence portalPluginsPersistence;
	@BeanReference(type = PortalPluginsFinder.class)
	protected PortalPluginsFinder portalPluginsFinder;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private PortalPluginsLocalServiceClpInvoker _clpInvoker = new PortalPluginsLocalServiceClpInvoker();
}