/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.portal_egov.portlet.citymaps.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CityMapType service. Represents a row in the &quot;CityMapType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.portal_egov.portlet.citymaps.model.impl.CityMapTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.portal_egov.portlet.citymaps.model.impl.CityMapTypeImpl}.
 * </p>
 *
 * @author HungDX
 * @see CityMapType
 * @see com.portal_egov.portlet.citymaps.model.impl.CityMapTypeImpl
 * @see com.portal_egov.portlet.citymaps.model.impl.CityMapTypeModelImpl
 * @generated
 */
public interface CityMapTypeModel extends BaseModel<CityMapType>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a city map type model instance should use the {@link CityMapType} interface instead.
	 */

	/**
	 * Returns the primary key of this city map type.
	 *
	 * @return the primary key of this city map type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this city map type.
	 *
	 * @param primaryKey the primary key of this city map type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the type ID of this city map type.
	 *
	 * @return the type ID of this city map type
	 */
	public long getTypeId();

	/**
	 * Sets the type ID of this city map type.
	 *
	 * @param typeId the type ID of this city map type
	 */
	public void setTypeId(long typeId);

	/**
	 * Returns the company ID of this city map type.
	 *
	 * @return the company ID of this city map type
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this city map type.
	 *
	 * @param companyId the company ID of this city map type
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this city map type.
	 *
	 * @return the group ID of this city map type
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this city map type.
	 *
	 * @param groupId the group ID of this city map type
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this city map type.
	 *
	 * @return the user ID of this city map type
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this city map type.
	 *
	 * @param userId the user ID of this city map type
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this city map type.
	 *
	 * @return the user uuid of this city map type
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this city map type.
	 *
	 * @param userUuid the user uuid of this city map type
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this city map type.
	 *
	 * @return the user name of this city map type
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this city map type.
	 *
	 * @param userName the user name of this city map type
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this city map type.
	 *
	 * @return the create date of this city map type
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this city map type.
	 *
	 * @param createDate the create date of this city map type
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this city map type.
	 *
	 * @return the modified date of this city map type
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this city map type.
	 *
	 * @param modifiedDate the modified date of this city map type
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the type name of this city map type.
	 *
	 * @return the type name of this city map type
	 */
	@AutoEscape
	public String getTypeName();

	/**
	 * Sets the type name of this city map type.
	 *
	 * @param typeName the type name of this city map type
	 */
	public void setTypeName(String typeName);

	/**
	 * Returns the type desc of this city map type.
	 *
	 * @return the type desc of this city map type
	 */
	@AutoEscape
	public String getTypeDesc();

	/**
	 * Sets the type desc of this city map type.
	 *
	 * @param typeDesc the type desc of this city map type
	 */
	public void setTypeDesc(String typeDesc);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(CityMapType cityMapType);

	public int hashCode();

	public CacheModel<CityMapType> toCacheModel();

	public CityMapType toEscapedModel();

	public String toString();

	public String toXmlString();
}