/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.portal_egov.portlet.citymaps.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CityMap service. Represents a row in the &quot;CityMap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.portal_egov.portlet.citymaps.model.impl.CityMapModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.portal_egov.portlet.citymaps.model.impl.CityMapImpl}.
 * </p>
 *
 * @author HungDX
 * @see CityMap
 * @see com.portal_egov.portlet.citymaps.model.impl.CityMapImpl
 * @see com.portal_egov.portlet.citymaps.model.impl.CityMapModelImpl
 * @generated
 */
public interface CityMapModel extends BaseModel<CityMap>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a city map model instance should use the {@link CityMap} interface instead.
	 */

	/**
	 * Returns the primary key of this city map.
	 *
	 * @return the primary key of this city map
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this city map.
	 *
	 * @param primaryKey the primary key of this city map
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the map ID of this city map.
	 *
	 * @return the map ID of this city map
	 */
	public long getMapId();

	/**
	 * Sets the map ID of this city map.
	 *
	 * @param mapId the map ID of this city map
	 */
	public void setMapId(long mapId);

	/**
	 * Returns the company ID of this city map.
	 *
	 * @return the company ID of this city map
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this city map.
	 *
	 * @param companyId the company ID of this city map
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this city map.
	 *
	 * @return the group ID of this city map
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this city map.
	 *
	 * @param groupId the group ID of this city map
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this city map.
	 *
	 * @return the user ID of this city map
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this city map.
	 *
	 * @param userId the user ID of this city map
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this city map.
	 *
	 * @return the user uuid of this city map
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this city map.
	 *
	 * @param userUuid the user uuid of this city map
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this city map.
	 *
	 * @return the user name of this city map
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this city map.
	 *
	 * @param userName the user name of this city map
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this city map.
	 *
	 * @return the create date of this city map
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this city map.
	 *
	 * @param createDate the create date of this city map
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this city map.
	 *
	 * @return the modified date of this city map
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this city map.
	 *
	 * @param modifiedDate the modified date of this city map
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the map type ID of this city map.
	 *
	 * @return the map type ID of this city map
	 */
	public long getMapTypeId();

	/**
	 * Sets the map type ID of this city map.
	 *
	 * @param mapTypeId the map type ID of this city map
	 */
	public void setMapTypeId(long mapTypeId);

	/**
	 * Returns the map image ID of this city map.
	 *
	 * @return the map image ID of this city map
	 */
	public long getMapImageId();

	/**
	 * Sets the map image ID of this city map.
	 *
	 * @param mapImageId the map image ID of this city map
	 */
	public void setMapImageId(long mapImageId);

	/**
	 * Returns the map name of this city map.
	 *
	 * @return the map name of this city map
	 */
	@AutoEscape
	public String getMapName();

	/**
	 * Sets the map name of this city map.
	 *
	 * @param mapName the map name of this city map
	 */
	public void setMapName(String mapName);

	/**
	 * Returns the map desc of this city map.
	 *
	 * @return the map desc of this city map
	 */
	@AutoEscape
	public String getMapDesc();

	/**
	 * Sets the map desc of this city map.
	 *
	 * @param mapDesc the map desc of this city map
	 */
	public void setMapDesc(String mapDesc);

	/**
	 * Returns the map sumary of this city map.
	 *
	 * @return the map sumary of this city map
	 */
	@AutoEscape
	public String getMapSumary();

	/**
	 * Sets the map sumary of this city map.
	 *
	 * @param mapSumary the map sumary of this city map
	 */
	public void setMapSumary(String mapSumary);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(CityMap cityMap);

	public int hashCode();

	public CacheModel<CityMap> toCacheModel();

	public CityMap toEscapedModel();

	public String toString();

	public String toXmlString();
}