/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bkav.portal_egov.portlet.asset_statistics.model.impl;

import com.bkav.portal_egov.portlet.asset_statistics.model.StatisticEntity;
import com.bkav.portal_egov.portlet.asset_statistics.model.StatisticEntityModel;
import com.bkav.portal_egov.portlet.asset_statistics.model.StatisticEntitySoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the StatisticEntity service. Represents a row in the &quot;StatisticEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.bkav.portal_egov.portlet.asset_statistics.model.StatisticEntityModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StatisticEntityImpl}.
 * </p>
 *
 * @author HungDX
 * @see StatisticEntityImpl
 * @see com.bkav.portal_egov.portlet.asset_statistics.model.StatisticEntity
 * @see com.bkav.portal_egov.portlet.asset_statistics.model.StatisticEntityModel
 * @generated
 */
@JSON(strict = true)
public class StatisticEntityModelImpl extends BaseModelImpl<StatisticEntity>
	implements StatisticEntityModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a statistic entity model instance should use the {@link com.bkav.portal_egov.portlet.asset_statistics.model.StatisticEntity} interface instead.
	 */
	public static final String TABLE_NAME = "StatisticEntity";
	public static final Object[][] TABLE_COLUMNS = {
			{ "entityId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "entityName", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table StatisticEntity (entityId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,entityName VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table StatisticEntity";
	public static final String ORDER_BY_JPQL = " ORDER BY statisticEntity.entityName ASC";
	public static final String ORDER_BY_SQL = " ORDER BY StatisticEntity.entityName ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.bkav.portal_egov.portlet.asset_statistics.model.StatisticEntity"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.bkav.portal_egov.portlet.asset_statistics.model.StatisticEntity"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.bkav.portal_egov.portlet.asset_statistics.model.StatisticEntity"),
			true);
	public static long GROUPID_COLUMN_BITMASK = 1L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static StatisticEntity toModel(StatisticEntitySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		StatisticEntity model = new StatisticEntityImpl();

		model.setEntityId(soapModel.getEntityId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setEntityName(soapModel.getEntityName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<StatisticEntity> toModels(
		StatisticEntitySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<StatisticEntity> models = new ArrayList<StatisticEntity>(soapModels.length);

		for (StatisticEntitySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.bkav.portal_egov.portlet.asset_statistics.model.StatisticEntity"));

	public StatisticEntityModelImpl() {
	}

	public long getPrimaryKey() {
		return _entityId;
	}

	public void setPrimaryKey(long primaryKey) {
		setEntityId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_entityId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return StatisticEntity.class;
	}

	public String getModelClassName() {
		return StatisticEntity.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("entityId", getEntityId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("entityName", getEntityName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long entityId = (Long)attributes.get("entityId");

		if (entityId != null) {
			setEntityId(entityId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String entityName = (String)attributes.get("entityName");

		if (entityName != null) {
			setEntityName(entityName);
		}
	}

	@JSON
	public long getEntityId() {
		return _entityId;
	}

	public void setEntityId(long entityId) {
		_entityId = entityId;
	}

	@JSON
	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	public String getEntityName() {
		if (_entityName == null) {
			return StringPool.BLANK;
		}
		else {
			return _entityName;
		}
	}

	public void setEntityName(String entityName) {
		_columnBitmask = -1L;

		_entityName = entityName;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			StatisticEntity.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public StatisticEntity toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (StatisticEntity)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		StatisticEntityImpl statisticEntityImpl = new StatisticEntityImpl();

		statisticEntityImpl.setEntityId(getEntityId());
		statisticEntityImpl.setCompanyId(getCompanyId());
		statisticEntityImpl.setGroupId(getGroupId());
		statisticEntityImpl.setUserId(getUserId());
		statisticEntityImpl.setUserName(getUserName());
		statisticEntityImpl.setCreateDate(getCreateDate());
		statisticEntityImpl.setModifiedDate(getModifiedDate());
		statisticEntityImpl.setEntityName(getEntityName());

		statisticEntityImpl.resetOriginalValues();

		return statisticEntityImpl;
	}

	public int compareTo(StatisticEntity statisticEntity) {
		int value = 0;

		value = getEntityName().compareTo(statisticEntity.getEntityName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		StatisticEntity statisticEntity = null;

		try {
			statisticEntity = (StatisticEntity)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = statisticEntity.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		StatisticEntityModelImpl statisticEntityModelImpl = this;

		statisticEntityModelImpl._originalGroupId = statisticEntityModelImpl._groupId;

		statisticEntityModelImpl._setOriginalGroupId = false;

		statisticEntityModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<StatisticEntity> toCacheModel() {
		StatisticEntityCacheModel statisticEntityCacheModel = new StatisticEntityCacheModel();

		statisticEntityCacheModel.entityId = getEntityId();

		statisticEntityCacheModel.companyId = getCompanyId();

		statisticEntityCacheModel.groupId = getGroupId();

		statisticEntityCacheModel.userId = getUserId();

		statisticEntityCacheModel.userName = getUserName();

		String userName = statisticEntityCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			statisticEntityCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			statisticEntityCacheModel.createDate = createDate.getTime();
		}
		else {
			statisticEntityCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			statisticEntityCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			statisticEntityCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		statisticEntityCacheModel.entityName = getEntityName();

		String entityName = statisticEntityCacheModel.entityName;

		if ((entityName != null) && (entityName.length() == 0)) {
			statisticEntityCacheModel.entityName = null;
		}

		return statisticEntityCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{entityId=");
		sb.append(getEntityId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", entityName=");
		sb.append(getEntityName());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append(
			"com.bkav.portal_egov.portlet.asset_statistics.model.StatisticEntity");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>entityId</column-name><column-value><![CDATA[");
		sb.append(getEntityId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>entityName</column-name><column-value><![CDATA[");
		sb.append(getEntityName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = StatisticEntity.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			StatisticEntity.class
		};
	private long _entityId;
	private long _companyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _entityName;
	private long _columnBitmask;
	private StatisticEntity _escapedModelProxy;
}