/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.portal_egov.portlet.citymaps.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.portal_egov.portlet.citymaps.model.CityMapType;
import com.portal_egov.portlet.citymaps.model.CityMapTypeModel;
import com.portal_egov.portlet.citymaps.model.CityMapTypeSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CityMapType service. Represents a row in the &quot;CityMapType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.portal_egov.portlet.citymaps.model.CityMapTypeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CityMapTypeImpl}.
 * </p>
 *
 * @author HungDX
 * @see CityMapTypeImpl
 * @see com.portal_egov.portlet.citymaps.model.CityMapType
 * @see com.portal_egov.portlet.citymaps.model.CityMapTypeModel
 * @generated
 */
@JSON(strict = true)
public class CityMapTypeModelImpl extends BaseModelImpl<CityMapType>
	implements CityMapTypeModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a city map type model instance should use the {@link com.portal_egov.portlet.citymaps.model.CityMapType} interface instead.
	 */
	public static final String TABLE_NAME = "CityMapType";
	public static final Object[][] TABLE_COLUMNS = {
			{ "typeId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "typeName", Types.VARCHAR },
			{ "typeDesc", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table CityMapType (typeId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,typeName VARCHAR(300) null,typeDesc VARCHAR(1000) null)";
	public static final String TABLE_SQL_DROP = "drop table CityMapType";
	public static final String ORDER_BY_JPQL = " ORDER BY cityMapType.typeName ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CityMapType.typeName ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.portal_egov.portlet.citymaps.model.CityMapType"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.portal_egov.portlet.citymaps.model.CityMapType"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.portal_egov.portlet.citymaps.model.CityMapType"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CityMapType toModel(CityMapTypeSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CityMapType model = new CityMapTypeImpl();

		model.setTypeId(soapModel.getTypeId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTypeName(soapModel.getTypeName());
		model.setTypeDesc(soapModel.getTypeDesc());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CityMapType> toModels(CityMapTypeSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CityMapType> models = new ArrayList<CityMapType>(soapModels.length);

		for (CityMapTypeSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.portal_egov.portlet.citymaps.model.CityMapType"));

	public CityMapTypeModelImpl() {
	}

	public long getPrimaryKey() {
		return _typeId;
	}

	public void setPrimaryKey(long primaryKey) {
		setTypeId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_typeId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return CityMapType.class;
	}

	public String getModelClassName() {
		return CityMapType.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("typeId", getTypeId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("typeName", getTypeName());
		attributes.put("typeDesc", getTypeDesc());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long typeId = (Long)attributes.get("typeId");

		if (typeId != null) {
			setTypeId(typeId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String typeName = (String)attributes.get("typeName");

		if (typeName != null) {
			setTypeName(typeName);
		}

		String typeDesc = (String)attributes.get("typeDesc");

		if (typeDesc != null) {
			setTypeDesc(typeDesc);
		}
	}

	@JSON
	public long getTypeId() {
		return _typeId;
	}

	public void setTypeId(long typeId) {
		_typeId = typeId;
	}

	@JSON
	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	public String getTypeName() {
		if (_typeName == null) {
			return StringPool.BLANK;
		}
		else {
			return _typeName;
		}
	}

	public void setTypeName(String typeName) {
		_columnBitmask = -1L;

		_typeName = typeName;
	}

	@JSON
	public String getTypeDesc() {
		if (_typeDesc == null) {
			return StringPool.BLANK;
		}
		else {
			return _typeDesc;
		}
	}

	public void setTypeDesc(String typeDesc) {
		_typeDesc = typeDesc;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			CityMapType.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CityMapType toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (CityMapType)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		CityMapTypeImpl cityMapTypeImpl = new CityMapTypeImpl();

		cityMapTypeImpl.setTypeId(getTypeId());
		cityMapTypeImpl.setCompanyId(getCompanyId());
		cityMapTypeImpl.setGroupId(getGroupId());
		cityMapTypeImpl.setUserId(getUserId());
		cityMapTypeImpl.setUserName(getUserName());
		cityMapTypeImpl.setCreateDate(getCreateDate());
		cityMapTypeImpl.setModifiedDate(getModifiedDate());
		cityMapTypeImpl.setTypeName(getTypeName());
		cityMapTypeImpl.setTypeDesc(getTypeDesc());

		cityMapTypeImpl.resetOriginalValues();

		return cityMapTypeImpl;
	}

	public int compareTo(CityMapType cityMapType) {
		int value = 0;

		value = getTypeName().compareTo(cityMapType.getTypeName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		CityMapType cityMapType = null;

		try {
			cityMapType = (CityMapType)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = cityMapType.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CityMapTypeModelImpl cityMapTypeModelImpl = this;

		cityMapTypeModelImpl._originalCompanyId = cityMapTypeModelImpl._companyId;

		cityMapTypeModelImpl._setOriginalCompanyId = false;

		cityMapTypeModelImpl._originalGroupId = cityMapTypeModelImpl._groupId;

		cityMapTypeModelImpl._setOriginalGroupId = false;

		cityMapTypeModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CityMapType> toCacheModel() {
		CityMapTypeCacheModel cityMapTypeCacheModel = new CityMapTypeCacheModel();

		cityMapTypeCacheModel.typeId = getTypeId();

		cityMapTypeCacheModel.companyId = getCompanyId();

		cityMapTypeCacheModel.groupId = getGroupId();

		cityMapTypeCacheModel.userId = getUserId();

		cityMapTypeCacheModel.userName = getUserName();

		String userName = cityMapTypeCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			cityMapTypeCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			cityMapTypeCacheModel.createDate = createDate.getTime();
		}
		else {
			cityMapTypeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			cityMapTypeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			cityMapTypeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		cityMapTypeCacheModel.typeName = getTypeName();

		String typeName = cityMapTypeCacheModel.typeName;

		if ((typeName != null) && (typeName.length() == 0)) {
			cityMapTypeCacheModel.typeName = null;
		}

		cityMapTypeCacheModel.typeDesc = getTypeDesc();

		String typeDesc = cityMapTypeCacheModel.typeDesc;

		if ((typeDesc != null) && (typeDesc.length() == 0)) {
			cityMapTypeCacheModel.typeDesc = null;
		}

		return cityMapTypeCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{typeId=");
		sb.append(getTypeId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", typeName=");
		sb.append(getTypeName());
		sb.append(", typeDesc=");
		sb.append(getTypeDesc());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.portal_egov.portlet.citymaps.model.CityMapType");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>typeId</column-name><column-value><![CDATA[");
		sb.append(getTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>typeName</column-name><column-value><![CDATA[");
		sb.append(getTypeName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>typeDesc</column-name><column-value><![CDATA[");
		sb.append(getTypeDesc());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CityMapType.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			CityMapType.class
		};
	private long _typeId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _typeName;
	private String _typeDesc;
	private long _columnBitmask;
	private CityMapType _escapedModelProxy;
}