/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bkav.portal.portlet.video.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VideoEntry service. Represents a row in the &quot;VideoEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bkav.portal.portlet.video.model.impl.VideoEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bkav.portal.portlet.video.model.impl.VideoEntryImpl}.
 * </p>
 *
 * @author hungdx
 * @see VideoEntry
 * @see com.bkav.portal.portlet.video.model.impl.VideoEntryImpl
 * @see com.bkav.portal.portlet.video.model.impl.VideoEntryModelImpl
 * @generated
 */
public interface VideoEntryModel extends BaseModel<VideoEntry>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a video entry model instance should use the {@link VideoEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this video entry.
	 *
	 * @return the primary key of this video entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this video entry.
	 *
	 * @param primaryKey the primary key of this video entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the entry ID of this video entry.
	 *
	 * @return the entry ID of this video entry
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this video entry.
	 *
	 * @param entryId the entry ID of this video entry
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the group ID of this video entry.
	 *
	 * @return the group ID of this video entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this video entry.
	 *
	 * @param groupId the group ID of this video entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this video entry.
	 *
	 * @return the company ID of this video entry
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this video entry.
	 *
	 * @param companyId the company ID of this video entry
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this video entry.
	 *
	 * @return the user ID of this video entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this video entry.
	 *
	 * @param userId the user ID of this video entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this video entry.
	 *
	 * @return the user uuid of this video entry
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this video entry.
	 *
	 * @param userUuid the user uuid of this video entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this video entry.
	 *
	 * @return the user name of this video entry
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this video entry.
	 *
	 * @param userName the user name of this video entry
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this video entry.
	 *
	 * @return the create date of this video entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this video entry.
	 *
	 * @param createDate the create date of this video entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this video entry.
	 *
	 * @return the modified date of this video entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this video entry.
	 *
	 * @param modifiedDate the modified date of this video entry
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this video entry.
	 *
	 * @return the name of this video entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this video entry.
	 *
	 * @param name the name of this video entry
	 */
	public void setName(String name);

	/**
	 * Returns the description of this video entry.
	 *
	 * @return the description of this video entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this video entry.
	 *
	 * @param description the description of this video entry
	 */
	public void setDescription(String description);

	/**
	 * Returns the video type of this video entry.
	 *
	 * @return the video type of this video entry
	 */
	@AutoEscape
	public String getVideoType();

	/**
	 * Sets the video type of this video entry.
	 *
	 * @param videoType the video type of this video entry
	 */
	public void setVideoType(String videoType);

	/**
	 * Returns the video url of this video entry.
	 *
	 * @return the video url of this video entry
	 */
	@AutoEscape
	public String getVideoUrl();

	/**
	 * Sets the video url of this video entry.
	 *
	 * @param videoUrl the video url of this video entry
	 */
	public void setVideoUrl(String videoUrl);

	/**
	 * Returns the video file ID of this video entry.
	 *
	 * @return the video file ID of this video entry
	 */
	public long getVideoFileId();

	/**
	 * Sets the video file ID of this video entry.
	 *
	 * @param videoFileId the video file ID of this video entry
	 */
	public void setVideoFileId(long videoFileId);

	/**
	 * Returns the thumbnail image of this video entry.
	 *
	 * @return the thumbnail image of this video entry
	 */
	public boolean getThumbnailImage();

	/**
	 * Returns <code>true</code> if this video entry is thumbnail image.
	 *
	 * @return <code>true</code> if this video entry is thumbnail image; <code>false</code> otherwise
	 */
	public boolean isThumbnailImage();

	/**
	 * Sets whether this video entry is thumbnail image.
	 *
	 * @param thumbnailImage the thumbnail image of this video entry
	 */
	public void setThumbnailImage(boolean thumbnailImage);

	/**
	 * Returns the thumbnail image ID of this video entry.
	 *
	 * @return the thumbnail image ID of this video entry
	 */
	public long getThumbnailImageId();

	/**
	 * Sets the thumbnail image ID of this video entry.
	 *
	 * @param thumbnailImageId the thumbnail image ID of this video entry
	 */
	public void setThumbnailImageId(long thumbnailImageId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VideoEntry videoEntry);

	public int hashCode();

	public CacheModel<VideoEntry> toCacheModel();

	public VideoEntry toEscapedModel();

	public String toString();

	public String toXmlString();
}