/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bkav.portal.portlet.contentsharing.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ContentSharing service. Represents a row in the &quot;ContentSharing&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bkav.portal.portlet.contentsharing.model.impl.ContentSharingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bkav.portal.portlet.contentsharing.model.impl.ContentSharingImpl}.
 * </p>
 *
 * @author anhbdb
 * @see ContentSharing
 * @see com.bkav.portal.portlet.contentsharing.model.impl.ContentSharingImpl
 * @see com.bkav.portal.portlet.contentsharing.model.impl.ContentSharingModelImpl
 * @generated
 */
public interface ContentSharingModel extends BaseModel<ContentSharing> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a content sharing model instance should use the {@link ContentSharing} interface instead.
	 */

	/**
	 * Returns the primary key of this content sharing.
	 *
	 * @return the primary key of this content sharing
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this content sharing.
	 *
	 * @param primaryKey the primary key of this content sharing
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the content ID of this content sharing.
	 *
	 * @return the content ID of this content sharing
	 */
	public long getContentId();

	/**
	 * Sets the content ID of this content sharing.
	 *
	 * @param contentId the content ID of this content sharing
	 */
	public void setContentId(long contentId);

	/**
	 * Returns the company ID of this content sharing.
	 *
	 * @return the company ID of this content sharing
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this content sharing.
	 *
	 * @param companyId the company ID of this content sharing
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this content sharing.
	 *
	 * @return the group ID of this content sharing
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this content sharing.
	 *
	 * @param groupId the group ID of this content sharing
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this content sharing.
	 *
	 * @return the user ID of this content sharing
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this content sharing.
	 *
	 * @param userId the user ID of this content sharing
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this content sharing.
	 *
	 * @return the user uuid of this content sharing
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this content sharing.
	 *
	 * @param userUuid the user uuid of this content sharing
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the content sharing of this content sharing.
	 *
	 * @return the content sharing of this content sharing
	 */
	@AutoEscape
	public String getContentSharing();

	/**
	 * Sets the content sharing of this content sharing.
	 *
	 * @param contentSharing the content sharing of this content sharing
	 */
	public void setContentSharing(String contentSharing);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ContentSharing contentSharing);

	public int hashCode();

	public CacheModel<ContentSharing> toCacheModel();

	public ContentSharing toEscapedModel();

	public String toString();

	public String toXmlString();
}