/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bkav.portal.portlet.employee.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Employee service. Represents a row in the &quot;Employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bkav.portal.portlet.employee.model.impl.EmployeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bkav.portal.portlet.employee.model.impl.EmployeeImpl}.
 * </p>
 *
 * @author ducdvd
 * @see Employee
 * @see com.bkav.portal.portlet.employee.model.impl.EmployeeImpl
 * @see com.bkav.portal.portlet.employee.model.impl.EmployeeModelImpl
 * @generated
 */
public interface EmployeeModel extends BaseModel<Employee>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee model instance should use the {@link Employee} interface instead.
	 */

	/**
	 * Returns the primary key of this employee.
	 *
	 * @return the primary key of this employee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee.
	 *
	 * @param primaryKey the primary key of this employee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the empl ID of this employee.
	 *
	 * @return the empl ID of this employee
	 */
	public long getEmplId();

	/**
	 * Sets the empl ID of this employee.
	 *
	 * @param emplId the empl ID of this employee
	 */
	public void setEmplId(long emplId);

	/**
	 * Returns the group ID of this employee.
	 *
	 * @return the group ID of this employee
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this employee.
	 *
	 * @param groupId the group ID of this employee
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee.
	 *
	 * @return the company ID of this employee
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee.
	 *
	 * @param companyId the company ID of this employee
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this employee.
	 *
	 * @return the user ID of this employee
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this employee.
	 *
	 * @param userId the user ID of this employee
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this employee.
	 *
	 * @return the user uuid of this employee
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this employee.
	 *
	 * @param userUuid the user uuid of this employee
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this employee.
	 *
	 * @return the user name of this employee
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this employee.
	 *
	 * @param userName the user name of this employee
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this employee.
	 *
	 * @return the create date of this employee
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee.
	 *
	 * @param createDate the create date of this employee
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee.
	 *
	 * @return the modified date of this employee
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee.
	 *
	 * @param modifiedDate the modified date of this employee
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this employee.
	 *
	 * @return the name of this employee
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this employee.
	 *
	 * @param name the name of this employee
	 */
	public void setName(String name);

	/**
	 * Returns the birthday of this employee.
	 *
	 * @return the birthday of this employee
	 */
	public Date getBirthday();

	/**
	 * Sets the birthday of this employee.
	 *
	 * @param birthday the birthday of this employee
	 */
	public void setBirthday(Date birthday);

	/**
	 * Returns the male of this employee.
	 *
	 * @return the male of this employee
	 */
	@AutoEscape
	public String getMale();

	/**
	 * Sets the male of this employee.
	 *
	 * @param male the male of this employee
	 */
	public void setMale(String male);

	/**
	 * Returns the phone of this employee.
	 *
	 * @return the phone of this employee
	 */
	public long getPhone();

	/**
	 * Sets the phone of this employee.
	 *
	 * @param phone the phone of this employee
	 */
	public void setPhone(long phone);

	/**
	 * Returns the addres of this employee.
	 *
	 * @return the addres of this employee
	 */
	@AutoEscape
	public String getAddres();

	/**
	 * Sets the addres of this employee.
	 *
	 * @param addres the addres of this employee
	 */
	public void setAddres(String addres);

	/**
	 * Returns the email of this employee.
	 *
	 * @return the email of this employee
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this employee.
	 *
	 * @param email the email of this employee
	 */
	public void setEmail(String email);

	/**
	 * Returns the post ID of this employee.
	 *
	 * @return the post ID of this employee
	 */
	public long getPostId();

	/**
	 * Sets the post ID of this employee.
	 *
	 * @param postId the post ID of this employee
	 */
	public void setPostId(long postId);

	/**
	 * Returns the dep ID of this employee.
	 *
	 * @return the dep ID of this employee
	 */
	public long getDepId();

	/**
	 * Sets the dep ID of this employee.
	 *
	 * @param depId the dep ID of this employee
	 */
	public void setDepId(long depId);

	/**
	 * Returns the sal of this employee.
	 *
	 * @return the sal of this employee
	 */
	public long getSal();

	/**
	 * Sets the sal of this employee.
	 *
	 * @param sal the sal of this employee
	 */
	public void setSal(long sal);

	/**
	 * Returns the break day of this employee.
	 *
	 * @return the break day of this employee
	 */
	public int getBreakDay();

	/**
	 * Sets the break day of this employee.
	 *
	 * @param breakDay the break day of this employee
	 */
	public void setBreakDay(int breakDay);

	/**
	 * Returns the add day of this employee.
	 *
	 * @return the add day of this employee
	 */
	public int getAddDay();

	/**
	 * Sets the add day of this employee.
	 *
	 * @param addDay the add day of this employee
	 */
	public void setAddDay(int addDay);

	/**
	 * Returns the end date of this employee.
	 *
	 * @return the end date of this employee
	 */
	@AutoEscape
	public String getEndDate();

	/**
	 * Sets the end date of this employee.
	 *
	 * @param endDate the end date of this employee
	 */
	public void setEndDate(String endDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Employee employee);

	public int hashCode();

	public CacheModel<Employee> toCacheModel();

	public Employee toEscapedModel();

	public String toString();

	public String toXmlString();
}