/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.portal_egov.portlet.contacts.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.portal_egov.portlet.contacts.model.ContactsProperty;
import com.portal_egov.portlet.contacts.model.ContactsPropertyModel;
import com.portal_egov.portlet.contacts.model.ContactsPropertySoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ContactsProperty service. Represents a row in the &quot;ContactsProperty&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.portal_egov.portlet.contacts.model.ContactsPropertyModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContactsPropertyImpl}.
 * </p>
 *
 * @author HungDX
 * @see ContactsPropertyImpl
 * @see com.portal_egov.portlet.contacts.model.ContactsProperty
 * @see com.portal_egov.portlet.contacts.model.ContactsPropertyModel
 * @generated
 */
@JSON(strict = true)
public class ContactsPropertyModelImpl extends BaseModelImpl<ContactsProperty>
	implements ContactsPropertyModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a contacts property model instance should use the {@link com.portal_egov.portlet.contacts.model.ContactsProperty} interface instead.
	 */
	public static final String TABLE_NAME = "ContactsProperty";
	public static final Object[][] TABLE_COLUMNS = {
			{ "propertyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "contactId", Types.BIGINT },
			{ "propertyKey", Types.VARCHAR },
			{ "propertyValue", Types.VARCHAR },
			{ "propertyType", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table ContactsProperty (propertyId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,contactId LONG,propertyKey VARCHAR(150) null,propertyValue VARCHAR(1000) null,propertyType VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table ContactsProperty";
	public static final String ORDER_BY_JPQL = " ORDER BY contactsProperty.contactId ASC, contactsProperty.propertyKey ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ContactsProperty.contactId ASC, ContactsProperty.propertyKey ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.portal_egov.portlet.contacts.model.ContactsProperty"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.portal_egov.portlet.contacts.model.ContactsProperty"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.portal_egov.portlet.contacts.model.ContactsProperty"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long CONTACTID_COLUMN_BITMASK = 2L;
	public static long GROUPID_COLUMN_BITMASK = 4L;
	public static long PROPERTYKEY_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ContactsProperty toModel(ContactsPropertySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ContactsProperty model = new ContactsPropertyImpl();

		model.setPropertyId(soapModel.getPropertyId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setContactId(soapModel.getContactId());
		model.setPropertyKey(soapModel.getPropertyKey());
		model.setPropertyValue(soapModel.getPropertyValue());
		model.setPropertyType(soapModel.getPropertyType());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ContactsProperty> toModels(
		ContactsPropertySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ContactsProperty> models = new ArrayList<ContactsProperty>(soapModels.length);

		for (ContactsPropertySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.portal_egov.portlet.contacts.model.ContactsProperty"));

	public ContactsPropertyModelImpl() {
	}

	public long getPrimaryKey() {
		return _propertyId;
	}

	public void setPrimaryKey(long primaryKey) {
		setPropertyId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_propertyId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return ContactsProperty.class;
	}

	public String getModelClassName() {
		return ContactsProperty.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("propertyId", getPropertyId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("contactId", getContactId());
		attributes.put("propertyKey", getPropertyKey());
		attributes.put("propertyValue", getPropertyValue());
		attributes.put("propertyType", getPropertyType());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long propertyId = (Long)attributes.get("propertyId");

		if (propertyId != null) {
			setPropertyId(propertyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long contactId = (Long)attributes.get("contactId");

		if (contactId != null) {
			setContactId(contactId);
		}

		String propertyKey = (String)attributes.get("propertyKey");

		if (propertyKey != null) {
			setPropertyKey(propertyKey);
		}

		String propertyValue = (String)attributes.get("propertyValue");

		if (propertyValue != null) {
			setPropertyValue(propertyValue);
		}

		String propertyType = (String)attributes.get("propertyType");

		if (propertyType != null) {
			setPropertyType(propertyType);
		}
	}

	@JSON
	public long getPropertyId() {
		return _propertyId;
	}

	public void setPropertyId(long propertyId) {
		_propertyId = propertyId;
	}

	@JSON
	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	public long getContactId() {
		return _contactId;
	}

	public void setContactId(long contactId) {
		_columnBitmask = -1L;

		if (!_setOriginalContactId) {
			_setOriginalContactId = true;

			_originalContactId = _contactId;
		}

		_contactId = contactId;
	}

	public long getOriginalContactId() {
		return _originalContactId;
	}

	@JSON
	public String getPropertyKey() {
		if (_propertyKey == null) {
			return StringPool.BLANK;
		}
		else {
			return _propertyKey;
		}
	}

	public void setPropertyKey(String propertyKey) {
		_columnBitmask = -1L;

		if (_originalPropertyKey == null) {
			_originalPropertyKey = _propertyKey;
		}

		_propertyKey = propertyKey;
	}

	public String getOriginalPropertyKey() {
		return GetterUtil.getString(_originalPropertyKey);
	}

	@JSON
	public String getPropertyValue() {
		if (_propertyValue == null) {
			return StringPool.BLANK;
		}
		else {
			return _propertyValue;
		}
	}

	public void setPropertyValue(String propertyValue) {
		_propertyValue = propertyValue;
	}

	@JSON
	public String getPropertyType() {
		if (_propertyType == null) {
			return StringPool.BLANK;
		}
		else {
			return _propertyType;
		}
	}

	public void setPropertyType(String propertyType) {
		_propertyType = propertyType;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ContactsProperty.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ContactsProperty toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (ContactsProperty)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		ContactsPropertyImpl contactsPropertyImpl = new ContactsPropertyImpl();

		contactsPropertyImpl.setPropertyId(getPropertyId());
		contactsPropertyImpl.setGroupId(getGroupId());
		contactsPropertyImpl.setCompanyId(getCompanyId());
		contactsPropertyImpl.setUserId(getUserId());
		contactsPropertyImpl.setUserName(getUserName());
		contactsPropertyImpl.setCreateDate(getCreateDate());
		contactsPropertyImpl.setModifiedDate(getModifiedDate());
		contactsPropertyImpl.setContactId(getContactId());
		contactsPropertyImpl.setPropertyKey(getPropertyKey());
		contactsPropertyImpl.setPropertyValue(getPropertyValue());
		contactsPropertyImpl.setPropertyType(getPropertyType());

		contactsPropertyImpl.resetOriginalValues();

		return contactsPropertyImpl;
	}

	public int compareTo(ContactsProperty contactsProperty) {
		int value = 0;

		if (getContactId() < contactsProperty.getContactId()) {
			value = -1;
		}
		else if (getContactId() > contactsProperty.getContactId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		value = getPropertyKey().toLowerCase()
					.compareTo(contactsProperty.getPropertyKey().toLowerCase());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		ContactsProperty contactsProperty = null;

		try {
			contactsProperty = (ContactsProperty)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = contactsProperty.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ContactsPropertyModelImpl contactsPropertyModelImpl = this;

		contactsPropertyModelImpl._originalGroupId = contactsPropertyModelImpl._groupId;

		contactsPropertyModelImpl._setOriginalGroupId = false;

		contactsPropertyModelImpl._originalCompanyId = contactsPropertyModelImpl._companyId;

		contactsPropertyModelImpl._setOriginalCompanyId = false;

		contactsPropertyModelImpl._originalContactId = contactsPropertyModelImpl._contactId;

		contactsPropertyModelImpl._setOriginalContactId = false;

		contactsPropertyModelImpl._originalPropertyKey = contactsPropertyModelImpl._propertyKey;

		contactsPropertyModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ContactsProperty> toCacheModel() {
		ContactsPropertyCacheModel contactsPropertyCacheModel = new ContactsPropertyCacheModel();

		contactsPropertyCacheModel.propertyId = getPropertyId();

		contactsPropertyCacheModel.groupId = getGroupId();

		contactsPropertyCacheModel.companyId = getCompanyId();

		contactsPropertyCacheModel.userId = getUserId();

		contactsPropertyCacheModel.userName = getUserName();

		String userName = contactsPropertyCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			contactsPropertyCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			contactsPropertyCacheModel.createDate = createDate.getTime();
		}
		else {
			contactsPropertyCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			contactsPropertyCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			contactsPropertyCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		contactsPropertyCacheModel.contactId = getContactId();

		contactsPropertyCacheModel.propertyKey = getPropertyKey();

		String propertyKey = contactsPropertyCacheModel.propertyKey;

		if ((propertyKey != null) && (propertyKey.length() == 0)) {
			contactsPropertyCacheModel.propertyKey = null;
		}

		contactsPropertyCacheModel.propertyValue = getPropertyValue();

		String propertyValue = contactsPropertyCacheModel.propertyValue;

		if ((propertyValue != null) && (propertyValue.length() == 0)) {
			contactsPropertyCacheModel.propertyValue = null;
		}

		contactsPropertyCacheModel.propertyType = getPropertyType();

		String propertyType = contactsPropertyCacheModel.propertyType;

		if ((propertyType != null) && (propertyType.length() == 0)) {
			contactsPropertyCacheModel.propertyType = null;
		}

		return contactsPropertyCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{propertyId=");
		sb.append(getPropertyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", contactId=");
		sb.append(getContactId());
		sb.append(", propertyKey=");
		sb.append(getPropertyKey());
		sb.append(", propertyValue=");
		sb.append(getPropertyValue());
		sb.append(", propertyType=");
		sb.append(getPropertyType());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.portal_egov.portlet.contacts.model.ContactsProperty");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>propertyId</column-name><column-value><![CDATA[");
		sb.append(getPropertyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>contactId</column-name><column-value><![CDATA[");
		sb.append(getContactId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>propertyKey</column-name><column-value><![CDATA[");
		sb.append(getPropertyKey());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>propertyValue</column-name><column-value><![CDATA[");
		sb.append(getPropertyValue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>propertyType</column-name><column-value><![CDATA[");
		sb.append(getPropertyType());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ContactsProperty.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			ContactsProperty.class
		};
	private long _propertyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _contactId;
	private long _originalContactId;
	private boolean _setOriginalContactId;
	private String _propertyKey;
	private String _originalPropertyKey;
	private String _propertyValue;
	private String _propertyType;
	private long _columnBitmask;
	private ContactsProperty _escapedModelProxy;
}