/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.portal_egov.portlet.tthc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TTHC_Attribute service. Represents a row in the &quot;tthc_attribute&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.portal_egov.portlet.tthc.model.impl.TTHC_AttributeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.portal_egov.portlet.tthc.model.impl.TTHC_AttributeImpl}.
 * </p>
 *
 * @author HungDX
 * @see TTHC_Attribute
 * @see com.portal_egov.portlet.tthc.model.impl.TTHC_AttributeImpl
 * @see com.portal_egov.portlet.tthc.model.impl.TTHC_AttributeModelImpl
 * @generated
 */
public interface TTHC_AttributeModel extends BaseModel<TTHC_Attribute> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a t t h c_ attribute model instance should use the {@link TTHC_Attribute} interface instead.
	 */

	/**
	 * Returns the primary key of this t t h c_ attribute.
	 *
	 * @return the primary key of this t t h c_ attribute
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this t t h c_ attribute.
	 *
	 * @param primaryKey the primary key of this t t h c_ attribute
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the attribute ID of this t t h c_ attribute.
	 *
	 * @return the attribute ID of this t t h c_ attribute
	 */
	public long getAttributeId();

	/**
	 * Sets the attribute ID of this t t h c_ attribute.
	 *
	 * @param attributeId the attribute ID of this t t h c_ attribute
	 */
	public void setAttributeId(long attributeId);

	/**
	 * Returns the company ID of this t t h c_ attribute.
	 *
	 * @return the company ID of this t t h c_ attribute
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this t t h c_ attribute.
	 *
	 * @param companyId the company ID of this t t h c_ attribute
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this t t h c_ attribute.
	 *
	 * @return the group ID of this t t h c_ attribute
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this t t h c_ attribute.
	 *
	 * @param groupId the group ID of this t t h c_ attribute
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this t t h c_ attribute.
	 *
	 * @return the user ID of this t t h c_ attribute
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this t t h c_ attribute.
	 *
	 * @param userId the user ID of this t t h c_ attribute
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this t t h c_ attribute.
	 *
	 * @return the user uuid of this t t h c_ attribute
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this t t h c_ attribute.
	 *
	 * @param userUuid the user uuid of this t t h c_ attribute
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the tthc entry ID of this t t h c_ attribute.
	 *
	 * @return the tthc entry ID of this t t h c_ attribute
	 */
	public long getTthcEntryId();

	/**
	 * Sets the tthc entry ID of this t t h c_ attribute.
	 *
	 * @param tthcEntryId the tthc entry ID of this t t h c_ attribute
	 */
	public void setTthcEntryId(long tthcEntryId);

	/**
	 * Returns the attribute type ID of this t t h c_ attribute.
	 *
	 * @return the attribute type ID of this t t h c_ attribute
	 */
	public int getAttributeTypeId();

	/**
	 * Sets the attribute type ID of this t t h c_ attribute.
	 *
	 * @param attributeTypeId the attribute type ID of this t t h c_ attribute
	 */
	public void setAttributeTypeId(int attributeTypeId);

	/**
	 * Returns the attribute index of this t t h c_ attribute.
	 *
	 * @return the attribute index of this t t h c_ attribute
	 */
	public int getAttributeIndex();

	/**
	 * Sets the attribute index of this t t h c_ attribute.
	 *
	 * @param attributeIndex the attribute index of this t t h c_ attribute
	 */
	public void setAttributeIndex(int attributeIndex);

	/**
	 * Returns the attribute name of this t t h c_ attribute.
	 *
	 * @return the attribute name of this t t h c_ attribute
	 */
	@AutoEscape
	public String getAttributeName();

	/**
	 * Sets the attribute name of this t t h c_ attribute.
	 *
	 * @param attributeName the attribute name of this t t h c_ attribute
	 */
	public void setAttributeName(String attributeName);

	/**
	 * Returns the attribute value of this t t h c_ attribute.
	 *
	 * @return the attribute value of this t t h c_ attribute
	 */
	@AutoEscape
	public String getAttributeValue();

	/**
	 * Sets the attribute value of this t t h c_ attribute.
	 *
	 * @param attributeValue the attribute value of this t t h c_ attribute
	 */
	public void setAttributeValue(String attributeValue);

	/**
	 * Returns the create date of this t t h c_ attribute.
	 *
	 * @return the create date of this t t h c_ attribute
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this t t h c_ attribute.
	 *
	 * @param createDate the create date of this t t h c_ attribute
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this t t h c_ attribute.
	 *
	 * @return the modified date of this t t h c_ attribute
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this t t h c_ attribute.
	 *
	 * @param modifiedDate the modified date of this t t h c_ attribute
	 */
	public void setModifiedDate(Date modifiedDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TTHC_Attribute tthc_Attribute);

	public int hashCode();

	public CacheModel<TTHC_Attribute> toCacheModel();

	public TTHC_Attribute toEscapedModel();

	public String toString();

	public String toXmlString();
}