/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.portal_egov.portlet.tthc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TTHC_Entry service. Represents a row in the &quot;tthc_entry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.portal_egov.portlet.tthc.model.impl.TTHC_EntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.portal_egov.portlet.tthc.model.impl.TTHC_EntryImpl}.
 * </p>
 *
 * @author HungDX
 * @see TTHC_Entry
 * @see com.portal_egov.portlet.tthc.model.impl.TTHC_EntryImpl
 * @see com.portal_egov.portlet.tthc.model.impl.TTHC_EntryModelImpl
 * @generated
 */
public interface TTHC_EntryModel extends BaseModel<TTHC_Entry>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a t t h c_ entry model instance should use the {@link TTHC_Entry} interface instead.
	 */

	/**
	 * Returns the primary key of this t t h c_ entry.
	 *
	 * @return the primary key of this t t h c_ entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this t t h c_ entry.
	 *
	 * @param primaryKey the primary key of this t t h c_ entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the entry ID of this t t h c_ entry.
	 *
	 * @return the entry ID of this t t h c_ entry
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this t t h c_ entry.
	 *
	 * @param entryId the entry ID of this t t h c_ entry
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the company ID of this t t h c_ entry.
	 *
	 * @return the company ID of this t t h c_ entry
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this t t h c_ entry.
	 *
	 * @param companyId the company ID of this t t h c_ entry
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this t t h c_ entry.
	 *
	 * @return the group ID of this t t h c_ entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this t t h c_ entry.
	 *
	 * @param groupId the group ID of this t t h c_ entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this t t h c_ entry.
	 *
	 * @return the user ID of this t t h c_ entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this t t h c_ entry.
	 *
	 * @param userId the user ID of this t t h c_ entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this t t h c_ entry.
	 *
	 * @return the user uuid of this t t h c_ entry
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this t t h c_ entry.
	 *
	 * @param userUuid the user uuid of this t t h c_ entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this t t h c_ entry.
	 *
	 * @return the user name of this t t h c_ entry
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this t t h c_ entry.
	 *
	 * @param userName the user name of this t t h c_ entry
	 */
	public void setUserName(String userName);

	/**
	 * Returns the level ID of this t t h c_ entry.
	 *
	 * @return the level ID of this t t h c_ entry
	 */
	public long getLevelId();

	/**
	 * Sets the level ID of this t t h c_ entry.
	 *
	 * @param levelId the level ID of this t t h c_ entry
	 */
	public void setLevelId(long levelId);

	/**
	 * Returns the department ID of this t t h c_ entry.
	 *
	 * @return the department ID of this t t h c_ entry
	 */
	public long getDepartmentId();

	/**
	 * Sets the department ID of this t t h c_ entry.
	 *
	 * @param departmentId the department ID of this t t h c_ entry
	 */
	public void setDepartmentId(long departmentId);

	/**
	 * Returns the category ID of this t t h c_ entry.
	 *
	 * @return the category ID of this t t h c_ entry
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this t t h c_ entry.
	 *
	 * @param categoryId the category ID of this t t h c_ entry
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the audience ID of this t t h c_ entry.
	 *
	 * @return the audience ID of this t t h c_ entry
	 */
	public long getAudienceId();

	/**
	 * Sets the audience ID of this t t h c_ entry.
	 *
	 * @param audienceId the audience ID of this t t h c_ entry
	 */
	public void setAudienceId(long audienceId);

	/**
	 * Returns the result type ID of this t t h c_ entry.
	 *
	 * @return the result type ID of this t t h c_ entry
	 */
	public long getResultTypeId();

	/**
	 * Sets the result type ID of this t t h c_ entry.
	 *
	 * @param resultTypeId the result type ID of this t t h c_ entry
	 */
	public void setResultTypeId(long resultTypeId);

	/**
	 * Returns the entry code of this t t h c_ entry.
	 *
	 * @return the entry code of this t t h c_ entry
	 */
	@AutoEscape
	public String getEntryCode();

	/**
	 * Sets the entry code of this t t h c_ entry.
	 *
	 * @param entryCode the entry code of this t t h c_ entry
	 */
	public void setEntryCode(String entryCode);

	/**
	 * Returns the entry name of this t t h c_ entry.
	 *
	 * @return the entry name of this t t h c_ entry
	 */
	@AutoEscape
	public String getEntryName();

	/**
	 * Sets the entry name of this t t h c_ entry.
	 *
	 * @param entryName the entry name of this t t h c_ entry
	 */
	public void setEntryName(String entryName);

	/**
	 * Returns the entry desc of this t t h c_ entry.
	 *
	 * @return the entry desc of this t t h c_ entry
	 */
	@AutoEscape
	public String getEntryDesc();

	/**
	 * Sets the entry desc of this t t h c_ entry.
	 *
	 * @param entryDesc the entry desc of this t t h c_ entry
	 */
	public void setEntryDesc(String entryDesc);

	/**
	 * Returns the process guide of this t t h c_ entry.
	 *
	 * @return the process guide of this t t h c_ entry
	 */
	@AutoEscape
	public String getProcessGuide();

	/**
	 * Sets the process guide of this t t h c_ entry.
	 *
	 * @param processGuide the process guide of this t t h c_ entry
	 */
	public void setProcessGuide(String processGuide);

	/**
	 * Returns the process type of this t t h c_ entry.
	 *
	 * @return the process type of this t t h c_ entry
	 */
	@AutoEscape
	public String getProcessType();

	/**
	 * Sets the process type of this t t h c_ entry.
	 *
	 * @param processType the process type of this t t h c_ entry
	 */
	public void setProcessType(String processType);

	/**
	 * Returns the process time of this t t h c_ entry.
	 *
	 * @return the process time of this t t h c_ entry
	 */
	@AutoEscape
	public String getProcessTime();

	/**
	 * Sets the process time of this t t h c_ entry.
	 *
	 * @param processTime the process time of this t t h c_ entry
	 */
	public void setProcessTime(String processTime);

	/**
	 * Returns the process fee of this t t h c_ entry.
	 *
	 * @return the process fee of this t t h c_ entry
	 */
	@AutoEscape
	public String getProcessFee();

	/**
	 * Sets the process fee of this t t h c_ entry.
	 *
	 * @param processFee the process fee of this t t h c_ entry
	 */
	public void setProcessFee(String processFee);

	/**
	 * Returns the process requirement of this t t h c_ entry.
	 *
	 * @return the process requirement of this t t h c_ entry
	 */
	@AutoEscape
	public String getProcessRequirement();

	/**
	 * Sets the process requirement of this t t h c_ entry.
	 *
	 * @param processRequirement the process requirement of this t t h c_ entry
	 */
	public void setProcessRequirement(String processRequirement);

	/**
	 * Returns the process foundation document of this t t h c_ entry.
	 *
	 * @return the process foundation document of this t t h c_ entry
	 */
	@AutoEscape
	public String getProcessFoundationDocument();

	/**
	 * Sets the process foundation document of this t t h c_ entry.
	 *
	 * @param processFoundationDocument the process foundation document of this t t h c_ entry
	 */
	public void setProcessFoundationDocument(String processFoundationDocument);

	/**
	 * Returns the create date of this t t h c_ entry.
	 *
	 * @return the create date of this t t h c_ entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this t t h c_ entry.
	 *
	 * @param createDate the create date of this t t h c_ entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this t t h c_ entry.
	 *
	 * @return the modified date of this t t h c_ entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this t t h c_ entry.
	 *
	 * @param modifiedDate the modified date of this t t h c_ entry
	 */
	public void setModifiedDate(Date modifiedDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TTHC_Entry tthc_Entry);

	public int hashCode();

	public CacheModel<TTHC_Entry> toCacheModel();

	public TTHC_Entry toEscapedModel();

	public String toString();

	public String toXmlString();
}