/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.portal_egov.portlet.visit_counter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VisitCounter service. Represents a row in the &quot;VisitCounter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.portal_egov.portlet.visit_counter.model.impl.VisitCounterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.portal_egov.portlet.visit_counter.model.impl.VisitCounterImpl}.
 * </p>
 *
 * @author HungDX
 * @see VisitCounter
 * @see com.portal_egov.portlet.visit_counter.model.impl.VisitCounterImpl
 * @see com.portal_egov.portlet.visit_counter.model.impl.VisitCounterModelImpl
 * @generated
 */
public interface VisitCounterModel extends BaseModel<VisitCounter>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a visit counter model instance should use the {@link VisitCounter} interface instead.
	 */

	/**
	 * Returns the primary key of this visit counter.
	 *
	 * @return the primary key of this visit counter
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this visit counter.
	 *
	 * @param primaryKey the primary key of this visit counter
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the counter ID of this visit counter.
	 *
	 * @return the counter ID of this visit counter
	 */
	public long getCounterId();

	/**
	 * Sets the counter ID of this visit counter.
	 *
	 * @param counterId the counter ID of this visit counter
	 */
	public void setCounterId(long counterId);

	/**
	 * Returns the company ID of this visit counter.
	 *
	 * @return the company ID of this visit counter
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this visit counter.
	 *
	 * @param companyId the company ID of this visit counter
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this visit counter.
	 *
	 * @return the group ID of this visit counter
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this visit counter.
	 *
	 * @param groupId the group ID of this visit counter
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this visit counter.
	 *
	 * @return the user ID of this visit counter
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this visit counter.
	 *
	 * @param userId the user ID of this visit counter
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this visit counter.
	 *
	 * @return the user uuid of this visit counter
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this visit counter.
	 *
	 * @param userUuid the user uuid of this visit counter
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this visit counter.
	 *
	 * @return the user name of this visit counter
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this visit counter.
	 *
	 * @param userName the user name of this visit counter
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this visit counter.
	 *
	 * @return the create date of this visit counter
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this visit counter.
	 *
	 * @param createDate the create date of this visit counter
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this visit counter.
	 *
	 * @return the modified date of this visit counter
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this visit counter.
	 *
	 * @param modifiedDate the modified date of this visit counter
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the total hit counter of this visit counter.
	 *
	 * @return the total hit counter of this visit counter
	 */
	public int getTotalHitCounter();

	/**
	 * Sets the total hit counter of this visit counter.
	 *
	 * @param totalHitCounter the total hit counter of this visit counter
	 */
	public void setTotalHitCounter(int totalHitCounter);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VisitCounter visitCounter);

	public int hashCode();

	public CacheModel<VisitCounter> toCacheModel();

	public VisitCounter toEscapedModel();

	public String toString();

	public String toXmlString();
}