/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.portal_egov.portlet.vbpq.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.portal_egov.portlet.vbpq.model.VBPQ_DlFileEntries;
import com.portal_egov.portlet.vbpq.model.VBPQ_DlFileEntriesModel;
import com.portal_egov.portlet.vbpq.model.VBPQ_DlFileEntriesSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the VBPQ_DlFileEntries service. Represents a row in the &quot;vbpq_dlfileentries&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.portal_egov.portlet.vbpq.model.VBPQ_DlFileEntriesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VBPQ_DlFileEntriesImpl}.
 * </p>
 *
 * @author HungDX
 * @see VBPQ_DlFileEntriesImpl
 * @see com.portal_egov.portlet.vbpq.model.VBPQ_DlFileEntries
 * @see com.portal_egov.portlet.vbpq.model.VBPQ_DlFileEntriesModel
 * @generated
 */
@JSON(strict = true)
public class VBPQ_DlFileEntriesModelImpl extends BaseModelImpl<VBPQ_DlFileEntries>
	implements VBPQ_DlFileEntriesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a v b p q_ dl file entries model instance should use the {@link com.portal_egov.portlet.vbpq.model.VBPQ_DlFileEntries} interface instead.
	 */
	public static final String TABLE_NAME = "vbpq_dlfileentries";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "vbpqEntryId", Types.BIGINT },
			{ "fileEntryId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table vbpq_dlfileentries (id_ LONG not null primary key,vbpqEntryId LONG,fileEntryId LONG)";
	public static final String TABLE_SQL_DROP = "drop table vbpq_dlfileentries";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.portal_egov.portlet.vbpq.model.VBPQ_DlFileEntries"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.portal_egov.portlet.vbpq.model.VBPQ_DlFileEntries"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.portal_egov.portlet.vbpq.model.VBPQ_DlFileEntries"),
			true);
	public static long FILEENTRYID_COLUMN_BITMASK = 1L;
	public static long VBPQENTRYID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VBPQ_DlFileEntries toModel(VBPQ_DlFileEntriesSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		VBPQ_DlFileEntries model = new VBPQ_DlFileEntriesImpl();

		model.setId(soapModel.getId());
		model.setVbpqEntryId(soapModel.getVbpqEntryId());
		model.setFileEntryId(soapModel.getFileEntryId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VBPQ_DlFileEntries> toModels(
		VBPQ_DlFileEntriesSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<VBPQ_DlFileEntries> models = new ArrayList<VBPQ_DlFileEntries>(soapModels.length);

		for (VBPQ_DlFileEntriesSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.portal_egov.portlet.vbpq.model.VBPQ_DlFileEntries"));

	public VBPQ_DlFileEntriesModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return VBPQ_DlFileEntries.class;
	}

	public String getModelClassName() {
		return VBPQ_DlFileEntries.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("vbpqEntryId", getVbpqEntryId());
		attributes.put("fileEntryId", getFileEntryId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long vbpqEntryId = (Long)attributes.get("vbpqEntryId");

		if (vbpqEntryId != null) {
			setVbpqEntryId(vbpqEntryId);
		}

		Long fileEntryId = (Long)attributes.get("fileEntryId");

		if (fileEntryId != null) {
			setFileEntryId(fileEntryId);
		}
	}

	@JSON
	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	@JSON
	public long getVbpqEntryId() {
		return _vbpqEntryId;
	}

	public void setVbpqEntryId(long vbpqEntryId) {
		_columnBitmask |= VBPQENTRYID_COLUMN_BITMASK;

		if (!_setOriginalVbpqEntryId) {
			_setOriginalVbpqEntryId = true;

			_originalVbpqEntryId = _vbpqEntryId;
		}

		_vbpqEntryId = vbpqEntryId;
	}

	public long getOriginalVbpqEntryId() {
		return _originalVbpqEntryId;
	}

	@JSON
	public long getFileEntryId() {
		return _fileEntryId;
	}

	public void setFileEntryId(long fileEntryId) {
		_columnBitmask |= FILEENTRYID_COLUMN_BITMASK;

		if (!_setOriginalFileEntryId) {
			_setOriginalFileEntryId = true;

			_originalFileEntryId = _fileEntryId;
		}

		_fileEntryId = fileEntryId;
	}

	public long getOriginalFileEntryId() {
		return _originalFileEntryId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			VBPQ_DlFileEntries.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VBPQ_DlFileEntries toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (VBPQ_DlFileEntries)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		VBPQ_DlFileEntriesImpl vbpq_DlFileEntriesImpl = new VBPQ_DlFileEntriesImpl();

		vbpq_DlFileEntriesImpl.setId(getId());
		vbpq_DlFileEntriesImpl.setVbpqEntryId(getVbpqEntryId());
		vbpq_DlFileEntriesImpl.setFileEntryId(getFileEntryId());

		vbpq_DlFileEntriesImpl.resetOriginalValues();

		return vbpq_DlFileEntriesImpl;
	}

	public int compareTo(VBPQ_DlFileEntries vbpq_DlFileEntries) {
		long primaryKey = vbpq_DlFileEntries.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		VBPQ_DlFileEntries vbpq_DlFileEntries = null;

		try {
			vbpq_DlFileEntries = (VBPQ_DlFileEntries)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = vbpq_DlFileEntries.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		VBPQ_DlFileEntriesModelImpl vbpq_DlFileEntriesModelImpl = this;

		vbpq_DlFileEntriesModelImpl._originalVbpqEntryId = vbpq_DlFileEntriesModelImpl._vbpqEntryId;

		vbpq_DlFileEntriesModelImpl._setOriginalVbpqEntryId = false;

		vbpq_DlFileEntriesModelImpl._originalFileEntryId = vbpq_DlFileEntriesModelImpl._fileEntryId;

		vbpq_DlFileEntriesModelImpl._setOriginalFileEntryId = false;

		vbpq_DlFileEntriesModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VBPQ_DlFileEntries> toCacheModel() {
		VBPQ_DlFileEntriesCacheModel vbpq_DlFileEntriesCacheModel = new VBPQ_DlFileEntriesCacheModel();

		vbpq_DlFileEntriesCacheModel.id = getId();

		vbpq_DlFileEntriesCacheModel.vbpqEntryId = getVbpqEntryId();

		vbpq_DlFileEntriesCacheModel.fileEntryId = getFileEntryId();

		return vbpq_DlFileEntriesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", vbpqEntryId=");
		sb.append(getVbpqEntryId());
		sb.append(", fileEntryId=");
		sb.append(getFileEntryId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.portal_egov.portlet.vbpq.model.VBPQ_DlFileEntries");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vbpqEntryId</column-name><column-value><![CDATA[");
		sb.append(getVbpqEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileEntryId</column-name><column-value><![CDATA[");
		sb.append(getFileEntryId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = VBPQ_DlFileEntries.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			VBPQ_DlFileEntries.class
		};
	private long _id;
	private long _vbpqEntryId;
	private long _originalVbpqEntryId;
	private boolean _setOriginalVbpqEntryId;
	private long _fileEntryId;
	private long _originalFileEntryId;
	private boolean _setOriginalFileEntryId;
	private long _columnBitmask;
	private VBPQ_DlFileEntries _escapedModelProxy;
}