/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.portal_egov.portlet.vbpq.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.portal_egov.portlet.vbpq.model.VBPQ_DlFileEntries;
import com.portal_egov.portlet.vbpq.service.VBPQ_DlFileEntriesLocalServiceUtil;

/**
 * The extended model base implementation for the VBPQ_DlFileEntries service. Represents a row in the &quot;vbpq_dlfileentries&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VBPQ_DlFileEntriesImpl}.
 * </p>
 *
 * @author HungDX
 * @see VBPQ_DlFileEntriesImpl
 * @see com.portal_egov.portlet.vbpq.model.VBPQ_DlFileEntries
 * @generated
 */
public abstract class VBPQ_DlFileEntriesBaseImpl
	extends VBPQ_DlFileEntriesModelImpl implements VBPQ_DlFileEntries {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a v b p q_ dl file entries model instance should use the {@link VBPQ_DlFileEntries} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			VBPQ_DlFileEntriesLocalServiceUtil.addVBPQ_DlFileEntries(this);
		}
		else {
			VBPQ_DlFileEntriesLocalServiceUtil.updateVBPQ_DlFileEntries(this);
		}
	}
}