/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.portal_egov.portlet.vbpq.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.portal_egov.portlet.vbpq.model.VBPQ_DlFileEntries;
import com.portal_egov.portlet.vbpq.service.VBPQ_CategoryLocalService;
import com.portal_egov.portlet.vbpq.service.VBPQ_CategoryService;
import com.portal_egov.portlet.vbpq.service.VBPQ_DlFileEntriesLocalService;
import com.portal_egov.portlet.vbpq.service.VBPQ_DlFileEntriesService;
import com.portal_egov.portlet.vbpq.service.VBPQ_EntryLocalService;
import com.portal_egov.portlet.vbpq.service.VBPQ_EntryService;
import com.portal_egov.portlet.vbpq.service.persistence.VBPQ_CategoryFinder;
import com.portal_egov.portlet.vbpq.service.persistence.VBPQ_CategoryPersistence;
import com.portal_egov.portlet.vbpq.service.persistence.VBPQ_DlFileEntriesPersistence;
import com.portal_egov.portlet.vbpq.service.persistence.VBPQ_EntryFinder;
import com.portal_egov.portlet.vbpq.service.persistence.VBPQ_EntryPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the v b p q_ dl file entries local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.portal_egov.portlet.vbpq.service.impl.VBPQ_DlFileEntriesLocalServiceImpl}.
 * </p>
 *
 * @author HungDX
 * @see com.portal_egov.portlet.vbpq.service.impl.VBPQ_DlFileEntriesLocalServiceImpl
 * @see com.portal_egov.portlet.vbpq.service.VBPQ_DlFileEntriesLocalServiceUtil
 * @generated
 */
public abstract class VBPQ_DlFileEntriesLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements VBPQ_DlFileEntriesLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.portal_egov.portlet.vbpq.service.VBPQ_DlFileEntriesLocalServiceUtil} to access the v b p q_ dl file entries local service.
	 */

	/**
	 * Adds the v b p q_ dl file entries to the database. Also notifies the appropriate model listeners.
	 *
	 * @param vbpq_DlFileEntries the v b p q_ dl file entries
	 * @return the v b p q_ dl file entries that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public VBPQ_DlFileEntries addVBPQ_DlFileEntries(
		VBPQ_DlFileEntries vbpq_DlFileEntries) throws SystemException {
		vbpq_DlFileEntries.setNew(true);

		return vbpq_DlFileEntriesPersistence.update(vbpq_DlFileEntries, false);
	}

	/**
	 * Creates a new v b p q_ dl file entries with the primary key. Does not add the v b p q_ dl file entries to the database.
	 *
	 * @param id the primary key for the new v b p q_ dl file entries
	 * @return the new v b p q_ dl file entries
	 */
	public VBPQ_DlFileEntries createVBPQ_DlFileEntries(long id) {
		return vbpq_DlFileEntriesPersistence.create(id);
	}

	/**
	 * Deletes the v b p q_ dl file entries with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id the primary key of the v b p q_ dl file entries
	 * @return the v b p q_ dl file entries that was removed
	 * @throws PortalException if a v b p q_ dl file entries with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public VBPQ_DlFileEntries deleteVBPQ_DlFileEntries(long id)
		throws PortalException, SystemException {
		return vbpq_DlFileEntriesPersistence.remove(id);
	}

	/**
	 * Deletes the v b p q_ dl file entries from the database. Also notifies the appropriate model listeners.
	 *
	 * @param vbpq_DlFileEntries the v b p q_ dl file entries
	 * @return the v b p q_ dl file entries that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public VBPQ_DlFileEntries deleteVBPQ_DlFileEntries(
		VBPQ_DlFileEntries vbpq_DlFileEntries) throws SystemException {
		return vbpq_DlFileEntriesPersistence.remove(vbpq_DlFileEntries);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(VBPQ_DlFileEntries.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return vbpq_DlFileEntriesPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return vbpq_DlFileEntriesPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return vbpq_DlFileEntriesPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return vbpq_DlFileEntriesPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public VBPQ_DlFileEntries fetchVBPQ_DlFileEntries(long id)
		throws SystemException {
		return vbpq_DlFileEntriesPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the v b p q_ dl file entries with the primary key.
	 *
	 * @param id the primary key of the v b p q_ dl file entries
	 * @return the v b p q_ dl file entries
	 * @throws PortalException if a v b p q_ dl file entries with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public VBPQ_DlFileEntries getVBPQ_DlFileEntries(long id)
		throws PortalException, SystemException {
		return vbpq_DlFileEntriesPersistence.findByPrimaryKey(id);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return vbpq_DlFileEntriesPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the v b p q_ dl file entrieses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of v b p q_ dl file entrieses
	 * @param end the upper bound of the range of v b p q_ dl file entrieses (not inclusive)
	 * @return the range of v b p q_ dl file entrieses
	 * @throws SystemException if a system exception occurred
	 */
	public List<VBPQ_DlFileEntries> getVBPQ_DlFileEntrieses(int start, int end)
		throws SystemException {
		return vbpq_DlFileEntriesPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of v b p q_ dl file entrieses.
	 *
	 * @return the number of v b p q_ dl file entrieses
	 * @throws SystemException if a system exception occurred
	 */
	public int getVBPQ_DlFileEntriesesCount() throws SystemException {
		return vbpq_DlFileEntriesPersistence.countAll();
	}

	/**
	 * Updates the v b p q_ dl file entries in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param vbpq_DlFileEntries the v b p q_ dl file entries
	 * @return the v b p q_ dl file entries that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public VBPQ_DlFileEntries updateVBPQ_DlFileEntries(
		VBPQ_DlFileEntries vbpq_DlFileEntries) throws SystemException {
		return updateVBPQ_DlFileEntries(vbpq_DlFileEntries, true);
	}

	/**
	 * Updates the v b p q_ dl file entries in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param vbpq_DlFileEntries the v b p q_ dl file entries
	 * @param merge whether to merge the v b p q_ dl file entries with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the v b p q_ dl file entries that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public VBPQ_DlFileEntries updateVBPQ_DlFileEntries(
		VBPQ_DlFileEntries vbpq_DlFileEntries, boolean merge)
		throws SystemException {
		vbpq_DlFileEntries.setNew(false);

		return vbpq_DlFileEntriesPersistence.update(vbpq_DlFileEntries, merge);
	}

	/**
	 * Returns the v b p q_ category local service.
	 *
	 * @return the v b p q_ category local service
	 */
	public VBPQ_CategoryLocalService getVBPQ_CategoryLocalService() {
		return vbpq_CategoryLocalService;
	}

	/**
	 * Sets the v b p q_ category local service.
	 *
	 * @param vbpq_CategoryLocalService the v b p q_ category local service
	 */
	public void setVBPQ_CategoryLocalService(
		VBPQ_CategoryLocalService vbpq_CategoryLocalService) {
		this.vbpq_CategoryLocalService = vbpq_CategoryLocalService;
	}

	/**
	 * Returns the v b p q_ category remote service.
	 *
	 * @return the v b p q_ category remote service
	 */
	public VBPQ_CategoryService getVBPQ_CategoryService() {
		return vbpq_CategoryService;
	}

	/**
	 * Sets the v b p q_ category remote service.
	 *
	 * @param vbpq_CategoryService the v b p q_ category remote service
	 */
	public void setVBPQ_CategoryService(
		VBPQ_CategoryService vbpq_CategoryService) {
		this.vbpq_CategoryService = vbpq_CategoryService;
	}

	/**
	 * Returns the v b p q_ category persistence.
	 *
	 * @return the v b p q_ category persistence
	 */
	public VBPQ_CategoryPersistence getVBPQ_CategoryPersistence() {
		return vbpq_CategoryPersistence;
	}

	/**
	 * Sets the v b p q_ category persistence.
	 *
	 * @param vbpq_CategoryPersistence the v b p q_ category persistence
	 */
	public void setVBPQ_CategoryPersistence(
		VBPQ_CategoryPersistence vbpq_CategoryPersistence) {
		this.vbpq_CategoryPersistence = vbpq_CategoryPersistence;
	}

	/**
	 * Returns the v b p q_ category finder.
	 *
	 * @return the v b p q_ category finder
	 */
	public VBPQ_CategoryFinder getVBPQ_CategoryFinder() {
		return vbpq_CategoryFinder;
	}

	/**
	 * Sets the v b p q_ category finder.
	 *
	 * @param vbpq_CategoryFinder the v b p q_ category finder
	 */
	public void setVBPQ_CategoryFinder(VBPQ_CategoryFinder vbpq_CategoryFinder) {
		this.vbpq_CategoryFinder = vbpq_CategoryFinder;
	}

	/**
	 * Returns the v b p q_ dl file entries local service.
	 *
	 * @return the v b p q_ dl file entries local service
	 */
	public VBPQ_DlFileEntriesLocalService getVBPQ_DlFileEntriesLocalService() {
		return vbpq_DlFileEntriesLocalService;
	}

	/**
	 * Sets the v b p q_ dl file entries local service.
	 *
	 * @param vbpq_DlFileEntriesLocalService the v b p q_ dl file entries local service
	 */
	public void setVBPQ_DlFileEntriesLocalService(
		VBPQ_DlFileEntriesLocalService vbpq_DlFileEntriesLocalService) {
		this.vbpq_DlFileEntriesLocalService = vbpq_DlFileEntriesLocalService;
	}

	/**
	 * Returns the v b p q_ dl file entries remote service.
	 *
	 * @return the v b p q_ dl file entries remote service
	 */
	public VBPQ_DlFileEntriesService getVBPQ_DlFileEntriesService() {
		return vbpq_DlFileEntriesService;
	}

	/**
	 * Sets the v b p q_ dl file entries remote service.
	 *
	 * @param vbpq_DlFileEntriesService the v b p q_ dl file entries remote service
	 */
	public void setVBPQ_DlFileEntriesService(
		VBPQ_DlFileEntriesService vbpq_DlFileEntriesService) {
		this.vbpq_DlFileEntriesService = vbpq_DlFileEntriesService;
	}

	/**
	 * Returns the v b p q_ dl file entries persistence.
	 *
	 * @return the v b p q_ dl file entries persistence
	 */
	public VBPQ_DlFileEntriesPersistence getVBPQ_DlFileEntriesPersistence() {
		return vbpq_DlFileEntriesPersistence;
	}

	/**
	 * Sets the v b p q_ dl file entries persistence.
	 *
	 * @param vbpq_DlFileEntriesPersistence the v b p q_ dl file entries persistence
	 */
	public void setVBPQ_DlFileEntriesPersistence(
		VBPQ_DlFileEntriesPersistence vbpq_DlFileEntriesPersistence) {
		this.vbpq_DlFileEntriesPersistence = vbpq_DlFileEntriesPersistence;
	}

	/**
	 * Returns the v b p q_ entry local service.
	 *
	 * @return the v b p q_ entry local service
	 */
	public VBPQ_EntryLocalService getVBPQ_EntryLocalService() {
		return vbpq_EntryLocalService;
	}

	/**
	 * Sets the v b p q_ entry local service.
	 *
	 * @param vbpq_EntryLocalService the v b p q_ entry local service
	 */
	public void setVBPQ_EntryLocalService(
		VBPQ_EntryLocalService vbpq_EntryLocalService) {
		this.vbpq_EntryLocalService = vbpq_EntryLocalService;
	}

	/**
	 * Returns the v b p q_ entry remote service.
	 *
	 * @return the v b p q_ entry remote service
	 */
	public VBPQ_EntryService getVBPQ_EntryService() {
		return vbpq_EntryService;
	}

	/**
	 * Sets the v b p q_ entry remote service.
	 *
	 * @param vbpq_EntryService the v b p q_ entry remote service
	 */
	public void setVBPQ_EntryService(VBPQ_EntryService vbpq_EntryService) {
		this.vbpq_EntryService = vbpq_EntryService;
	}

	/**
	 * Returns the v b p q_ entry persistence.
	 *
	 * @return the v b p q_ entry persistence
	 */
	public VBPQ_EntryPersistence getVBPQ_EntryPersistence() {
		return vbpq_EntryPersistence;
	}

	/**
	 * Sets the v b p q_ entry persistence.
	 *
	 * @param vbpq_EntryPersistence the v b p q_ entry persistence
	 */
	public void setVBPQ_EntryPersistence(
		VBPQ_EntryPersistence vbpq_EntryPersistence) {
		this.vbpq_EntryPersistence = vbpq_EntryPersistence;
	}

	/**
	 * Returns the v b p q_ entry finder.
	 *
	 * @return the v b p q_ entry finder
	 */
	public VBPQ_EntryFinder getVBPQ_EntryFinder() {
		return vbpq_EntryFinder;
	}

	/**
	 * Sets the v b p q_ entry finder.
	 *
	 * @param vbpq_EntryFinder the v b p q_ entry finder
	 */
	public void setVBPQ_EntryFinder(VBPQ_EntryFinder vbpq_EntryFinder) {
		this.vbpq_EntryFinder = vbpq_EntryFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.portal_egov.portlet.vbpq.model.VBPQ_DlFileEntries",
			vbpq_DlFileEntriesLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.portal_egov.portlet.vbpq.model.VBPQ_DlFileEntries");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return VBPQ_DlFileEntries.class;
	}

	protected String getModelClassName() {
		return VBPQ_DlFileEntries.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = vbpq_DlFileEntriesPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = VBPQ_CategoryLocalService.class)
	protected VBPQ_CategoryLocalService vbpq_CategoryLocalService;
	@BeanReference(type = VBPQ_CategoryService.class)
	protected VBPQ_CategoryService vbpq_CategoryService;
	@BeanReference(type = VBPQ_CategoryPersistence.class)
	protected VBPQ_CategoryPersistence vbpq_CategoryPersistence;
	@BeanReference(type = VBPQ_CategoryFinder.class)
	protected VBPQ_CategoryFinder vbpq_CategoryFinder;
	@BeanReference(type = VBPQ_DlFileEntriesLocalService.class)
	protected VBPQ_DlFileEntriesLocalService vbpq_DlFileEntriesLocalService;
	@BeanReference(type = VBPQ_DlFileEntriesService.class)
	protected VBPQ_DlFileEntriesService vbpq_DlFileEntriesService;
	@BeanReference(type = VBPQ_DlFileEntriesPersistence.class)
	protected VBPQ_DlFileEntriesPersistence vbpq_DlFileEntriesPersistence;
	@BeanReference(type = VBPQ_EntryLocalService.class)
	protected VBPQ_EntryLocalService vbpq_EntryLocalService;
	@BeanReference(type = VBPQ_EntryService.class)
	protected VBPQ_EntryService vbpq_EntryService;
	@BeanReference(type = VBPQ_EntryPersistence.class)
	protected VBPQ_EntryPersistence vbpq_EntryPersistence;
	@BeanReference(type = VBPQ_EntryFinder.class)
	protected VBPQ_EntryFinder vbpq_EntryFinder;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private VBPQ_DlFileEntriesLocalServiceClpInvoker _clpInvoker = new VBPQ_DlFileEntriesLocalServiceClpInvoker();
}