/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.portal_egov.portlet.vbpq.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VBPQ_Entry service. Represents a row in the &quot;vbpq_entry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.portal_egov.portlet.vbpq.model.impl.VBPQ_EntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.portal_egov.portlet.vbpq.model.impl.VBPQ_EntryImpl}.
 * </p>
 *
 * @author HungDX
 * @see VBPQ_Entry
 * @see com.portal_egov.portlet.vbpq.model.impl.VBPQ_EntryImpl
 * @see com.portal_egov.portlet.vbpq.model.impl.VBPQ_EntryModelImpl
 * @generated
 */
public interface VBPQ_EntryModel extends BaseModel<VBPQ_Entry>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a v b p q_ entry model instance should use the {@link VBPQ_Entry} interface instead.
	 */

	/**
	 * Returns the primary key of this v b p q_ entry.
	 *
	 * @return the primary key of this v b p q_ entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this v b p q_ entry.
	 *
	 * @param primaryKey the primary key of this v b p q_ entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the entry ID of this v b p q_ entry.
	 *
	 * @return the entry ID of this v b p q_ entry
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this v b p q_ entry.
	 *
	 * @param entryId the entry ID of this v b p q_ entry
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the department ID of this v b p q_ entry.
	 *
	 * @return the department ID of this v b p q_ entry
	 */
	public long getDepartmentId();

	/**
	 * Sets the department ID of this v b p q_ entry.
	 *
	 * @param departmentId the department ID of this v b p q_ entry
	 */
	public void setDepartmentId(long departmentId);

	/**
	 * Returns the category ID of this v b p q_ entry.
	 *
	 * @return the category ID of this v b p q_ entry
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this v b p q_ entry.
	 *
	 * @param categoryId the category ID of this v b p q_ entry
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the doc type ID of this v b p q_ entry.
	 *
	 * @return the doc type ID of this v b p q_ entry
	 */
	public long getDocTypeId();

	/**
	 * Sets the doc type ID of this v b p q_ entry.
	 *
	 * @param docTypeId the doc type ID of this v b p q_ entry
	 */
	public void setDocTypeId(long docTypeId);

	/**
	 * Returns the company ID of this v b p q_ entry.
	 *
	 * @return the company ID of this v b p q_ entry
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this v b p q_ entry.
	 *
	 * @param companyId the company ID of this v b p q_ entry
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this v b p q_ entry.
	 *
	 * @return the group ID of this v b p q_ entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this v b p q_ entry.
	 *
	 * @param groupId the group ID of this v b p q_ entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this v b p q_ entry.
	 *
	 * @return the user ID of this v b p q_ entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this v b p q_ entry.
	 *
	 * @param userId the user ID of this v b p q_ entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this v b p q_ entry.
	 *
	 * @return the user uuid of this v b p q_ entry
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this v b p q_ entry.
	 *
	 * @param userUuid the user uuid of this v b p q_ entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this v b p q_ entry.
	 *
	 * @return the user name of this v b p q_ entry
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this v b p q_ entry.
	 *
	 * @param userName the user name of this v b p q_ entry
	 */
	public void setUserName(String userName);

	/**
	 * Returns the entry name of this v b p q_ entry.
	 *
	 * @return the entry name of this v b p q_ entry
	 */
	@AutoEscape
	public String getEntryName();

	/**
	 * Sets the entry name of this v b p q_ entry.
	 *
	 * @param entryName the entry name of this v b p q_ entry
	 */
	public void setEntryName(String entryName);

	/**
	 * Returns the entry code of this v b p q_ entry.
	 *
	 * @return the entry code of this v b p q_ entry
	 */
	@AutoEscape
	public String getEntryCode();

	/**
	 * Sets the entry code of this v b p q_ entry.
	 *
	 * @param entryCode the entry code of this v b p q_ entry
	 */
	public void setEntryCode(String entryCode);

	/**
	 * Returns the entry desc of this v b p q_ entry.
	 *
	 * @return the entry desc of this v b p q_ entry
	 */
	@AutoEscape
	public String getEntryDesc();

	/**
	 * Sets the entry desc of this v b p q_ entry.
	 *
	 * @param entryDesc the entry desc of this v b p q_ entry
	 */
	public void setEntryDesc(String entryDesc);

	/**
	 * Returns the file attachment u r l of this v b p q_ entry.
	 *
	 * @return the file attachment u r l of this v b p q_ entry
	 */
	@AutoEscape
	public String getFileAttachmentURL();

	/**
	 * Sets the file attachment u r l of this v b p q_ entry.
	 *
	 * @param fileAttachmentURL the file attachment u r l of this v b p q_ entry
	 */
	public void setFileAttachmentURL(String fileAttachmentURL);

	/**
	 * Returns the publicator name of this v b p q_ entry.
	 *
	 * @return the publicator name of this v b p q_ entry
	 */
	@AutoEscape
	public String getPublicatorName();

	/**
	 * Sets the publicator name of this v b p q_ entry.
	 *
	 * @param publicatorName the publicator name of this v b p q_ entry
	 */
	public void setPublicatorName(String publicatorName);

	/**
	 * Returns the create date of this v b p q_ entry.
	 *
	 * @return the create date of this v b p q_ entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this v b p q_ entry.
	 *
	 * @param createDate the create date of this v b p q_ entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this v b p q_ entry.
	 *
	 * @return the modified date of this v b p q_ entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this v b p q_ entry.
	 *
	 * @param modifiedDate the modified date of this v b p q_ entry
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the publish date of this v b p q_ entry.
	 *
	 * @return the publish date of this v b p q_ entry
	 */
	public Date getPublishDate();

	/**
	 * Sets the publish date of this v b p q_ entry.
	 *
	 * @param publishDate the publish date of this v b p q_ entry
	 */
	public void setPublishDate(Date publishDate);

	/**
	 * Returns the execute date of this v b p q_ entry.
	 *
	 * @return the execute date of this v b p q_ entry
	 */
	public Date getExecuteDate();

	/**
	 * Sets the execute date of this v b p q_ entry.
	 *
	 * @param executeDate the execute date of this v b p q_ entry
	 */
	public void setExecuteDate(Date executeDate);

	/**
	 * Returns the expiration date of this v b p q_ entry.
	 *
	 * @return the expiration date of this v b p q_ entry
	 */
	public Date getExpirationDate();

	/**
	 * Sets the expiration date of this v b p q_ entry.
	 *
	 * @param expirationDate the expiration date of this v b p q_ entry
	 */
	public void setExpirationDate(Date expirationDate);

	/**
	 * Returns the never expired of this v b p q_ entry.
	 *
	 * @return the never expired of this v b p q_ entry
	 */
	public boolean getNeverExpired();

	/**
	 * Returns <code>true</code> if this v b p q_ entry is never expired.
	 *
	 * @return <code>true</code> if this v b p q_ entry is never expired; <code>false</code> otherwise
	 */
	public boolean isNeverExpired();

	/**
	 * Sets whether this v b p q_ entry is never expired.
	 *
	 * @param neverExpired the never expired of this v b p q_ entry
	 */
	public void setNeverExpired(boolean neverExpired);

	/**
	 * Returns the active of this v b p q_ entry.
	 *
	 * @return the active of this v b p q_ entry
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this v b p q_ entry is active.
	 *
	 * @return <code>true</code> if this v b p q_ entry is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this v b p q_ entry is active.
	 *
	 * @param active the active of this v b p q_ entry
	 */
	public void setActive(boolean active);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VBPQ_Entry vbpq_Entry);

	public int hashCode();

	public CacheModel<VBPQ_Entry> toCacheModel();

	public VBPQ_Entry toEscapedModel();

	public String toString();

	public String toXmlString();
}