/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bkav.portal_egov.portlet.asset_statistics.service.base;

import com.bkav.portal_egov.portlet.asset_statistics.model.StatisticEntity;
import com.bkav.portal_egov.portlet.asset_statistics.service.StatisticEntityLocalService;
import com.bkav.portal_egov.portlet.asset_statistics.service.StatisticEntityService;
import com.bkav.portal_egov.portlet.asset_statistics.service.persistence.StatisticEntityFinder;
import com.bkav.portal_egov.portlet.asset_statistics.service.persistence.StatisticEntityPersistence;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import javax.sql.DataSource;

/**
 * The base implementation of the statistic entity remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.bkav.portal_egov.portlet.asset_statistics.service.impl.StatisticEntityServiceImpl}.
 * </p>
 *
 * @author HungDX
 * @see com.bkav.portal_egov.portlet.asset_statistics.service.impl.StatisticEntityServiceImpl
 * @see com.bkav.portal_egov.portlet.asset_statistics.service.StatisticEntityServiceUtil
 * @generated
 */
public abstract class StatisticEntityServiceBaseImpl extends BaseServiceImpl
	implements StatisticEntityService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.bkav.portal_egov.portlet.asset_statistics.service.StatisticEntityServiceUtil} to access the statistic entity remote service.
	 */

	/**
	 * Returns the statistic entity local service.
	 *
	 * @return the statistic entity local service
	 */
	public StatisticEntityLocalService getStatisticEntityLocalService() {
		return statisticEntityLocalService;
	}

	/**
	 * Sets the statistic entity local service.
	 *
	 * @param statisticEntityLocalService the statistic entity local service
	 */
	public void setStatisticEntityLocalService(
		StatisticEntityLocalService statisticEntityLocalService) {
		this.statisticEntityLocalService = statisticEntityLocalService;
	}

	/**
	 * Returns the statistic entity remote service.
	 *
	 * @return the statistic entity remote service
	 */
	public StatisticEntityService getStatisticEntityService() {
		return statisticEntityService;
	}

	/**
	 * Sets the statistic entity remote service.
	 *
	 * @param statisticEntityService the statistic entity remote service
	 */
	public void setStatisticEntityService(
		StatisticEntityService statisticEntityService) {
		this.statisticEntityService = statisticEntityService;
	}

	/**
	 * Returns the statistic entity persistence.
	 *
	 * @return the statistic entity persistence
	 */
	public StatisticEntityPersistence getStatisticEntityPersistence() {
		return statisticEntityPersistence;
	}

	/**
	 * Sets the statistic entity persistence.
	 *
	 * @param statisticEntityPersistence the statistic entity persistence
	 */
	public void setStatisticEntityPersistence(
		StatisticEntityPersistence statisticEntityPersistence) {
		this.statisticEntityPersistence = statisticEntityPersistence;
	}

	/**
	 * Returns the statistic entity finder.
	 *
	 * @return the statistic entity finder
	 */
	public StatisticEntityFinder getStatisticEntityFinder() {
		return statisticEntityFinder;
	}

	/**
	 * Sets the statistic entity finder.
	 *
	 * @param statisticEntityFinder the statistic entity finder
	 */
	public void setStatisticEntityFinder(
		StatisticEntityFinder statisticEntityFinder) {
		this.statisticEntityFinder = statisticEntityFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return StatisticEntity.class;
	}

	protected String getModelClassName() {
		return StatisticEntity.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = statisticEntityPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = StatisticEntityLocalService.class)
	protected StatisticEntityLocalService statisticEntityLocalService;
	@BeanReference(type = StatisticEntityService.class)
	protected StatisticEntityService statisticEntityService;
	@BeanReference(type = StatisticEntityPersistence.class)
	protected StatisticEntityPersistence statisticEntityPersistence;
	@BeanReference(type = StatisticEntityFinder.class)
	protected StatisticEntityFinder statisticEntityFinder;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private StatisticEntityServiceClpInvoker _clpInvoker = new StatisticEntityServiceClpInvoker();
}