/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.portal_egov.portlet.landprice.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.portal_egov.portlet.landprice.model.LandLocation;
import com.portal_egov.portlet.landprice.model.LandLocationModel;
import com.portal_egov.portlet.landprice.model.LandLocationSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the LandLocation service. Represents a row in the &quot;LandLocation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.portal_egov.portlet.landprice.model.LandLocationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LandLocationImpl}.
 * </p>
 *
 * @author HungDX
 * @see LandLocationImpl
 * @see com.portal_egov.portlet.landprice.model.LandLocation
 * @see com.portal_egov.portlet.landprice.model.LandLocationModel
 * @generated
 */
@JSON(strict = true)
public class LandLocationModelImpl extends BaseModelImpl<LandLocation>
	implements LandLocationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a land location model instance should use the {@link com.portal_egov.portlet.landprice.model.LandLocation} interface instead.
	 */
	public static final String TABLE_NAME = "LandLocation";
	public static final Object[][] TABLE_COLUMNS = {
			{ "locationId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "parentLocationId", Types.BIGINT },
			{ "locationName", Types.VARCHAR },
			{ "locationInfo", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table LandLocation (locationId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,parentLocationId LONG,locationName VARCHAR(300) null,locationInfo VARCHAR(1000) null)";
	public static final String TABLE_SQL_DROP = "drop table LandLocation";
	public static final String ORDER_BY_JPQL = " ORDER BY landLocation.parentLocationId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY LandLocation.parentLocationId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.portal_egov.portlet.landprice.model.LandLocation"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.portal_egov.portlet.landprice.model.LandLocation"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.portal_egov.portlet.landprice.model.LandLocation"),
			true);
	public static long GROUPID_COLUMN_BITMASK = 1L;
	public static long PARENTLOCATIONID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LandLocation toModel(LandLocationSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LandLocation model = new LandLocationImpl();

		model.setLocationId(soapModel.getLocationId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setParentLocationId(soapModel.getParentLocationId());
		model.setLocationName(soapModel.getLocationName());
		model.setLocationInfo(soapModel.getLocationInfo());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LandLocation> toModels(LandLocationSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LandLocation> models = new ArrayList<LandLocation>(soapModels.length);

		for (LandLocationSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.portal_egov.portlet.landprice.model.LandLocation"));

	public LandLocationModelImpl() {
	}

	public long getPrimaryKey() {
		return _locationId;
	}

	public void setPrimaryKey(long primaryKey) {
		setLocationId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_locationId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return LandLocation.class;
	}

	public String getModelClassName() {
		return LandLocation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("locationId", getLocationId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("parentLocationId", getParentLocationId());
		attributes.put("locationName", getLocationName());
		attributes.put("locationInfo", getLocationInfo());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long locationId = (Long)attributes.get("locationId");

		if (locationId != null) {
			setLocationId(locationId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long parentLocationId = (Long)attributes.get("parentLocationId");

		if (parentLocationId != null) {
			setParentLocationId(parentLocationId);
		}

		String locationName = (String)attributes.get("locationName");

		if (locationName != null) {
			setLocationName(locationName);
		}

		String locationInfo = (String)attributes.get("locationInfo");

		if (locationInfo != null) {
			setLocationInfo(locationInfo);
		}
	}

	@JSON
	public long getLocationId() {
		return _locationId;
	}

	public void setLocationId(long locationId) {
		_locationId = locationId;
	}

	@JSON
	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	public long getParentLocationId() {
		return _parentLocationId;
	}

	public void setParentLocationId(long parentLocationId) {
		_columnBitmask = -1L;

		if (!_setOriginalParentLocationId) {
			_setOriginalParentLocationId = true;

			_originalParentLocationId = _parentLocationId;
		}

		_parentLocationId = parentLocationId;
	}

	public long getOriginalParentLocationId() {
		return _originalParentLocationId;
	}

	@JSON
	public String getLocationName() {
		if (_locationName == null) {
			return StringPool.BLANK;
		}
		else {
			return _locationName;
		}
	}

	public void setLocationName(String locationName) {
		_locationName = locationName;
	}

	@JSON
	public String getLocationInfo() {
		if (_locationInfo == null) {
			return StringPool.BLANK;
		}
		else {
			return _locationInfo;
		}
	}

	public void setLocationInfo(String locationInfo) {
		_locationInfo = locationInfo;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			LandLocation.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LandLocation toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (LandLocation)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		LandLocationImpl landLocationImpl = new LandLocationImpl();

		landLocationImpl.setLocationId(getLocationId());
		landLocationImpl.setCompanyId(getCompanyId());
		landLocationImpl.setGroupId(getGroupId());
		landLocationImpl.setUserId(getUserId());
		landLocationImpl.setUserName(getUserName());
		landLocationImpl.setCreateDate(getCreateDate());
		landLocationImpl.setModifiedDate(getModifiedDate());
		landLocationImpl.setParentLocationId(getParentLocationId());
		landLocationImpl.setLocationName(getLocationName());
		landLocationImpl.setLocationInfo(getLocationInfo());

		landLocationImpl.resetOriginalValues();

		return landLocationImpl;
	}

	public int compareTo(LandLocation landLocation) {
		int value = 0;

		if (getParentLocationId() < landLocation.getParentLocationId()) {
			value = -1;
		}
		else if (getParentLocationId() > landLocation.getParentLocationId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		LandLocation landLocation = null;

		try {
			landLocation = (LandLocation)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = landLocation.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		LandLocationModelImpl landLocationModelImpl = this;

		landLocationModelImpl._originalGroupId = landLocationModelImpl._groupId;

		landLocationModelImpl._setOriginalGroupId = false;

		landLocationModelImpl._originalParentLocationId = landLocationModelImpl._parentLocationId;

		landLocationModelImpl._setOriginalParentLocationId = false;

		landLocationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LandLocation> toCacheModel() {
		LandLocationCacheModel landLocationCacheModel = new LandLocationCacheModel();

		landLocationCacheModel.locationId = getLocationId();

		landLocationCacheModel.companyId = getCompanyId();

		landLocationCacheModel.groupId = getGroupId();

		landLocationCacheModel.userId = getUserId();

		landLocationCacheModel.userName = getUserName();

		String userName = landLocationCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			landLocationCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			landLocationCacheModel.createDate = createDate.getTime();
		}
		else {
			landLocationCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			landLocationCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			landLocationCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		landLocationCacheModel.parentLocationId = getParentLocationId();

		landLocationCacheModel.locationName = getLocationName();

		String locationName = landLocationCacheModel.locationName;

		if ((locationName != null) && (locationName.length() == 0)) {
			landLocationCacheModel.locationName = null;
		}

		landLocationCacheModel.locationInfo = getLocationInfo();

		String locationInfo = landLocationCacheModel.locationInfo;

		if ((locationInfo != null) && (locationInfo.length() == 0)) {
			landLocationCacheModel.locationInfo = null;
		}

		return landLocationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{locationId=");
		sb.append(getLocationId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", parentLocationId=");
		sb.append(getParentLocationId());
		sb.append(", locationName=");
		sb.append(getLocationName());
		sb.append(", locationInfo=");
		sb.append(getLocationInfo());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.portal_egov.portlet.landprice.model.LandLocation");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>locationId</column-name><column-value><![CDATA[");
		sb.append(getLocationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>parentLocationId</column-name><column-value><![CDATA[");
		sb.append(getParentLocationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>locationName</column-name><column-value><![CDATA[");
		sb.append(getLocationName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>locationInfo</column-name><column-value><![CDATA[");
		sb.append(getLocationInfo());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = LandLocation.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			LandLocation.class
		};
	private long _locationId;
	private long _companyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _parentLocationId;
	private long _originalParentLocationId;
	private boolean _setOriginalParentLocationId;
	private String _locationName;
	private String _locationInfo;
	private long _columnBitmask;
	private LandLocation _escapedModelProxy;
}