/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.portal_egov.portlet.conversation.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CO_Conversation service. Represents a row in the &quot;CO_Conversation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.portal_egov.portlet.conversation.model.impl.CO_ConversationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.portal_egov.portlet.conversation.model.impl.CO_ConversationImpl}.
 * </p>
 *
 * @author DucDVd
 * @see CO_Conversation
 * @see com.portal_egov.portlet.conversation.model.impl.CO_ConversationImpl
 * @see com.portal_egov.portlet.conversation.model.impl.CO_ConversationModelImpl
 * @generated
 */
public interface CO_ConversationModel extends BaseModel<CO_Conversation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a c o_ conversation model instance should use the {@link CO_Conversation} interface instead.
	 */

	/**
	 * Returns the primary key of this c o_ conversation.
	 *
	 * @return the primary key of this c o_ conversation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this c o_ conversation.
	 *
	 * @param primaryKey the primary key of this c o_ conversation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the conversation ID of this c o_ conversation.
	 *
	 * @return the conversation ID of this c o_ conversation
	 */
	public long getConversationId();

	/**
	 * Sets the conversation ID of this c o_ conversation.
	 *
	 * @param conversationId the conversation ID of this c o_ conversation
	 */
	public void setConversationId(long conversationId);

	/**
	 * Returns the company ID of this c o_ conversation.
	 *
	 * @return the company ID of this c o_ conversation
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this c o_ conversation.
	 *
	 * @param companyId the company ID of this c o_ conversation
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this c o_ conversation.
	 *
	 * @return the group ID of this c o_ conversation
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this c o_ conversation.
	 *
	 * @param groupId the group ID of this c o_ conversation
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this c o_ conversation.
	 *
	 * @return the user ID of this c o_ conversation
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this c o_ conversation.
	 *
	 * @param userId the user ID of this c o_ conversation
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this c o_ conversation.
	 *
	 * @return the user uuid of this c o_ conversation
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this c o_ conversation.
	 *
	 * @param userUuid the user uuid of this c o_ conversation
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the thread ID of this c o_ conversation.
	 *
	 * @return the thread ID of this c o_ conversation
	 */
	public long getThreadId();

	/**
	 * Sets the thread ID of this c o_ conversation.
	 *
	 * @param threadId the thread ID of this c o_ conversation
	 */
	public void setThreadId(long threadId);

	/**
	 * Returns the title of this c o_ conversation.
	 *
	 * @return the title of this c o_ conversation
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this c o_ conversation.
	 *
	 * @param title the title of this c o_ conversation
	 */
	public void setTitle(String title);

	/**
	 * Returns the ask user name of this c o_ conversation.
	 *
	 * @return the ask user name of this c o_ conversation
	 */
	@AutoEscape
	public String getAskUserName();

	/**
	 * Sets the ask user name of this c o_ conversation.
	 *
	 * @param askUserName the ask user name of this c o_ conversation
	 */
	public void setAskUserName(String askUserName);

	/**
	 * Returns the ask user info of this c o_ conversation.
	 *
	 * @return the ask user info of this c o_ conversation
	 */
	@AutoEscape
	public String getAskUserInfo();

	/**
	 * Sets the ask user info of this c o_ conversation.
	 *
	 * @param askUserInfo the ask user info of this c o_ conversation
	 */
	public void setAskUserInfo(String askUserInfo);

	/**
	 * Returns the ask content of this c o_ conversation.
	 *
	 * @return the ask content of this c o_ conversation
	 */
	@AutoEscape
	public String getAskContent();

	/**
	 * Sets the ask content of this c o_ conversation.
	 *
	 * @param askContent the ask content of this c o_ conversation
	 */
	public void setAskContent(String askContent);

	/**
	 * Returns the answer user name of this c o_ conversation.
	 *
	 * @return the answer user name of this c o_ conversation
	 */
	@AutoEscape
	public String getAnswerUserName();

	/**
	 * Sets the answer user name of this c o_ conversation.
	 *
	 * @param answerUserName the answer user name of this c o_ conversation
	 */
	public void setAnswerUserName(String answerUserName);

	/**
	 * Returns the answer user info of this c o_ conversation.
	 *
	 * @return the answer user info of this c o_ conversation
	 */
	@AutoEscape
	public String getAnswerUserInfo();

	/**
	 * Sets the answer user info of this c o_ conversation.
	 *
	 * @param answerUserInfo the answer user info of this c o_ conversation
	 */
	public void setAnswerUserInfo(String answerUserInfo);

	/**
	 * Returns the answer content of this c o_ conversation.
	 *
	 * @return the answer content of this c o_ conversation
	 */
	@AutoEscape
	public String getAnswerContent();

	/**
	 * Sets the answer content of this c o_ conversation.
	 *
	 * @param answerContent the answer content of this c o_ conversation
	 */
	public void setAnswerContent(String answerContent);

	/**
	 * Returns the ask date of this c o_ conversation.
	 *
	 * @return the ask date of this c o_ conversation
	 */
	public Date getAskDate();

	/**
	 * Sets the ask date of this c o_ conversation.
	 *
	 * @param askDate the ask date of this c o_ conversation
	 */
	public void setAskDate(Date askDate);

	/**
	 * Returns the answer date of this c o_ conversation.
	 *
	 * @return the answer date of this c o_ conversation
	 */
	public Date getAnswerDate();

	/**
	 * Sets the answer date of this c o_ conversation.
	 *
	 * @param answerDate the answer date of this c o_ conversation
	 */
	public void setAnswerDate(Date answerDate);

	/**
	 * Returns the create date of this c o_ conversation.
	 *
	 * @return the create date of this c o_ conversation
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this c o_ conversation.
	 *
	 * @param createDate the create date of this c o_ conversation
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this c o_ conversation.
	 *
	 * @return the modified date of this c o_ conversation
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this c o_ conversation.
	 *
	 * @param modifiedDate the modified date of this c o_ conversation
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this c o_ conversation.
	 *
	 * @return the status of this c o_ conversation
	 */
	public int getStatus();

	/**
	 * Sets the status of this c o_ conversation.
	 *
	 * @param status the status of this c o_ conversation
	 */
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this c o_ conversation.
	 *
	 * @return the status by user ID of this c o_ conversation
	 */
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this c o_ conversation.
	 *
	 * @param statusByUserId the status by user ID of this c o_ conversation
	 */
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this c o_ conversation.
	 *
	 * @return the status by user uuid of this c o_ conversation
	 * @throws SystemException if a system exception occurred
	 */
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this c o_ conversation.
	 *
	 * @param statusByUserUuid the status by user uuid of this c o_ conversation
	 */
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status date of this c o_ conversation.
	 *
	 * @return the status date of this c o_ conversation
	 */
	public Date getStatusDate();

	/**
	 * Sets the status date of this c o_ conversation.
	 *
	 * @param statusDate the status date of this c o_ conversation
	 */
	public void setStatusDate(Date statusDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(CO_Conversation co_Conversation);

	public int hashCode();

	public CacheModel<CO_Conversation> toCacheModel();

	public CO_Conversation toEscapedModel();

	public String toString();

	public String toXmlString();
}