/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.portal_egov.portlet.conversation.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CO_Thread service. Represents a row in the &quot;CO_Thread&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.portal_egov.portlet.conversation.model.impl.CO_ThreadModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.portal_egov.portlet.conversation.model.impl.CO_ThreadImpl}.
 * </p>
 *
 * @author DucDVd
 * @see CO_Thread
 * @see com.portal_egov.portlet.conversation.model.impl.CO_ThreadImpl
 * @see com.portal_egov.portlet.conversation.model.impl.CO_ThreadModelImpl
 * @generated
 */
public interface CO_ThreadModel extends BaseModel<CO_Thread> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a c o_ thread model instance should use the {@link CO_Thread} interface instead.
	 */

	/**
	 * Returns the primary key of this c o_ thread.
	 *
	 * @return the primary key of this c o_ thread
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this c o_ thread.
	 *
	 * @param primaryKey the primary key of this c o_ thread
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the thread ID of this c o_ thread.
	 *
	 * @return the thread ID of this c o_ thread
	 */
	public long getThreadId();

	/**
	 * Sets the thread ID of this c o_ thread.
	 *
	 * @param threadId the thread ID of this c o_ thread
	 */
	public void setThreadId(long threadId);

	/**
	 * Returns the company ID of this c o_ thread.
	 *
	 * @return the company ID of this c o_ thread
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this c o_ thread.
	 *
	 * @param companyId the company ID of this c o_ thread
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this c o_ thread.
	 *
	 * @return the group ID of this c o_ thread
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this c o_ thread.
	 *
	 * @param groupId the group ID of this c o_ thread
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this c o_ thread.
	 *
	 * @return the user ID of this c o_ thread
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this c o_ thread.
	 *
	 * @param userId the user ID of this c o_ thread
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this c o_ thread.
	 *
	 * @return the user uuid of this c o_ thread
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this c o_ thread.
	 *
	 * @param userUuid the user uuid of this c o_ thread
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the parent thread ID of this c o_ thread.
	 *
	 * @return the parent thread ID of this c o_ thread
	 */
	public long getParentThreadId();

	/**
	 * Sets the parent thread ID of this c o_ thread.
	 *
	 * @param parentThreadId the parent thread ID of this c o_ thread
	 */
	public void setParentThreadId(long parentThreadId);

	/**
	 * Returns the category ID of this c o_ thread.
	 *
	 * @return the category ID of this c o_ thread
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this c o_ thread.
	 *
	 * @param categoryId the category ID of this c o_ thread
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the thread name of this c o_ thread.
	 *
	 * @return the thread name of this c o_ thread
	 */
	@AutoEscape
	public String getThreadName();

	/**
	 * Sets the thread name of this c o_ thread.
	 *
	 * @param threadName the thread name of this c o_ thread
	 */
	public void setThreadName(String threadName);

	/**
	 * Returns the department name of this c o_ thread.
	 *
	 * @return the department name of this c o_ thread
	 */
	@AutoEscape
	public String getDepartmentName();

	/**
	 * Sets the department name of this c o_ thread.
	 *
	 * @param departmentName the department name of this c o_ thread
	 */
	public void setDepartmentName(String departmentName);

	/**
	 * Returns the participants of this c o_ thread.
	 *
	 * @return the participants of this c o_ thread
	 */
	@AutoEscape
	public String getParticipants();

	/**
	 * Sets the participants of this c o_ thread.
	 *
	 * @param participants the participants of this c o_ thread
	 */
	public void setParticipants(String participants);

	/**
	 * Returns the thread desc of this c o_ thread.
	 *
	 * @return the thread desc of this c o_ thread
	 */
	@AutoEscape
	public String getThreadDesc();

	/**
	 * Sets the thread desc of this c o_ thread.
	 *
	 * @param threadDesc the thread desc of this c o_ thread
	 */
	public void setThreadDesc(String threadDesc);

	/**
	 * Returns the start date of this c o_ thread.
	 *
	 * @return the start date of this c o_ thread
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this c o_ thread.
	 *
	 * @param startDate the start date of this c o_ thread
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this c o_ thread.
	 *
	 * @return the end date of this c o_ thread
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this c o_ thread.
	 *
	 * @param endDate the end date of this c o_ thread
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the create date of this c o_ thread.
	 *
	 * @return the create date of this c o_ thread
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this c o_ thread.
	 *
	 * @param createDate the create date of this c o_ thread
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this c o_ thread.
	 *
	 * @return the modified date of this c o_ thread
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this c o_ thread.
	 *
	 * @param modifiedDate the modified date of this c o_ thread
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the view count of this c o_ thread.
	 *
	 * @return the view count of this c o_ thread
	 */
	public int getViewCount();

	/**
	 * Sets the view count of this c o_ thread.
	 *
	 * @param viewCount the view count of this c o_ thread
	 */
	public void setViewCount(int viewCount);

	/**
	 * Returns the conversation count of this c o_ thread.
	 *
	 * @return the conversation count of this c o_ thread
	 */
	public int getConversationCount();

	/**
	 * Sets the conversation count of this c o_ thread.
	 *
	 * @param conversationCount the conversation count of this c o_ thread
	 */
	public void setConversationCount(int conversationCount);

	/**
	 * Returns the status of this c o_ thread.
	 *
	 * @return the status of this c o_ thread
	 */
	public int getStatus();

	/**
	 * Sets the status of this c o_ thread.
	 *
	 * @param status the status of this c o_ thread
	 */
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this c o_ thread.
	 *
	 * @return the status by user ID of this c o_ thread
	 */
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this c o_ thread.
	 *
	 * @param statusByUserId the status by user ID of this c o_ thread
	 */
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this c o_ thread.
	 *
	 * @return the status by user uuid of this c o_ thread
	 * @throws SystemException if a system exception occurred
	 */
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this c o_ thread.
	 *
	 * @param statusByUserUuid the status by user uuid of this c o_ thread
	 */
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status date of this c o_ thread.
	 *
	 * @return the status date of this c o_ thread
	 */
	public Date getStatusDate();

	/**
	 * Sets the status date of this c o_ thread.
	 *
	 * @param statusDate the status date of this c o_ thread
	 */
	public void setStatusDate(Date statusDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(CO_Thread co_Thread);

	public int hashCode();

	public CacheModel<CO_Thread> toCacheModel();

	public CO_Thread toEscapedModel();

	public String toString();

	public String toXmlString();
}