/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.portal_egov.portlet.citymaps.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.portal_egov.portlet.citymaps.model.CityMap;
import com.portal_egov.portlet.citymaps.service.CityMapLocalService;
import com.portal_egov.portlet.citymaps.service.CityMapService;
import com.portal_egov.portlet.citymaps.service.CityMapTypeLocalService;
import com.portal_egov.portlet.citymaps.service.CityMapTypeService;
import com.portal_egov.portlet.citymaps.service.persistence.CityMapFinder;
import com.portal_egov.portlet.citymaps.service.persistence.CityMapPersistence;
import com.portal_egov.portlet.citymaps.service.persistence.CityMapTypePersistence;

import javax.sql.DataSource;

/**
 * The base implementation of the city map remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.portal_egov.portlet.citymaps.service.impl.CityMapServiceImpl}.
 * </p>
 *
 * @author HungDX
 * @see com.portal_egov.portlet.citymaps.service.impl.CityMapServiceImpl
 * @see com.portal_egov.portlet.citymaps.service.CityMapServiceUtil
 * @generated
 */
public abstract class CityMapServiceBaseImpl extends BaseServiceImpl
	implements CityMapService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.portal_egov.portlet.citymaps.service.CityMapServiceUtil} to access the city map remote service.
	 */

	/**
	 * Returns the city map local service.
	 *
	 * @return the city map local service
	 */
	public CityMapLocalService getCityMapLocalService() {
		return cityMapLocalService;
	}

	/**
	 * Sets the city map local service.
	 *
	 * @param cityMapLocalService the city map local service
	 */
	public void setCityMapLocalService(CityMapLocalService cityMapLocalService) {
		this.cityMapLocalService = cityMapLocalService;
	}

	/**
	 * Returns the city map remote service.
	 *
	 * @return the city map remote service
	 */
	public CityMapService getCityMapService() {
		return cityMapService;
	}

	/**
	 * Sets the city map remote service.
	 *
	 * @param cityMapService the city map remote service
	 */
	public void setCityMapService(CityMapService cityMapService) {
		this.cityMapService = cityMapService;
	}

	/**
	 * Returns the city map persistence.
	 *
	 * @return the city map persistence
	 */
	public CityMapPersistence getCityMapPersistence() {
		return cityMapPersistence;
	}

	/**
	 * Sets the city map persistence.
	 *
	 * @param cityMapPersistence the city map persistence
	 */
	public void setCityMapPersistence(CityMapPersistence cityMapPersistence) {
		this.cityMapPersistence = cityMapPersistence;
	}

	/**
	 * Returns the city map finder.
	 *
	 * @return the city map finder
	 */
	public CityMapFinder getCityMapFinder() {
		return cityMapFinder;
	}

	/**
	 * Sets the city map finder.
	 *
	 * @param cityMapFinder the city map finder
	 */
	public void setCityMapFinder(CityMapFinder cityMapFinder) {
		this.cityMapFinder = cityMapFinder;
	}

	/**
	 * Returns the city map type local service.
	 *
	 * @return the city map type local service
	 */
	public CityMapTypeLocalService getCityMapTypeLocalService() {
		return cityMapTypeLocalService;
	}

	/**
	 * Sets the city map type local service.
	 *
	 * @param cityMapTypeLocalService the city map type local service
	 */
	public void setCityMapTypeLocalService(
		CityMapTypeLocalService cityMapTypeLocalService) {
		this.cityMapTypeLocalService = cityMapTypeLocalService;
	}

	/**
	 * Returns the city map type remote service.
	 *
	 * @return the city map type remote service
	 */
	public CityMapTypeService getCityMapTypeService() {
		return cityMapTypeService;
	}

	/**
	 * Sets the city map type remote service.
	 *
	 * @param cityMapTypeService the city map type remote service
	 */
	public void setCityMapTypeService(CityMapTypeService cityMapTypeService) {
		this.cityMapTypeService = cityMapTypeService;
	}

	/**
	 * Returns the city map type persistence.
	 *
	 * @return the city map type persistence
	 */
	public CityMapTypePersistence getCityMapTypePersistence() {
		return cityMapTypePersistence;
	}

	/**
	 * Sets the city map type persistence.
	 *
	 * @param cityMapTypePersistence the city map type persistence
	 */
	public void setCityMapTypePersistence(
		CityMapTypePersistence cityMapTypePersistence) {
		this.cityMapTypePersistence = cityMapTypePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return CityMap.class;
	}

	protected String getModelClassName() {
		return CityMap.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = cityMapPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = CityMapLocalService.class)
	protected CityMapLocalService cityMapLocalService;
	@BeanReference(type = CityMapService.class)
	protected CityMapService cityMapService;
	@BeanReference(type = CityMapPersistence.class)
	protected CityMapPersistence cityMapPersistence;
	@BeanReference(type = CityMapFinder.class)
	protected CityMapFinder cityMapFinder;
	@BeanReference(type = CityMapTypeLocalService.class)
	protected CityMapTypeLocalService cityMapTypeLocalService;
	@BeanReference(type = CityMapTypeService.class)
	protected CityMapTypeService cityMapTypeService;
	@BeanReference(type = CityMapTypePersistence.class)
	protected CityMapTypePersistence cityMapTypePersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private CityMapServiceClpInvoker _clpInvoker = new CityMapServiceClpInvoker();
}