/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bkav.portal.portlet.autoupdate.service.base;

import com.bkav.portal.portlet.autoupdate.model.UpdatePlugins;
import com.bkav.portal.portlet.autoupdate.service.UpdatePluginsLocalService;
import com.bkav.portal.portlet.autoupdate.service.UpdatePluginsService;
import com.bkav.portal.portlet.autoupdate.service.persistence.UpdatePluginsPersistence;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the update plugins local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.bkav.portal.portlet.autoupdate.service.impl.UpdatePluginsLocalServiceImpl}.
 * </p>
 *
 * @author anhbdb
 * @see com.bkav.portal.portlet.autoupdate.service.impl.UpdatePluginsLocalServiceImpl
 * @see com.bkav.portal.portlet.autoupdate.service.UpdatePluginsLocalServiceUtil
 * @generated
 */
public abstract class UpdatePluginsLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements UpdatePluginsLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.bkav.portal.portlet.autoupdate.service.UpdatePluginsLocalServiceUtil} to access the update plugins local service.
	 */

	/**
	 * Adds the update plugins to the database. Also notifies the appropriate model listeners.
	 *
	 * @param updatePlugins the update plugins
	 * @return the update plugins that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public UpdatePlugins addUpdatePlugins(UpdatePlugins updatePlugins)
		throws SystemException {
		updatePlugins.setNew(true);

		return updatePluginsPersistence.update(updatePlugins, false);
	}

	/**
	 * Creates a new update plugins with the primary key. Does not add the update plugins to the database.
	 *
	 * @param pluginId the primary key for the new update plugins
	 * @return the new update plugins
	 */
	public UpdatePlugins createUpdatePlugins(long pluginId) {
		return updatePluginsPersistence.create(pluginId);
	}

	/**
	 * Deletes the update plugins with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param pluginId the primary key of the update plugins
	 * @return the update plugins that was removed
	 * @throws PortalException if a update plugins with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public UpdatePlugins deleteUpdatePlugins(long pluginId)
		throws PortalException, SystemException {
		return updatePluginsPersistence.remove(pluginId);
	}

	/**
	 * Deletes the update plugins from the database. Also notifies the appropriate model listeners.
	 *
	 * @param updatePlugins the update plugins
	 * @return the update plugins that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public UpdatePlugins deleteUpdatePlugins(UpdatePlugins updatePlugins)
		throws SystemException {
		return updatePluginsPersistence.remove(updatePlugins);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(UpdatePlugins.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return updatePluginsPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return updatePluginsPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return updatePluginsPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return updatePluginsPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public UpdatePlugins fetchUpdatePlugins(long pluginId)
		throws SystemException {
		return updatePluginsPersistence.fetchByPrimaryKey(pluginId);
	}

	/**
	 * Returns the update plugins with the primary key.
	 *
	 * @param pluginId the primary key of the update plugins
	 * @return the update plugins
	 * @throws PortalException if a update plugins with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public UpdatePlugins getUpdatePlugins(long pluginId)
		throws PortalException, SystemException {
		return updatePluginsPersistence.findByPrimaryKey(pluginId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return updatePluginsPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the update pluginses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of update pluginses
	 * @param end the upper bound of the range of update pluginses (not inclusive)
	 * @return the range of update pluginses
	 * @throws SystemException if a system exception occurred
	 */
	public List<UpdatePlugins> getUpdatePluginses(int start, int end)
		throws SystemException {
		return updatePluginsPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of update pluginses.
	 *
	 * @return the number of update pluginses
	 * @throws SystemException if a system exception occurred
	 */
	public int getUpdatePluginsesCount() throws SystemException {
		return updatePluginsPersistence.countAll();
	}

	/**
	 * Updates the update plugins in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param updatePlugins the update plugins
	 * @return the update plugins that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public UpdatePlugins updateUpdatePlugins(UpdatePlugins updatePlugins)
		throws SystemException {
		return updateUpdatePlugins(updatePlugins, true);
	}

	/**
	 * Updates the update plugins in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param updatePlugins the update plugins
	 * @param merge whether to merge the update plugins with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the update plugins that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public UpdatePlugins updateUpdatePlugins(UpdatePlugins updatePlugins,
		boolean merge) throws SystemException {
		updatePlugins.setNew(false);

		return updatePluginsPersistence.update(updatePlugins, merge);
	}

	/**
	 * Returns the update plugins local service.
	 *
	 * @return the update plugins local service
	 */
	public UpdatePluginsLocalService getUpdatePluginsLocalService() {
		return updatePluginsLocalService;
	}

	/**
	 * Sets the update plugins local service.
	 *
	 * @param updatePluginsLocalService the update plugins local service
	 */
	public void setUpdatePluginsLocalService(
		UpdatePluginsLocalService updatePluginsLocalService) {
		this.updatePluginsLocalService = updatePluginsLocalService;
	}

	/**
	 * Returns the update plugins remote service.
	 *
	 * @return the update plugins remote service
	 */
	public UpdatePluginsService getUpdatePluginsService() {
		return updatePluginsService;
	}

	/**
	 * Sets the update plugins remote service.
	 *
	 * @param updatePluginsService the update plugins remote service
	 */
	public void setUpdatePluginsService(
		UpdatePluginsService updatePluginsService) {
		this.updatePluginsService = updatePluginsService;
	}

	/**
	 * Returns the update plugins persistence.
	 *
	 * @return the update plugins persistence
	 */
	public UpdatePluginsPersistence getUpdatePluginsPersistence() {
		return updatePluginsPersistence;
	}

	/**
	 * Sets the update plugins persistence.
	 *
	 * @param updatePluginsPersistence the update plugins persistence
	 */
	public void setUpdatePluginsPersistence(
		UpdatePluginsPersistence updatePluginsPersistence) {
		this.updatePluginsPersistence = updatePluginsPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.bkav.portal.portlet.autoupdate.model.UpdatePlugins",
			updatePluginsLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.bkav.portal.portlet.autoupdate.model.UpdatePlugins");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return UpdatePlugins.class;
	}

	protected String getModelClassName() {
		return UpdatePlugins.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = updatePluginsPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = UpdatePluginsLocalService.class)
	protected UpdatePluginsLocalService updatePluginsLocalService;
	@BeanReference(type = UpdatePluginsService.class)
	protected UpdatePluginsService updatePluginsService;
	@BeanReference(type = UpdatePluginsPersistence.class)
	protected UpdatePluginsPersistence updatePluginsPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private UpdatePluginsLocalServiceClpInvoker _clpInvoker = new UpdatePluginsLocalServiceClpInvoker();
}