/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bkav.portal.portlet.audioplayer.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the AlbumAudioMap service. Represents a row in the &quot;AudioPlayer_AlbumAudioMap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bkav.portal.portlet.audioplayer.model.impl.AlbumAudioMapModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bkav.portal.portlet.audioplayer.model.impl.AlbumAudioMapImpl}.
 * </p>
 *
 * @author anhbdb
 * @see AlbumAudioMap
 * @see com.bkav.portal.portlet.audioplayer.model.impl.AlbumAudioMapImpl
 * @see com.bkav.portal.portlet.audioplayer.model.impl.AlbumAudioMapModelImpl
 * @generated
 */
public interface AlbumAudioMapModel extends BaseModel<AlbumAudioMap> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a album audio map model instance should use the {@link AlbumAudioMap} interface instead.
	 */

	/**
	 * Returns the primary key of this album audio map.
	 *
	 * @return the primary key of this album audio map
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this album audio map.
	 *
	 * @param primaryKey the primary key of this album audio map
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the map ID of this album audio map.
	 *
	 * @return the map ID of this album audio map
	 */
	public long getMapId();

	/**
	 * Sets the map ID of this album audio map.
	 *
	 * @param mapId the map ID of this album audio map
	 */
	public void setMapId(long mapId);

	/**
	 * Returns the album ID of this album audio map.
	 *
	 * @return the album ID of this album audio map
	 */
	public long getAlbumId();

	/**
	 * Sets the album ID of this album audio map.
	 *
	 * @param albumId the album ID of this album audio map
	 */
	public void setAlbumId(long albumId);

	/**
	 * Returns the audio ID of this album audio map.
	 *
	 * @return the audio ID of this album audio map
	 */
	public long getAudioId();

	/**
	 * Sets the audio ID of this album audio map.
	 *
	 * @param audioId the audio ID of this album audio map
	 */
	public void setAudioId(long audioId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AlbumAudioMap albumAudioMap);

	public int hashCode();

	public CacheModel<AlbumAudioMap> toCacheModel();

	public AlbumAudioMap toEscapedModel();

	public String toString();

	public String toXmlString();
}