/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bkav.portal.portlet.audioplayer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AudioAlbum service. Represents a row in the &quot;AudioPlayer_AudioAlbum&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bkav.portal.portlet.audioplayer.model.impl.AudioAlbumModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bkav.portal.portlet.audioplayer.model.impl.AudioAlbumImpl}.
 * </p>
 *
 * @author anhbdb
 * @see AudioAlbum
 * @see com.bkav.portal.portlet.audioplayer.model.impl.AudioAlbumImpl
 * @see com.bkav.portal.portlet.audioplayer.model.impl.AudioAlbumModelImpl
 * @generated
 */
public interface AudioAlbumModel extends BaseModel<AudioAlbum> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a audio album model instance should use the {@link AudioAlbum} interface instead.
	 */

	/**
	 * Returns the primary key of this audio album.
	 *
	 * @return the primary key of this audio album
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this audio album.
	 *
	 * @param primaryKey the primary key of this audio album
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the album ID of this audio album.
	 *
	 * @return the album ID of this audio album
	 */
	public long getAlbumId();

	/**
	 * Sets the album ID of this audio album.
	 *
	 * @param albumId the album ID of this audio album
	 */
	public void setAlbumId(long albumId);

	/**
	 * Returns the album name of this audio album.
	 *
	 * @return the album name of this audio album
	 */
	@AutoEscape
	public String getAlbumName();

	/**
	 * Sets the album name of this audio album.
	 *
	 * @param albumName the album name of this audio album
	 */
	public void setAlbumName(String albumName);

	/**
	 * Returns the album info of this audio album.
	 *
	 * @return the album info of this audio album
	 */
	@AutoEscape
	public String getAlbumInfo();

	/**
	 * Sets the album info of this audio album.
	 *
	 * @param albumInfo the album info of this audio album
	 */
	public void setAlbumInfo(String albumInfo);

	/**
	 * Returns the album cover ID of this audio album.
	 *
	 * @return the album cover ID of this audio album
	 */
	public long getAlbumCoverId();

	/**
	 * Sets the album cover ID of this audio album.
	 *
	 * @param albumCoverId the album cover ID of this audio album
	 */
	public void setAlbumCoverId(long albumCoverId);

	/**
	 * Returns the create date of this audio album.
	 *
	 * @return the create date of this audio album
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this audio album.
	 *
	 * @param createDate the create date of this audio album
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modify date of this audio album.
	 *
	 * @return the modify date of this audio album
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this audio album.
	 *
	 * @param modifyDate the modify date of this audio album
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the group ID of this audio album.
	 *
	 * @return the group ID of this audio album
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this audio album.
	 *
	 * @param groupId the group ID of this audio album
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this audio album.
	 *
	 * @return the company ID of this audio album
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this audio album.
	 *
	 * @param companyId the company ID of this audio album
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this audio album.
	 *
	 * @return the user ID of this audio album
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this audio album.
	 *
	 * @param userId the user ID of this audio album
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this audio album.
	 *
	 * @return the user uuid of this audio album
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this audio album.
	 *
	 * @param userUuid the user uuid of this audio album
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this audio album.
	 *
	 * @return the user name of this audio album
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this audio album.
	 *
	 * @param userName the user name of this audio album
	 */
	public void setUserName(String userName);

	/**
	 * Returns the view counter of this audio album.
	 *
	 * @return the view counter of this audio album
	 */
	public long getViewCounter();

	/**
	 * Sets the view counter of this audio album.
	 *
	 * @param viewCounter the view counter of this audio album
	 */
	public void setViewCounter(long viewCounter);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AudioAlbum audioAlbum);

	public int hashCode();

	public CacheModel<AudioAlbum> toCacheModel();

	public AudioAlbum toEscapedModel();

	public String toString();

	public String toXmlString();
}