/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.portal_egov.portlet.tourism_map.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TourismMapMarker service. Represents a row in the &quot;TourismMapMarker&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.portal_egov.portlet.tourism_map.model.impl.TourismMapMarkerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.portal_egov.portlet.tourism_map.model.impl.TourismMapMarkerImpl}.
 * </p>
 *
 * @author HungDX
 * @see TourismMapMarker
 * @see com.portal_egov.portlet.tourism_map.model.impl.TourismMapMarkerImpl
 * @see com.portal_egov.portlet.tourism_map.model.impl.TourismMapMarkerModelImpl
 * @generated
 */
public interface TourismMapMarkerModel extends BaseModel<TourismMapMarker>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tourism map marker model instance should use the {@link TourismMapMarker} interface instead.
	 */

	/**
	 * Returns the primary key of this tourism map marker.
	 *
	 * @return the primary key of this tourism map marker
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tourism map marker.
	 *
	 * @param primaryKey the primary key of this tourism map marker
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the marker ID of this tourism map marker.
	 *
	 * @return the marker ID of this tourism map marker
	 */
	public long getMarkerId();

	/**
	 * Sets the marker ID of this tourism map marker.
	 *
	 * @param markerId the marker ID of this tourism map marker
	 */
	public void setMarkerId(long markerId);

	/**
	 * Returns the company ID of this tourism map marker.
	 *
	 * @return the company ID of this tourism map marker
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this tourism map marker.
	 *
	 * @param companyId the company ID of this tourism map marker
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this tourism map marker.
	 *
	 * @return the group ID of this tourism map marker
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this tourism map marker.
	 *
	 * @param groupId the group ID of this tourism map marker
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this tourism map marker.
	 *
	 * @return the user ID of this tourism map marker
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this tourism map marker.
	 *
	 * @param userId the user ID of this tourism map marker
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this tourism map marker.
	 *
	 * @return the user uuid of this tourism map marker
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this tourism map marker.
	 *
	 * @param userUuid the user uuid of this tourism map marker
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this tourism map marker.
	 *
	 * @return the user name of this tourism map marker
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this tourism map marker.
	 *
	 * @param userName the user name of this tourism map marker
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this tourism map marker.
	 *
	 * @return the create date of this tourism map marker
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this tourism map marker.
	 *
	 * @param createDate the create date of this tourism map marker
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this tourism map marker.
	 *
	 * @return the modified date of this tourism map marker
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this tourism map marker.
	 *
	 * @param modifiedDate the modified date of this tourism map marker
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the marker group ID of this tourism map marker.
	 *
	 * @return the marker group ID of this tourism map marker
	 */
	public long getMarkerGroupId();

	/**
	 * Sets the marker group ID of this tourism map marker.
	 *
	 * @param markerGroupId the marker group ID of this tourism map marker
	 */
	public void setMarkerGroupId(long markerGroupId);

	/**
	 * Returns the marker title of this tourism map marker.
	 *
	 * @return the marker title of this tourism map marker
	 */
	@AutoEscape
	public String getMarkerTitle();

	/**
	 * Sets the marker title of this tourism map marker.
	 *
	 * @param markerTitle the marker title of this tourism map marker
	 */
	public void setMarkerTitle(String markerTitle);

	/**
	 * Returns the marker info of this tourism map marker.
	 *
	 * @return the marker info of this tourism map marker
	 */
	@AutoEscape
	public String getMarkerInfo();

	/**
	 * Sets the marker info of this tourism map marker.
	 *
	 * @param markerInfo the marker info of this tourism map marker
	 */
	public void setMarkerInfo(String markerInfo);

	/**
	 * Returns the marker address of this tourism map marker.
	 *
	 * @return the marker address of this tourism map marker
	 */
	@AutoEscape
	public String getMarkerAddress();

	/**
	 * Sets the marker address of this tourism map marker.
	 *
	 * @param markerAddress the marker address of this tourism map marker
	 */
	public void setMarkerAddress(String markerAddress);

	/**
	 * Returns the marker image ID of this tourism map marker.
	 *
	 * @return the marker image ID of this tourism map marker
	 */
	public long getMarkerImageId();

	/**
	 * Sets the marker image ID of this tourism map marker.
	 *
	 * @param markerImageId the marker image ID of this tourism map marker
	 */
	public void setMarkerImageId(long markerImageId);

	/**
	 * Returns the marker longitude of this tourism map marker.
	 *
	 * @return the marker longitude of this tourism map marker
	 */
	@AutoEscape
	public String getMarkerLongitude();

	/**
	 * Sets the marker longitude of this tourism map marker.
	 *
	 * @param markerLongitude the marker longitude of this tourism map marker
	 */
	public void setMarkerLongitude(String markerLongitude);

	/**
	 * Returns the marker latitude of this tourism map marker.
	 *
	 * @return the marker latitude of this tourism map marker
	 */
	@AutoEscape
	public String getMarkerLatitude();

	/**
	 * Sets the marker latitude of this tourism map marker.
	 *
	 * @param markerLatitude the marker latitude of this tourism map marker
	 */
	public void setMarkerLatitude(String markerLatitude);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TourismMapMarker tourismMapMarker);

	public int hashCode();

	public CacheModel<TourismMapMarker> toCacheModel();

	public TourismMapMarker toEscapedModel();

	public String toString();

	public String toXmlString();
}