/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.portal_egov.portlet.tourism_map.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TourismMapMarkerGroup service. Represents a row in the &quot;TourismMapMarkerGroup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.portal_egov.portlet.tourism_map.model.impl.TourismMapMarkerGroupModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.portal_egov.portlet.tourism_map.model.impl.TourismMapMarkerGroupImpl}.
 * </p>
 *
 * @author HungDX
 * @see TourismMapMarkerGroup
 * @see com.portal_egov.portlet.tourism_map.model.impl.TourismMapMarkerGroupImpl
 * @see com.portal_egov.portlet.tourism_map.model.impl.TourismMapMarkerGroupModelImpl
 * @generated
 */
public interface TourismMapMarkerGroupModel extends BaseModel<TourismMapMarkerGroup>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tourism map marker group model instance should use the {@link TourismMapMarkerGroup} interface instead.
	 */

	/**
	 * Returns the primary key of this tourism map marker group.
	 *
	 * @return the primary key of this tourism map marker group
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tourism map marker group.
	 *
	 * @param primaryKey the primary key of this tourism map marker group
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the marker group ID of this tourism map marker group.
	 *
	 * @return the marker group ID of this tourism map marker group
	 */
	public long getMarkerGroupId();

	/**
	 * Sets the marker group ID of this tourism map marker group.
	 *
	 * @param markerGroupId the marker group ID of this tourism map marker group
	 */
	public void setMarkerGroupId(long markerGroupId);

	/**
	 * Returns the company ID of this tourism map marker group.
	 *
	 * @return the company ID of this tourism map marker group
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this tourism map marker group.
	 *
	 * @param companyId the company ID of this tourism map marker group
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this tourism map marker group.
	 *
	 * @return the group ID of this tourism map marker group
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this tourism map marker group.
	 *
	 * @param groupId the group ID of this tourism map marker group
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this tourism map marker group.
	 *
	 * @return the user ID of this tourism map marker group
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this tourism map marker group.
	 *
	 * @param userId the user ID of this tourism map marker group
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this tourism map marker group.
	 *
	 * @return the user uuid of this tourism map marker group
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this tourism map marker group.
	 *
	 * @param userUuid the user uuid of this tourism map marker group
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this tourism map marker group.
	 *
	 * @return the user name of this tourism map marker group
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this tourism map marker group.
	 *
	 * @param userName the user name of this tourism map marker group
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this tourism map marker group.
	 *
	 * @return the create date of this tourism map marker group
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this tourism map marker group.
	 *
	 * @param createDate the create date of this tourism map marker group
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this tourism map marker group.
	 *
	 * @return the modified date of this tourism map marker group
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this tourism map marker group.
	 *
	 * @param modifiedDate the modified date of this tourism map marker group
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the marker group name of this tourism map marker group.
	 *
	 * @return the marker group name of this tourism map marker group
	 */
	@AutoEscape
	public String getMarkerGroupName();

	/**
	 * Sets the marker group name of this tourism map marker group.
	 *
	 * @param markerGroupName the marker group name of this tourism map marker group
	 */
	public void setMarkerGroupName(String markerGroupName);

	/**
	 * Returns the marker group info of this tourism map marker group.
	 *
	 * @return the marker group info of this tourism map marker group
	 */
	@AutoEscape
	public String getMarkerGroupInfo();

	/**
	 * Sets the marker group info of this tourism map marker group.
	 *
	 * @param markerGroupInfo the marker group info of this tourism map marker group
	 */
	public void setMarkerGroupInfo(String markerGroupInfo);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TourismMapMarkerGroup tourismMapMarkerGroup);

	public int hashCode();

	public CacheModel<TourismMapMarkerGroup> toCacheModel();

	public TourismMapMarkerGroup toEscapedModel();

	public String toString();

	public String toXmlString();
}