/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bkav.portal.portlet.contentsharing.model.impl;

import com.bkav.portal.portlet.contentsharing.model.ContentSharing;
import com.bkav.portal.portlet.contentsharing.model.ContentSharingModel;
import com.bkav.portal.portlet.contentsharing.model.ContentSharingSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ContentSharing service. Represents a row in the &quot;ContentSharing&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.bkav.portal.portlet.contentsharing.model.ContentSharingModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContentSharingImpl}.
 * </p>
 *
 * @author anhbdb
 * @see ContentSharingImpl
 * @see com.bkav.portal.portlet.contentsharing.model.ContentSharing
 * @see com.bkav.portal.portlet.contentsharing.model.ContentSharingModel
 * @generated
 */
@JSON(strict = true)
public class ContentSharingModelImpl extends BaseModelImpl<ContentSharing>
	implements ContentSharingModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a content sharing model instance should use the {@link com.bkav.portal.portlet.contentsharing.model.ContentSharing} interface instead.
	 */
	public static final String TABLE_NAME = "ContentSharing";
	public static final Object[][] TABLE_COLUMNS = {
			{ "contentId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "contentSharing", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table ContentSharing (contentId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,contentSharing VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table ContentSharing";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.bkav.portal.portlet.contentsharing.model.ContentSharing"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.bkav.portal.portlet.contentsharing.model.ContentSharing"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.bkav.portal.portlet.contentsharing.model.ContentSharing"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ContentSharing toModel(ContentSharingSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ContentSharing model = new ContentSharingImpl();

		model.setContentId(soapModel.getContentId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setContentSharing(soapModel.getContentSharing());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ContentSharing> toModels(ContentSharingSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ContentSharing> models = new ArrayList<ContentSharing>(soapModels.length);

		for (ContentSharingSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.bkav.portal.portlet.contentsharing.model.ContentSharing"));

	public ContentSharingModelImpl() {
	}

	public long getPrimaryKey() {
		return _contentId;
	}

	public void setPrimaryKey(long primaryKey) {
		setContentId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_contentId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return ContentSharing.class;
	}

	public String getModelClassName() {
		return ContentSharing.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("contentId", getContentId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("contentSharing", getContentSharing());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long contentId = (Long)attributes.get("contentId");

		if (contentId != null) {
			setContentId(contentId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String contentSharing = (String)attributes.get("contentSharing");

		if (contentSharing != null) {
			setContentSharing(contentSharing);
		}
	}

	@JSON
	public long getContentId() {
		return _contentId;
	}

	public void setContentId(long contentId) {
		_contentId = contentId;
	}

	@JSON
	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	public String getContentSharing() {
		if (_contentSharing == null) {
			return StringPool.BLANK;
		}
		else {
			return _contentSharing;
		}
	}

	public void setContentSharing(String contentSharing) {
		_contentSharing = contentSharing;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ContentSharing.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ContentSharing toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (ContentSharing)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		ContentSharingImpl contentSharingImpl = new ContentSharingImpl();

		contentSharingImpl.setContentId(getContentId());
		contentSharingImpl.setCompanyId(getCompanyId());
		contentSharingImpl.setGroupId(getGroupId());
		contentSharingImpl.setUserId(getUserId());
		contentSharingImpl.setContentSharing(getContentSharing());

		contentSharingImpl.resetOriginalValues();

		return contentSharingImpl;
	}

	public int compareTo(ContentSharing contentSharing) {
		long primaryKey = contentSharing.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		ContentSharing contentSharing = null;

		try {
			contentSharing = (ContentSharing)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = contentSharing.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ContentSharingModelImpl contentSharingModelImpl = this;

		contentSharingModelImpl._originalCompanyId = contentSharingModelImpl._companyId;

		contentSharingModelImpl._setOriginalCompanyId = false;

		contentSharingModelImpl._originalGroupId = contentSharingModelImpl._groupId;

		contentSharingModelImpl._setOriginalGroupId = false;

		contentSharingModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ContentSharing> toCacheModel() {
		ContentSharingCacheModel contentSharingCacheModel = new ContentSharingCacheModel();

		contentSharingCacheModel.contentId = getContentId();

		contentSharingCacheModel.companyId = getCompanyId();

		contentSharingCacheModel.groupId = getGroupId();

		contentSharingCacheModel.userId = getUserId();

		contentSharingCacheModel.contentSharing = getContentSharing();

		String contentSharing = contentSharingCacheModel.contentSharing;

		if ((contentSharing != null) && (contentSharing.length() == 0)) {
			contentSharingCacheModel.contentSharing = null;
		}

		return contentSharingCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{contentId=");
		sb.append(getContentId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", contentSharing=");
		sb.append(getContentSharing());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.bkav.portal.portlet.contentsharing.model.ContentSharing");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>contentId</column-name><column-value><![CDATA[");
		sb.append(getContentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>contentSharing</column-name><column-value><![CDATA[");
		sb.append(getContentSharing());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ContentSharing.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			ContentSharing.class
		};
	private long _contentId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private String _userUuid;
	private String _contentSharing;
	private long _columnBitmask;
	private ContentSharing _escapedModelProxy;
}