/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bkav.portal.portlet.topic.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Topic service. Represents a row in the &quot;Asset_Topic&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bkav.portal.portlet.topic.model.impl.TopicModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bkav.portal.portlet.topic.model.impl.TopicImpl}.
 * </p>
 *
 * @author anhbdb
 * @see Topic
 * @see com.bkav.portal.portlet.topic.model.impl.TopicImpl
 * @see com.bkav.portal.portlet.topic.model.impl.TopicModelImpl
 * @generated
 */
public interface TopicModel extends BaseModel<Topic>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a topic model instance should use the {@link Topic} interface instead.
	 */

	/**
	 * Returns the primary key of this topic.
	 *
	 * @return the primary key of this topic
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this topic.
	 *
	 * @param primaryKey the primary key of this topic
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the topic ID of this topic.
	 *
	 * @return the topic ID of this topic
	 */
	public long getTopicId();

	/**
	 * Sets the topic ID of this topic.
	 *
	 * @param topicId the topic ID of this topic
	 */
	public void setTopicId(long topicId);

	/**
	 * Returns the group ID of this topic.
	 *
	 * @return the group ID of this topic
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this topic.
	 *
	 * @param groupId the group ID of this topic
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this topic.
	 *
	 * @return the company ID of this topic
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this topic.
	 *
	 * @param companyId the company ID of this topic
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this topic.
	 *
	 * @return the user ID of this topic
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this topic.
	 *
	 * @param userId the user ID of this topic
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this topic.
	 *
	 * @return the user uuid of this topic
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this topic.
	 *
	 * @param userUuid the user uuid of this topic
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this topic.
	 *
	 * @return the user name of this topic
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this topic.
	 *
	 * @param userName the user name of this topic
	 */
	public void setUserName(String userName);

	/**
	 * Returns the topic name of this topic.
	 *
	 * @return the topic name of this topic
	 */
	@AutoEscape
	public String getTopicName();

	/**
	 * Sets the topic name of this topic.
	 *
	 * @param topicName the topic name of this topic
	 */
	public void setTopicName(String topicName);

	/**
	 * Returns the category IDs of this topic.
	 *
	 * @return the category IDs of this topic
	 */
	@AutoEscape
	public String getCategoryIds();

	/**
	 * Sets the category IDs of this topic.
	 *
	 * @param categoryIds the category IDs of this topic
	 */
	public void setCategoryIds(String categoryIds);

	/**
	 * Returns the create date of this topic.
	 *
	 * @return the create date of this topic
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this topic.
	 *
	 * @param createDate the create date of this topic
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this topic.
	 *
	 * @return the modified date of this topic
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this topic.
	 *
	 * @param modifiedDate the modified date of this topic
	 */
	public void setModifiedDate(Date modifiedDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Topic topic);

	public int hashCode();

	public CacheModel<Topic> toCacheModel();

	public Topic toEscapedModel();

	public String toString();

	public String toXmlString();
}