/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bkav.portal.portlet.portalplugins.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ePortals service. Represents a row in the &quot;ePortals&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bkav.portal.portlet.portalplugins.model.impl.ePortalsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bkav.portal.portlet.portalplugins.model.impl.ePortalsImpl}.
 * </p>
 *
 * @author AnhBDb
 * @see ePortals
 * @see com.bkav.portal.portlet.portalplugins.model.impl.ePortalsImpl
 * @see com.bkav.portal.portlet.portalplugins.model.impl.ePortalsModelImpl
 * @generated
 */
public interface ePortalsModel extends BaseModel<ePortals> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e portals model instance should use the {@link ePortals} interface instead.
	 */

	/**
	 * Returns the primary key of this e portals.
	 *
	 * @return the primary key of this e portals
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e portals.
	 *
	 * @param primaryKey the primary key of this e portals
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the eportal ID of this e portals.
	 *
	 * @return the eportal ID of this e portals
	 */
	public long getEportalId();

	/**
	 * Sets the eportal ID of this e portals.
	 *
	 * @param eportalId the eportal ID of this e portals
	 */
	public void setEportalId(long eportalId);

	/**
	 * Returns the eportal name of this e portals.
	 *
	 * @return the eportal name of this e portals
	 */
	@AutoEscape
	public String getEportalName();

	/**
	 * Sets the eportal name of this e portals.
	 *
	 * @param eportalName the eportal name of this e portals
	 */
	public void setEportalName(String eportalName);

	/**
	 * Returns the eportal code of this e portals.
	 *
	 * @return the eportal code of this e portals
	 */
	@AutoEscape
	public String getEportalCode();

	/**
	 * Sets the eportal code of this e portals.
	 *
	 * @param eportalCode the eportal code of this e portals
	 */
	public void setEportalCode(String eportalCode);

	/**
	 * Returns the eportal domain of this e portals.
	 *
	 * @return the eportal domain of this e portals
	 */
	@AutoEscape
	public String getEportalDomain();

	/**
	 * Sets the eportal domain of this e portals.
	 *
	 * @param eportalDomain the eportal domain of this e portals
	 */
	public void setEportalDomain(String eportalDomain);

	/**
	 * Returns the eportal version of this e portals.
	 *
	 * @return the eportal version of this e portals
	 */
	@AutoEscape
	public String getEportalVersion();

	/**
	 * Sets the eportal version of this e portals.
	 *
	 * @param eportalVersion the eportal version of this e portals
	 */
	public void setEportalVersion(String eportalVersion);

	/**
	 * Returns the create date of this e portals.
	 *
	 * @return the create date of this e portals
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this e portals.
	 *
	 * @param createDate the create date of this e portals
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modify date of this e portals.
	 *
	 * @return the modify date of this e portals
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this e portals.
	 *
	 * @param modifyDate the modify date of this e portals
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the group ID of this e portals.
	 *
	 * @return the group ID of this e portals
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this e portals.
	 *
	 * @param groupId the group ID of this e portals
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this e portals.
	 *
	 * @return the company ID of this e portals
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this e portals.
	 *
	 * @param companyId the company ID of this e portals
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this e portals.
	 *
	 * @return the user ID of this e portals
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this e portals.
	 *
	 * @param userId the user ID of this e portals
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this e portals.
	 *
	 * @return the user uuid of this e portals
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this e portals.
	 *
	 * @param userUuid the user uuid of this e portals
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this e portals.
	 *
	 * @return the user name of this e portals
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this e portals.
	 *
	 * @param userName the user name of this e portals
	 */
	public void setUserName(String userName);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ePortals ePortals);

	public int hashCode();

	public CacheModel<ePortals> toCacheModel();

	public ePortals toEscapedModel();

	public String toString();

	public String toXmlString();
}