/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bkav.portal.portlet.portalplugins.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PortalPlugins service. Represents a row in the &quot;PortalPlugins&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bkav.portal.portlet.portalplugins.model.impl.PortalPluginsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bkav.portal.portlet.portalplugins.model.impl.PortalPluginsImpl}.
 * </p>
 *
 * @author AnhBDb
 * @see PortalPlugins
 * @see com.bkav.portal.portlet.portalplugins.model.impl.PortalPluginsImpl
 * @see com.bkav.portal.portlet.portalplugins.model.impl.PortalPluginsModelImpl
 * @generated
 */
public interface PortalPluginsModel extends BaseModel<PortalPlugins> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a portal plugins model instance should use the {@link PortalPlugins} interface instead.
	 */

	/**
	 * Returns the primary key of this portal plugins.
	 *
	 * @return the primary key of this portal plugins
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this portal plugins.
	 *
	 * @param primaryKey the primary key of this portal plugins
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the plugin ID of this portal plugins.
	 *
	 * @return the plugin ID of this portal plugins
	 */
	public long getPluginId();

	/**
	 * Sets the plugin ID of this portal plugins.
	 *
	 * @param pluginId the plugin ID of this portal plugins
	 */
	public void setPluginId(long pluginId);

	/**
	 * Returns the plugin name of this portal plugins.
	 *
	 * @return the plugin name of this portal plugins
	 */
	@AutoEscape
	public String getPluginName();

	/**
	 * Sets the plugin name of this portal plugins.
	 *
	 * @param pluginName the plugin name of this portal plugins
	 */
	public void setPluginName(String pluginName);

	/**
	 * Returns the plugin code of this portal plugins.
	 *
	 * @return the plugin code of this portal plugins
	 */
	@AutoEscape
	public String getPluginCode();

	/**
	 * Sets the plugin code of this portal plugins.
	 *
	 * @param pluginCode the plugin code of this portal plugins
	 */
	public void setPluginCode(String pluginCode);

	/**
	 * Returns the plugin version of this portal plugins.
	 *
	 * @return the plugin version of this portal plugins
	 */
	public double getPluginVersion();

	/**
	 * Sets the plugin version of this portal plugins.
	 *
	 * @param pluginVersion the plugin version of this portal plugins
	 */
	public void setPluginVersion(double pluginVersion);

	/**
	 * Returns the plugin type of this portal plugins.
	 *
	 * @return the plugin type of this portal plugins
	 */
	public int getPluginType();

	/**
	 * Sets the plugin type of this portal plugins.
	 *
	 * @param pluginType the plugin type of this portal plugins
	 */
	public void setPluginType(int pluginType);

	/**
	 * Returns the e portal ID of this portal plugins.
	 *
	 * @return the e portal ID of this portal plugins
	 */
	public long getEPortalId();

	/**
	 * Sets the e portal ID of this portal plugins.
	 *
	 * @param ePortalId the e portal ID of this portal plugins
	 */
	public void setEPortalId(long ePortalId);

	/**
	 * Returns the is important of this portal plugins.
	 *
	 * @return the is important of this portal plugins
	 */
	public int getIsImportant();

	/**
	 * Sets the is important of this portal plugins.
	 *
	 * @param isImportant the is important of this portal plugins
	 */
	public void setIsImportant(int isImportant);

	/**
	 * Returns the plugin description of this portal plugins.
	 *
	 * @return the plugin description of this portal plugins
	 */
	@AutoEscape
	public String getPluginDescription();

	/**
	 * Sets the plugin description of this portal plugins.
	 *
	 * @param pluginDescription the plugin description of this portal plugins
	 */
	public void setPluginDescription(String pluginDescription);

	/**
	 * Returns the plugin update info of this portal plugins.
	 *
	 * @return the plugin update info of this portal plugins
	 */
	@AutoEscape
	public String getPluginUpdateInfo();

	/**
	 * Sets the plugin update info of this portal plugins.
	 *
	 * @param pluginUpdateInfo the plugin update info of this portal plugins
	 */
	public void setPluginUpdateInfo(String pluginUpdateInfo);

	/**
	 * Returns the plugin size of this portal plugins.
	 *
	 * @return the plugin size of this portal plugins
	 */
	public double getPluginSize();

	/**
	 * Sets the plugin size of this portal plugins.
	 *
	 * @param pluginSize the plugin size of this portal plugins
	 */
	public void setPluginSize(double pluginSize);

	/**
	 * Returns the war file ID of this portal plugins.
	 *
	 * @return the war file ID of this portal plugins
	 */
	public long getWarFileId();

	/**
	 * Sets the war file ID of this portal plugins.
	 *
	 * @param warFileId the war file ID of this portal plugins
	 */
	public void setWarFileId(long warFileId);

	/**
	 * Returns the sign file ID of this portal plugins.
	 *
	 * @return the sign file ID of this portal plugins
	 */
	public long getSignFileId();

	/**
	 * Sets the sign file ID of this portal plugins.
	 *
	 * @param signFileId the sign file ID of this portal plugins
	 */
	public void setSignFileId(long signFileId);

	/**
	 * Returns the create date of this portal plugins.
	 *
	 * @return the create date of this portal plugins
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this portal plugins.
	 *
	 * @param createDate the create date of this portal plugins
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modify date of this portal plugins.
	 *
	 * @return the modify date of this portal plugins
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this portal plugins.
	 *
	 * @param modifyDate the modify date of this portal plugins
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the group ID of this portal plugins.
	 *
	 * @return the group ID of this portal plugins
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this portal plugins.
	 *
	 * @param groupId the group ID of this portal plugins
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this portal plugins.
	 *
	 * @return the user ID of this portal plugins
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this portal plugins.
	 *
	 * @param userId the user ID of this portal plugins
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this portal plugins.
	 *
	 * @return the user uuid of this portal plugins
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this portal plugins.
	 *
	 * @param userUuid the user uuid of this portal plugins
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the company ID of this portal plugins.
	 *
	 * @return the company ID of this portal plugins
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this portal plugins.
	 *
	 * @param companyId the company ID of this portal plugins
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user name of this portal plugins.
	 *
	 * @return the user name of this portal plugins
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this portal plugins.
	 *
	 * @param userName the user name of this portal plugins
	 */
	public void setUserName(String userName);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(PortalPlugins portalPlugins);

	public int hashCode();

	public CacheModel<PortalPlugins> toCacheModel();

	public PortalPlugins toEscapedModel();

	public String toString();

	public String toXmlString();
}