/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bkav.portal.portlet.rss.service.base;

import com.bkav.portal.portlet.rss.model.RssFeed;
import com.bkav.portal.portlet.rss.service.RssFeedLocalService;
import com.bkav.portal.portlet.rss.service.RssFeedService;
import com.bkav.portal.portlet.rss.service.persistence.RssFeedFinder;
import com.bkav.portal.portlet.rss.service.persistence.RssFeedPersistence;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the rss feed local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.bkav.portal.portlet.rss.service.impl.RssFeedLocalServiceImpl}.
 * </p>
 *
 * @author hungdx
 * @see com.bkav.portal.portlet.rss.service.impl.RssFeedLocalServiceImpl
 * @see com.bkav.portal.portlet.rss.service.RssFeedLocalServiceUtil
 * @generated
 */
public abstract class RssFeedLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements RssFeedLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.bkav.portal.portlet.rss.service.RssFeedLocalServiceUtil} to access the rss feed local service.
	 */

	/**
	 * Adds the rss feed to the database. Also notifies the appropriate model listeners.
	 *
	 * @param rssFeed the rss feed
	 * @return the rss feed that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public RssFeed addRssFeed(RssFeed rssFeed) throws SystemException {
		rssFeed.setNew(true);

		return rssFeedPersistence.update(rssFeed, false);
	}

	/**
	 * Creates a new rss feed with the primary key. Does not add the rss feed to the database.
	 *
	 * @param id_ the primary key for the new rss feed
	 * @return the new rss feed
	 */
	public RssFeed createRssFeed(long id_) {
		return rssFeedPersistence.create(id_);
	}

	/**
	 * Deletes the rss feed with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id_ the primary key of the rss feed
	 * @return the rss feed that was removed
	 * @throws PortalException if a rss feed with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public RssFeed deleteRssFeed(long id_)
		throws PortalException, SystemException {
		return rssFeedPersistence.remove(id_);
	}

	/**
	 * Deletes the rss feed from the database. Also notifies the appropriate model listeners.
	 *
	 * @param rssFeed the rss feed
	 * @return the rss feed that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public RssFeed deleteRssFeed(RssFeed rssFeed) throws SystemException {
		return rssFeedPersistence.remove(rssFeed);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(RssFeed.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return rssFeedPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return rssFeedPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return rssFeedPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return rssFeedPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public RssFeed fetchRssFeed(long id_) throws SystemException {
		return rssFeedPersistence.fetchByPrimaryKey(id_);
	}

	/**
	 * Returns the rss feed with the primary key.
	 *
	 * @param id_ the primary key of the rss feed
	 * @return the rss feed
	 * @throws PortalException if a rss feed with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public RssFeed getRssFeed(long id_) throws PortalException, SystemException {
		return rssFeedPersistence.findByPrimaryKey(id_);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return rssFeedPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the rss feeds.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of rss feeds
	 * @param end the upper bound of the range of rss feeds (not inclusive)
	 * @return the range of rss feeds
	 * @throws SystemException if a system exception occurred
	 */
	public List<RssFeed> getRssFeeds(int start, int end)
		throws SystemException {
		return rssFeedPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of rss feeds.
	 *
	 * @return the number of rss feeds
	 * @throws SystemException if a system exception occurred
	 */
	public int getRssFeedsCount() throws SystemException {
		return rssFeedPersistence.countAll();
	}

	/**
	 * Updates the rss feed in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param rssFeed the rss feed
	 * @return the rss feed that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public RssFeed updateRssFeed(RssFeed rssFeed) throws SystemException {
		return updateRssFeed(rssFeed, true);
	}

	/**
	 * Updates the rss feed in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param rssFeed the rss feed
	 * @param merge whether to merge the rss feed with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the rss feed that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public RssFeed updateRssFeed(RssFeed rssFeed, boolean merge)
		throws SystemException {
		rssFeed.setNew(false);

		return rssFeedPersistence.update(rssFeed, merge);
	}

	/**
	 * Returns the rss feed local service.
	 *
	 * @return the rss feed local service
	 */
	public RssFeedLocalService getRssFeedLocalService() {
		return rssFeedLocalService;
	}

	/**
	 * Sets the rss feed local service.
	 *
	 * @param rssFeedLocalService the rss feed local service
	 */
	public void setRssFeedLocalService(RssFeedLocalService rssFeedLocalService) {
		this.rssFeedLocalService = rssFeedLocalService;
	}

	/**
	 * Returns the rss feed remote service.
	 *
	 * @return the rss feed remote service
	 */
	public RssFeedService getRssFeedService() {
		return rssFeedService;
	}

	/**
	 * Sets the rss feed remote service.
	 *
	 * @param rssFeedService the rss feed remote service
	 */
	public void setRssFeedService(RssFeedService rssFeedService) {
		this.rssFeedService = rssFeedService;
	}

	/**
	 * Returns the rss feed persistence.
	 *
	 * @return the rss feed persistence
	 */
	public RssFeedPersistence getRssFeedPersistence() {
		return rssFeedPersistence;
	}

	/**
	 * Sets the rss feed persistence.
	 *
	 * @param rssFeedPersistence the rss feed persistence
	 */
	public void setRssFeedPersistence(RssFeedPersistence rssFeedPersistence) {
		this.rssFeedPersistence = rssFeedPersistence;
	}

	/**
	 * Returns the rss feed finder.
	 *
	 * @return the rss feed finder
	 */
	public RssFeedFinder getRssFeedFinder() {
		return rssFeedFinder;
	}

	/**
	 * Sets the rss feed finder.
	 *
	 * @param rssFeedFinder the rss feed finder
	 */
	public void setRssFeedFinder(RssFeedFinder rssFeedFinder) {
		this.rssFeedFinder = rssFeedFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.bkav.portal.portlet.rss.model.RssFeed",
			rssFeedLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.bkav.portal.portlet.rss.model.RssFeed");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return RssFeed.class;
	}

	protected String getModelClassName() {
		return RssFeed.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = rssFeedPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = RssFeedLocalService.class)
	protected RssFeedLocalService rssFeedLocalService;
	@BeanReference(type = RssFeedService.class)
	protected RssFeedService rssFeedService;
	@BeanReference(type = RssFeedPersistence.class)
	protected RssFeedPersistence rssFeedPersistence;
	@BeanReference(type = RssFeedFinder.class)
	protected RssFeedFinder rssFeedFinder;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private RssFeedLocalServiceClpInvoker _clpInvoker = new RssFeedLocalServiceClpInvoker();
}