/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bkav.portal.portlet.rss.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the RssFeed service. Represents a row in the &quot;RssFeed&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bkav.portal.portlet.rss.model.impl.RssFeedModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bkav.portal.portlet.rss.model.impl.RssFeedImpl}.
 * </p>
 *
 * @author hungdx
 * @see RssFeed
 * @see com.bkav.portal.portlet.rss.model.impl.RssFeedImpl
 * @see com.bkav.portal.portlet.rss.model.impl.RssFeedModelImpl
 * @generated
 */
public interface RssFeedModel extends BaseModel<RssFeed>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rss feed model instance should use the {@link RssFeed} interface instead.
	 */

	/**
	 * Returns the primary key of this rss feed.
	 *
	 * @return the primary key of this rss feed
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rss feed.
	 *
	 * @param primaryKey the primary key of this rss feed
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_ of this rss feed.
	 *
	 * @return the id_ of this rss feed
	 */
	public long getId_();

	/**
	 * Sets the id_ of this rss feed.
	 *
	 * @param id_ the id_ of this rss feed
	 */
	public void setId_(long id_);

	/**
	 * Returns the group ID of this rss feed.
	 *
	 * @return the group ID of this rss feed
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this rss feed.
	 *
	 * @param groupId the group ID of this rss feed
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this rss feed.
	 *
	 * @return the company ID of this rss feed
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this rss feed.
	 *
	 * @param companyId the company ID of this rss feed
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this rss feed.
	 *
	 * @return the user ID of this rss feed
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this rss feed.
	 *
	 * @param userId the user ID of this rss feed
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this rss feed.
	 *
	 * @return the user uuid of this rss feed
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this rss feed.
	 *
	 * @param userUuid the user uuid of this rss feed
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this rss feed.
	 *
	 * @return the user name of this rss feed
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this rss feed.
	 *
	 * @param userName the user name of this rss feed
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this rss feed.
	 *
	 * @return the create date of this rss feed
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this rss feed.
	 *
	 * @param createDate the create date of this rss feed
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this rss feed.
	 *
	 * @return the modified date of this rss feed
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this rss feed.
	 *
	 * @param modifiedDate the modified date of this rss feed
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this rss feed.
	 *
	 * @return the name of this rss feed
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this rss feed.
	 *
	 * @param name the name of this rss feed
	 */
	public void setName(String name);

	/**
	 * Returns the url of this rss feed.
	 *
	 * @return the url of this rss feed
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this rss feed.
	 *
	 * @param url the url of this rss feed
	 */
	public void setUrl(String url);

	/**
	 * Returns the description of this rss feed.
	 *
	 * @return the description of this rss feed
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this rss feed.
	 *
	 * @param description the description of this rss feed
	 */
	public void setDescription(String description);

	/**
	 * Returns the status of this rss feed.
	 *
	 * @return the status of this rss feed
	 */
	public int getStatus();

	/**
	 * Sets the status of this rss feed.
	 *
	 * @param status the status of this rss feed
	 */
	public void setStatus(int status);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(RssFeed rssFeed);

	public int hashCode();

	public CacheModel<RssFeed> toCacheModel();

	public RssFeed toEscapedModel();

	public String toString();

	public String toXmlString();
}